added splice-call feature in goto instrument
diffblue/cbmc pull request #1360
Opened 2017-09-07 19:50 UTC by KPouliasis

it prepends a nullary function call say foo in the body of another call say moo when called as --splice-call moo,foo  . Also added tests

2017-09-08 11:35 UTC, kroening requested changes

2017-09-08 11:35 UTC, kroening commented on regression/splice_call_01/main.c
> +}
stupid nit: two extra spaces

2017-09-08 11:35 UTC, kroening commented on src/goto-instrument/goto_instrument_parse_options.cpp
> +  if(cmdline.isset("splice-call"))
extra space between splice and option

2017-09-08 11:35 UTC, kroening commented on src/goto-instrument/splice_call.cpp
> +{
We usually use two spaces here.

2017-09-08 11:36 UTC, kroening commented
BTW, how closely related is this to the --function-enter instrumentation?
Could these be consolidated?

2017-09-12 23:18 UTC, KPouliasis commented
Hi Daniel, good point. It actually is. I was wondering if this could be made available so that Elizabeth could use my tool (that depends on it) and I will refactor my implementation to use code in function.cpp when I am back to school in a week.

2017-09-18 22:06 UTC, kroening approved these changes

2017-09-18 22:07 UTC, merged