Fix pointer type
diffblue/cbmc pull request #1390
Opened 2017-09-14 15:10 UTC by kroening

Pointers in the frontend (before type checking) are different, and don't yet obey the type invariant of pointer_typet.

2017-09-14 15:46 UTC, reuk reviewed
We have no way of enforcing, or even *seeing* that the pointer ends up with a width in all cases. At least if we use the `pointer_typet` constructor, we know that the object is a valid instance of that type. I don't understand how this change is an improvement.

2017-09-14 15:46 UTC, reuk commented on src/ansi-c/c_typecheck_type.cpp
> +    source_locationt source_location=type.source_location();
Should be const.

2017-09-14 15:46 UTC, reuk commented on src/ansi-c/c_typecheck_type.cpp
> +    source_locationt source_location=type.source_location();
Should be const.

2017-09-26 22:13 UTC, kroening commented
The type invariant problem is now addressed. There are now frontend_pointers, which do not have a width, which then get turned into pointers, which do have it.

2017-09-27 07:59 UTC, reuk requested changes

2017-09-27 07:59 UTC, reuk commented on src/ansi-c/ansi_c_convert_type.cpp
> +    tmp.set(ID_width, config.ansi_c.pointer_width);
This should use the proper pointer_type constructor

2017-09-29 13:58 UTC, peterschrammel approved these changes
lgtm modulo addressing @reuk's comments

2017-09-29 21:19 UTC, merged