Split the entry-point-generation phase into two parts
diffblue/cbmc pull request #1394
Opened 2017-09-15 15:12 UTC by smowton

The new generate_support_functions phase creates __CPROVER_start and __CPROVER_initialize and runs before lazy loading; the final phase will run *after* lazy loading, and is therefore used to patch up changes that require functions' bodies to have been loaded already.

In subsequent PRs, lazy loading will take advantage of this to read __CPROVER_start and use it to guide its work; CI-lazy-loading will use it to replace its current hackish logic to guess how globals and parameters will be initialised.

2017-09-15 15:18 UTC, reuk requested changes
Virtual methods used to customize behavior should generally be private.

2017-09-15 15:18 UTC, reuk commented on src/util/language.h
> +  virtual bool generate_support_functions(
Should probably be `private`.

2017-09-18 10:18 UTC, thk123 approved these changes
Seems reasonable - some suggestions if you agree with them. One thing to bare in mind is that the language appears to get thrown away and recreated (meaning the cmdline isn't parsed to the new instance). I'm going to create a PR that basically `assert`s that this is called _before_ calling any of the methods. You  might want to rebase this ontop of that and add the assert to `generate_support_functions` if it gets in first...

2017-09-18 10:18 UTC, thk123 commented on src/ansi-c/ansi_c_language.cpp
> +bool ansi_c_languaget::generate_support_functions(
Consider adding doxygen documentation for what supporting functions this generates (opaque functions, entry point)

2017-09-18 10:18 UTC, thk123 commented on src/goto-programs/initialize_goto_model.cpp
> +          msg.error() << "ENTRY-POINT GENERATION ERROR" << messaget::eom;
Though most of `generate_support_functions` is related to the entry point, in might be worth calling this `SUPPORT FUNCTION ERROR`. Alternatively, could have the `generate_support_functions` throw structured exceptions for error states?

2017-09-18 10:32 UTC, mgudemann commented on src/java_bytecode/java_bytecode_language.cpp
> +  return false;
Would you mind adding a comment to this?
Sometime later it might not be obvious why this cannot fail.

2017-09-18 15:55 UTC, smowton commented on src/ansi-c/ansi_c_language.cpp
> +bool ansi_c_languaget::generate_support_functions(
I have this in `languaget`, is that enough or does it have to be duplicated in derived classes?

2017-09-18 16:17 UTC, smowton commented
@thk123 suggest checking https://github.com/diffblue/security-scanner/pull/192/files for the latest version of this (will update that one once this passes)--

Changes since this version:
* Removed `generate_entry_point`, replaced with a call to `generate_support_functions` (which must work correctly if run more than once; amended the Java version to match the Ansi-C version in this respect)
* Only use `rebuild_goto_start_function` when the binaries provided one and we're directed to overwrite it; otherwise run the `language_filest` version which searches for a frontend that can provide an entry-point.
* Move declaration of the `--function` option into `languaget`, which is I think its proper owner

2017-09-19 10:22 UTC, thk123 commented
@smowton Sorry your last message confused me - which PR should I be reviewing, this on diffblue/security-scanner#192?

2017-09-19 12:30 UTC, smowton commented
@thk123 please review diffblue/security-scanner#192 then I once that's in I will clone it into this one for submission to develop

2017-09-19 15:15 UTC, peterschrammel commented on src/cbmc/cbmc_parse_options.cpp
> -    if(cmdline.isset("function"))
Why is this removed? What replaces this functionality?

2017-09-19 15:15 UTC, peterschrammel commented on src/goto-programs/initialize_goto_model.cpp
> +          msg.error() << "ENTRY-POINT GENERATION ERROR" << messaget::eom;
Structured exception will come, but let's do that separately.

2017-09-19 15:15 UTC, peterschrammel commented on src/util/language_file.cpp
> +  for(file_mapt::iterator it=file_map.begin();
ranged for?

2017-09-19 15:38 UTC, smowton commented on src/cbmc/cbmc_parse_options.cpp
> -    if(cmdline.isset("function"))
This was a duplicate of functionality already in `initialize_goto_model` -- it was previously overwriting the start function twice.

2017-09-19 15:38 UTC, smowton commented on src/util/language_file.cpp
> +  for(file_mapt::iterator it=file_map.begin();
ok

2017-09-20 12:22 UTC, thk123 commented
I've reviewed 192 - once you've updated this PR to mirror could you ping me so I can create a TG bump since this will probably require some changes (I overhead you mention about the TG specific version of the language)

2017-09-20 15:21 UTC, smowton commented
@thk123 @peterschrammel this has been updated; Peter your suggested C++11 loops have been added as a separate commit.

2017-09-21 19:38 UTC, peterschrammel approved these changes

2017-09-22 08:53 UTC, thk123 commented
I am creating a TG bump for this to verify it - but then can be merged

2017-09-22 09:16 UTC, smowton commented
@thk123 please press the button when you're happy

2017-09-25 09:04 UTC, thk123 requested changes
For those out of ear shot of me and @smowton - there was a problem merging in to TG which @smowton is looking at at the moment.

2017-10-04 10:41 UTC, smowton commented
Updated; created companion test-gen PR https://github.com/diffblue/test-gen/pull/1085 to verify this doesn't break it

2017-10-04 11:28 UTC, thk123 approved these changes

2017-10-04 11:28 UTC, thk123 commented
TG bump passes so have set approval.

2017-10-04 11:54 UTC, merged