Replace use of expr visitor by loop with depth_begin in find_index
diffblue/cbmc pull request #1428
Opened 2017-09-29 12:37 UTC by romainbrenguier

This makes the code clearer and more succinct

2017-09-29 12:39 UTC, jasigal approved these changes
LGTM, glad we can use `exprt` iterators.

2017-09-29 12:42 UTC, LAJW requested changes

2017-09-29 12:42 UTC, LAJW commented on src/solvers/refinement/string_refinement.cpp
> +      const index_exprt &i=to_index_expr(expr);
I'd rename `i` to `index`, as `i` is usually the name used by the incremented integer in a loop.

2017-09-29 12:42 UTC, LAJW commented on src/solvers/refinement/string_refinement.cpp
> +  for(auto it=expr.depth_begin(); it!=expr.depth_end(); ++it)
Use `std::find` since you're not mutating.

2017-09-29 13:19 UTC, LAJW approved these changes

2017-09-29 13:35 UTC, LAJW approved these changes

2017-10-09 16:46 UTC, thk123 approved these changes

2017-10-13 09:46 UTC, merged