Remove tautological typecasts
diffblue/cbmc pull request #1438
Opened 2017-10-02 16:08 UTC by reuk

Java bytecode doesn't really have a concept of a 'boolean', which means that exprs generated from Java bytecode sometimes contain unnecessary casts of the form `(boolean)(int)boolean`. This PR is designed to remove such casts.

At the moment the simplify_expr unit test is failing on my machine, even when using the version from `develop` (i.e. without these changes). I'm submitting this to see whether it gets through travis CI. If it does, I'll add a unit test for simplify_expr which checks the new behaviour.

2017-10-02 18:57 UTC, kroening commented on src/util/simplify_expr.cpp
> +     ns.follow(expr.op0().op0().type()).id()==ID_c_bool)
use to_typecast_exprt to stay type-safe

2017-10-02 18:57 UTC, kroening requested changes

2017-10-02 18:57 UTC, kroening commented on src/util/simplify_expr.cpp
> +     ns.follow(expr.op0().op0().type()).id()==ID_c_bool)
The ns.follow is not needed

2017-10-03 13:06 UTC, reuk commented
@kroening @pkesseli Please review

2017-10-03 16:31 UTC, tautschnig requested changes

2017-10-03 16:31 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +      simplify_node(expr.op0().op0());
This is redundant as that simplification has already been performed.

2017-10-03 16:31 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +     op_type.id()==ID_signedbv)
I believe this case should be merged into the next case ("// eliminate casts to _Bool").

2017-10-03 17:00 UTC, reuk commented
@tautschnig I've responded to feedback, please re-review

2017-10-03 17:02 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +        expr=expr.op0().op0();
`expr=typecast.op();`

2017-10-03 17:03 UTC, tautschnig approved these changes
Apart from the remaining suggestion added moments ago this looks good to me.

2017-10-03 17:04 UTC, tautschnig commented on unit/util/simplify_expr.cpp
> +    typecast_exprt{
Use `(` to keep the linter happy. (And me, but I don't count.)

2017-10-04 09:42 UTC, pkesseli approved these changes

2017-10-04 09:42 UTC, pkesseli commented on src/util/simplify_expr.cpp
> +      const auto typecast=to_typecast_expr(expr.op0());
Nit-pick: This can be a reference:
```c++
const auto &typecast=to_typecast_expr(expr.op0()); 
```

2017-10-04 09:47 UTC, reuk commented
Fixed, please re-review

2017-10-04 09:48 UTC, tautschnig commented
Looks good to me (but then I had given my approval already). @kroening?

2017-10-04 14:04 UTC, reuk commented
This is blocking my work. I have two approvals, and have addressed @kroening 's concerns. Could someone merge this please?

2017-10-04 14:39 UTC, merged

2017-10-04 14:40 UTC, reuk commented
Thanks!