Allow expr_dynamic_cast to be used with std_code types
diffblue/cbmc pull request #1441
Opened 2017-10-03 16:30 UTC by reuk

Provides some utility methods for the types in std_code.h, which allow them to be used with expr_dynamic_cast.

Suggest @NathanJPhillips and @smowton to review.

2017-10-03 16:47 UTC, NathanJPhillips requested changes

2017-10-03 16:47 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +template<typename T> void validate_expr(const T &) {}
Does this need to be templated? Can it just take `exprt`?

2017-10-03 16:47 UTC, NathanJPhillips commented on src/util/std_code.h
> +template <typename Tag>
space after `template`?

2017-10-03 16:47 UTC, NathanJPhillips commented on src/util/std_code.h
> +  INVARIANT(x.operands().size()>=1, "Decls must have one or more operands");
`validate_operands(x, 1, "Decls must have one or more operands", true);`
Although I think there may be a bug in `validate_operands` that you'll need to fix too.

2017-10-03 16:47 UTC, NathanJPhillips commented on src/util/std_code.h
> +  validate_operands(x, 0, "Goto must have no operands");
"mustn't have" seems better English.

2017-10-03 16:47 UTC, NathanJPhillips commented on src/util/std_code.h
> +  validate_operands(x, 1, "Expression must have one operands");
operand, not operands

2017-10-03 17:33 UTC, reuk commented
Made suggested changes

2017-10-04 08:59 UTC, NathanJPhillips requested changes

2017-10-04 08:59 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +/// a template specialization) to validate particular types.
template specialisation comment now redundant.

2017-10-04 09:02 UTC, smowton commented
Suggest adding comments indicating for each code where you *didn't* supply a validate, what prevented you from doing so

2017-10-04 09:24 UTC, NathanJPhillips commented
On the other hand, validating invariant while casting is fairly arbitrary - why not validate on member access or at any other point. Don't feel compelled to add validation before being able to merge this useful improvement as long as there wasn't validation when casting before.

2017-10-04 09:44 UTC, reuk commented
Fixed-up, please re-review

2017-10-04 09:47 UTC, smowton approved these changes
Ahh, I thought they had tricky edge cases where they were sometimes used with odd operand numbers; turns out you were just mirroring the existing validation code. Thanks for clarifying!

2017-10-04 09:49 UTC, NathanJPhillips approved these changes

2017-10-04 14:06 UTC, reuk commented
@smowton @NathanJPhillips I've updated this with the feature I discussed (separate `dynamic_cast` and `checked_cast` implementations), could you review the last four commits please?

2017-10-06 11:15 UTC, NathanJPhillips requested changes

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +// We hide these functions in a namespace so that only functions that they only
English. Perhaps "so that functions only"?

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +  typedef typename std::decay<T>::type TUnderlyingt;
Generally wouldn't start typedefs with a capital T, perhaps `underlying_typet`?

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +  return expr_try_checked_cast<T>(base);
Why isn't this infinite recursion?

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +  typedef typename std::decay<T>::type TUnderlyingt;
Is it worth creating a typedef rather than just using it inline?

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +  typedef typename std::remove_reference<T>::type TConstt;
Is it worth creating a typedef rather than just using it inline?

2017-10-06 11:15 UTC, NathanJPhillips commented on src/util/expr_cast.h
> +expr_try_checked_cast(TExpr &base)
This operation doesn't make sense. If you assert your check will pass then why would you force yourself to write code to handle the case that you're saying can't happen?

2017-10-06 14:25 UTC, NathanJPhillips approved these changes

2017-10-06 14:25 UTC, NathanJPhillips commented
Squash and go as far as I'm concerned.

2017-10-06 15:34 UTC, merged