use std::size_t in interpreter
diffblue/cbmc pull request #1484
Opened 2017-10-14 17:58 UTC by kroening

2017-10-16 08:57 UTC, mgudemann requested changes

2017-10-16 08:57 UTC, mgudemann commented on src/goto-programs/interpreter.cpp
> +      std::size_t address=integer2unsigned(evaluate_address(code_assign.lhs()));
should be `integer2size_t`

2017-10-16 09:00 UTC, mgudemann commented on src/goto-programs/interpreter.cpp
> +      std::size_t address=integer2unsigned(evaluate_address(code_assign.lhs()));
somehow related to this PR, there are also occurrences of `size_t` and not `std::size_t`

2017-10-16 13:41 UTC, tautschnig requested changes
Can this please be synchronised with #1330?

2017-10-16 19:47 UTC, kroening commented
See comments in #1330.

2017-10-16 20:35 UTC, kroening commented
There are a few remaining issues in the code, that could be addressed in a separate PR. In particular, we could worry about the case in which an address actually does exceed a 64-bit integer; or where it exceeds a size_t, and a vector is used. We could then give a graceful error message.

2017-10-17 09:39 UTC, mgudemann approved these changes
LGTM but the name of the PR should probably be changed now to include the `mp_integer` additions

2017-10-17 10:01 UTC, reuk approved these changes

2017-10-18 07:53 UTC, mgudemann commented
@tautschnig are you ok with the comments on #1330 , i.e., using `mp_integer` here instead of any atomic integral type?

2017-10-23 08:00 UTC, mgudemann commented
@tautschnig would you mind having a look, considering @kroening 's comment?

2017-10-23 08:02 UTC, tautschnig approved these changes
I am assuming that #1330 should just be closed as this PR effectively does the same?

2017-10-23 08:02 UTC, tautschnig commented
> @tautschnig would you mind having a look, considering @kroening 's comment?

Been looking right in this moment ...

2017-10-23 08:02 UTC, merged

2017-10-23 08:03 UTC, peterschrammel commented
@mgudemann, does this make https://github.com/diffblue/cbmc/pull/987 obsolete?

2017-10-23 13:15 UTC, mgudemann commented
@peterschrammel yes, this is also an `mp_integer` now. The only thing is that it says `2^32` in the comment, but actually returns `2^33`
```
  if(unbounded_size(type))
    return mp_integer(2) << 32;
```

but the issue on 32-bit should be resolved with this PR

2017-10-24 08:06 UTC, peterschrammel commented
@mgudemann, then please close https://github.com/diffblue/cbmc/pull/987.