Add symbol table writer
diffblue/cbmc pull request #1496
Opened 2017-10-18 17:07 UTC by smowton

This wraps a symbol table, providing an interface matching its write side
(but not type-compatible, to avoid implicit casts between the two), and
journals modifcations such that callers can determine what changes were made
by code using this wrapper to add, update and remove symbols

2017-10-18 17:08 UTC, smowton commented
@NathanJPhillips should also review

2017-10-19 08:59 UTC, smowton commented
(Alternative to #1446)

2017-10-19 09:03 UTC, smowton commented
@kroening @tautschnig review of the lazy loading use case indicates around 200 lines of code will need to change (mostly switching function prototypes form `symbol_tablet` to the writer wrapper class, plus introducing an overload of `get_fresh_aux_symbol` to work against the writer). That's comparable to the number of changes needed to introduce `concrete_symbol_tablet`, but these are concentrated in the Java frontend.

2017-10-20 17:21 UTC, NathanJPhillips requested changes
This doesn't show the code churn that this version causes, it might be worth including a use site (without doing anything with it) in the place that we'll be using it for lazy loading.

As a general comment on the approach, this method requires the symbol_tablet-using methods being recorded to be updated and doesn't facilitate use by a caller on existing symbol_tablet code as the other approach does. This prevents it being used so easily by new parts of the code base - with the other version using it elsewhere would only introduce a change at the call site, with this version another user would have to change the signature of any functions they wanted to record. 

Finally this version doesn't allow sub-recording (recording of changes by a single part of an operation that is already being recorded).

All these comments are issues of this general approach and if they are just the price we pay for reducing the impact on other code then that's fine.

A change to the implementation is requested below.

2017-10-20 17:21 UTC, NathanJPhillips commented on src/util/symbol_table_writer.h
> +    base_symbol_table(other.base_symbol_table)
This appears to lose all change records. Better to delete the copy constructor and add a move constructor instead.

2017-10-24 15:44 UTC, kroening commented
I would have called the unit test unit/util/symbol_table_writer.cpp (independently, there should be one for the regular symbol table). Otherwise fine!

2017-10-24 15:44 UTC, kroening approved these changes

2017-10-24 15:45 UTC, merged