TG-1158: Add a unit test for specialising Java generic types with array types
diffblue/cbmc pull request #1545
Opened 2017-10-31 17:06 UTC by chrisr-diffblue

This PR is built on top of https://github.com/diffblue/cbmc/pull/1543, and as such shows one commit (helper function) in common with PR1543

2017-10-31 17:08 UTC, smowton approved these changes

2017-10-31 17:27 UTC, thk123 requested changes
I'm not certain - but I think your test is looking at the array field rather than the generic field specialised with an array.

2017-10-31 17:27 UTC, thk123 commented on unit/java_bytecode/generate_concrete_generic_type/generate_java_generic_type.cpp
> +      to_struct_type(test_class_symbol.type).components()[3].type();
Nit: use `require_type::require_component` to get the specific components type (not obvious that  `components()[3]` corresponds to `f`

2017-10-31 17:27 UTC, thk123 commented on unit/java_bytecode/generate_concrete_generic_type/generate_java_generic_type.cpp
> +      to_struct_type(test_class_symbol.type).components()[3].type();
In fact, is it actually pointing to `af` if the type is pointer to `array[reference]`?

2017-10-31 17:27 UTC, thk123 commented on unit/java_bytecode/generate_concrete_generic_type/generic_field_array_instantiation.java
> +    generic<Float []> f;
The logic to specialise these is moving to just specialise inputs for functions - you may want to modify this test to directly call the specialisation logic for the generic field.

2017-11-01 18:10 UTC, thk123 approved these changes

2017-11-01 18:11 UTC, merged