Further improvements to unified_difft
diffblue/cbmc pull request #1557
Opened 2017-11-02 19:43 UTC by janmroczkowski

Follow up to https://github.com/diffblue/cbmc/pull/1526
contains https://github.com/diffblue/cbmc/pull/1554

2017-11-02 19:46 UTC, janmroczkowski commented
@reuk @LAJW

2017-11-02 21:11 UTC, reuk requested changes

2017-11-02 21:11 UTC, reuk commented on src/goto-diff/unified_diff.cpp
> +    return {};
Should return `differences` here.

2017-11-03 14:06 UTC, reuk approved these changes

2017-11-03 14:35 UTC, tautschnig approved these changes

2017-11-03 14:35 UTC, merged