[TG-1157] Add specialised java generic class type.
diffblue/cbmc pull request #1576
Opened 2017-11-10 13:52 UTC by NlightNFotis

2017-11-13 11:12 UTC, mgudemann requested changes

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/generate_java_generic_type.cpp
> +//    replacement_components);
should have commented-out code here

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/generate_java_generic_type.cpp
> +    // NOTE: the tag absolutely has to be BasicGeneric
what does `BasicGeneric` here mean?

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/generate_java_generic_type.cpp
> +    else
with the above invariant, is this case possible at all ?

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/generate_java_generic_type.cpp
> +    else if(parameter_type.subtype().id() == ID_symbol)
what are the cases that can happen here? The only one seems to be arrays, please add a short documentation here.

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/java_types.h
> +  // note the constryctor could take the components and construct it itself
typo: constructor

2017-11-13 11:12 UTC, mgudemann commented on src/java_bytecode/java_types.h
> +  // TODO: to be defined more appropriately.
TODO for whom?

2017-11-13 11:12 UTC, mgudemann commented on unit/java_bytecode/generate_concrete_generic_type/generate_java_generic_type.cpp
> +  const irep_idt test_class =
does this work with the changed implementation for arrays as generic parameters? These should now be of the form `java::array[reference]of_java::inner_type`

2017-11-21 16:55 UTC, NlightNFotis commented
This is being superseded by https://github.com/diffblue/cbmc/pull/1606. Thanks for your comments everyone.

2017-11-21 16:55 UTC, closed without merging