Use -p option of test.pl instead of printer script
diffblue/cbmc pull request #1605
Opened 2017-11-21 09:50 UTC by romainbrenguier

This script was removed, so mentions of it in Makefiles need to be
replaced by usage of -p option of test.pl.

2017-11-21 09:59 UTC, LAJW approved these changes

2017-11-23 22:39 UTC, tautschnig requested changes
Thanks a lot for this PR, but please add one minor consistency fix (to each changed line).

2017-11-23 22:39 UTC, tautschnig commented on regression/jbmc-strings/Makefile
> +	../test.pl -p -c ../../../src/jbmc/jbmc
Please hide the output of this line by prefixing it with an `@`. (I wouldn't strictly mind, but this is how it's done in all other regression/*/Makefile.)

2017-11-24 12:12 UTC, tautschnig approved these changes

2017-11-24 12:12 UTC, merged