Add extra tests for the non-det issue with constants.
diffblue/cbmc pull request #1679
Opened 2017-12-20 15:46 UTC by NlightNFotis

This is essentially #1678, ported from `goto-analyzer-develop` to `develop`. 

Paging @martin-cs for a review.

2017-12-20 16:11 UTC, tautschnig requested changes

2017-12-20 16:11 UTC, tautschnig commented on regression/goto-instrument/no_nondet_const/test.desc
> +--nondet-static a.out
I believe you need to drop "a.out" from the above to make tests work.

2017-12-21 11:52 UTC, NlightNFotis commented
@tautschnig I have implemented the fix and it now passes CI. Should be ready to be merged now.

2017-12-21 12:01 UTC, tautschnig approved these changes

2017-12-21 12:07 UTC, tautschnig commented
The changes as such are fine, thanks. Yet could I please ask for the commit message to be amended to answer the “Why?” question? I had to click through three pull requests to even understand what this was good for. And then none of that info will be in the git history.

If I have one Christmas wish for this project, it is that everyone reads and adheres to https://chris.beams.io/posts/git-commit/. Happy Holidays!

2018-01-10 22:21 UTC, martin-cs commented
@NlightNFotis I'd really like to merge this; please can you sort this out?

2018-01-11 10:25 UTC, NlightNFotis commented
@tautschnig @martin-cs  Is the new commit message better?

2018-01-11 10:30 UTC, tautschnig commented
Thanks a lot for the update! Except for a typo ("teh") that seems perfect. I'll merge once CI completes.

2018-01-11 10:35 UTC, NlightNFotis commented
@tautschnig I also fixed the typo. Now it should be okay.

2018-01-11 14:07 UTC, merged