Add --flush option to flush all output
diffblue/cbmc pull request #1712
Opened 2018-01-09 11:33 UTC by karkhaz

2018-01-09 13:20 UTC, smowton approved these changes
Do as cpplint asks; otherwise seems like a handy addition.

2018-01-09 14:37 UTC, kroening commented on src/util/cout_message.h
> +    : always_flush(always_flush)
Needs an 'explicit'

2018-01-09 15:39 UTC, kroening commented
See comment for missing 'explicit'

2018-01-14 12:19 UTC, martin-cs approved these changes
Looks good.

2018-01-14 12:20 UTC, martin-cs requested changes
Sorry -- can we have the flush option and help string as macros and in the relevant header?  (Your timer patch does this well).

2018-02-13 12:06 UTC, martin-cs commented
@karkhaz : still interested, from my point of view it just needs that change then it is good to go.

2018-04-11 14:32 UTC, karkhaz commented
Thanks for your patience @kroening @martin-cs @tautschnig, I've rebased & addressed all comments on this; all tests are passing.

2018-04-11 19:19 UTC, tautschnig requested changes

2018-04-11 19:19 UTC, tautschnig commented on src/cbmc/cbmc_parse_options.h
> +  "(flush)" \
That should be `OPT_FLUSH`  as is  used elsewhere.

2018-04-11 19:19 UTC, tautschnig commented on src/util/cout_message.cpp
> +  if(always_flush || level <= 6)
That does not seem to be correct: the previous code would (intentionally) flush `std::cout` in some levels as that's where output is sent to.

2018-04-11 19:19 UTC, tautschnig commented on src/util/ui_message.cpp
> +      console_message_handlert console_message_handler(always_flush);
JSON and XML streams should also be flushed.

2018-04-12 09:46 UTC, karkhaz commented
@tautschnig that's done, all checks have passed. Would you mind checking that the JSON & XML flush is in the right place? I tested it by replacing the call to flush with `out << "foo\n"` and it seemed to do the right thing when I passed `--flush`, but not sure if it covers all cases.

2018-04-12 10:14 UTC, tautschnig requested changes

2018-04-12 10:14 UTC, tautschnig commented on src/cbmc/cbmc_parse_options.cpp
> +    HELP_FLUSH
Could you please also add this to goto-analyzer (and possibly goto-diff)?

2018-04-12 10:14 UTC, tautschnig commented on src/util/ui_message.cpp
> +        flush(1);
Replace `1` by `level`

2018-04-12 10:14 UTC, tautschnig commented on src/util/ui_message.cpp
> +    flush(1);
Replace `1` by `level`

2018-04-12 11:34 UTC, karkhaz commented
Comments addressed. All tests are passing, except that the one that failed because Travis ran out of disk space. Should I re-force-push, or will somebody investigate this?

`level` is not in scope for `xml_ui_msg()`, so I added a `level` parameter to both that function and its caller `ui_msg()`. On the other hand, `json_ui_msg` does not need a `level` parameter since the caller flushes it.

2018-04-12 12:00 UTC, tautschnig approved these changes

2018-04-12 12:03 UTC, tautschnig commented
> `level` is not in scope for `xml_ui_msg()`, so I added a `level` parameter to both that function and its caller `ui_msg()`. On the other hand, `json_ui_msg` does not need a `level` parameter since the caller flushes it.

Very true - but then wouldn't the same actually hold for `xml_ui_msg`?

(I have restarted the Travis job.)

2018-04-12 12:03 UTC, tautschnig commented
@martin-cs If/when you have a minute, could you please re-review?

2018-04-12 12:14 UTC, karkhaz commented
Yes, you're right, I didn't follow the control flow up far enough. it looks like flushing for both XML and JSON should be taken care of on line 153. I've just re-pushed.

2018-04-20 08:35 UTC, karkhaz commented
@martin-cs this is ready to go, are you happy with it?

2018-05-01 09:51 UTC, martin-cs approved these changes
Looks fine to me.  I'm unsure about @tautschnig 's comment about JSON and XML streams.  I'd be tempted to say they should be flushed at the end of objects...

2018-05-02 17:29 UTC, merged