Complete instanceof for Java.
diffblue/cbmc pull request #1716
Opened 2018-01-09 15:33 UTC by mgudemann

The current implementation did not consider correctly the case of `null` in
`ID_java_instanceof`. An instanceof with `null` always fails. For `a instanceof
B` this now adds `a != null` to the condition.

2018-01-09 16:42 UTC, tautschnig commented
This is a bug fix, please add a corresponding regression test.

2018-01-09 16:44 UTC, tautschnig requested changes
See my earlier comment: needs a regression test.

2018-01-09 16:44 UTC, tautschnig commented on src/goto-programs/remove_instanceof.cpp
> +    check_ptr, null_pointer_exprt(to_pointer_type(check_ptr.type())));
I'd suggest `notequal_exprt non_null_expr( ... )`

2018-01-09 17:24 UTC, thk123 approved these changes
I know we have a test in TG, but if possible might be good to have a regression in JBMC too.

2018-01-09 17:24 UTC, thk123 commented on src/goto-programs/remove_instanceof.cpp
> +  exprt non_null_expr = notequal_exprt(
I would be tempted to put the construction of the non_null_expr directly below the comment.

The LHS can be more precisely typed as a `notequal_exprt`.

2018-01-09 18:52 UTC, tautschnig commented on src/goto-programs/remove_instanceof.cpp
> +  notequal_exprt non_null_expr = notequal_exprt(
Is the use of the assignment a left-over?

2018-01-09 18:56 UTC, mgudemann commented
yes, is removed now, thanks!

On 9 January 2018 at 19:52, Michael Tautschnig <notifications@github.com>
wrote:

> *@tautschnig* commented on this pull request.
> ------------------------------
>
> In src/goto-programs/remove_instanceof.cpp
> <https://github.com/diffblue/cbmc/pull/1716#discussion_r160493940>:
>
> > @@ -113,15 +113,20 @@ std::size_t remove_instanceoft::lower_instanceof(
>    newinst->source_location=this_inst->source_location;
>    newinst->function=this_inst->function;
>
> -  // Replace the instanceof construct with a big-or.
> +  // Replace the instanceof construct with a conjunction of non-null and the
> +  // disjunction of all possible object types. According to the Java
> +  // specification, null instanceof T is false for all possible values of T.
> +  // (http://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.20.2)
> +  notequal_exprt non_null_expr = notequal_exprt(
>
> Is the use of the assignment a left-over?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/diffblue/cbmc/pull/1716#pullrequestreview-87621093>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACeHTPhTjfeIqSM8Aov45O830-aIvCdlks5tI7VfgaJpZM4RYAbB>
> .
>

2018-01-09 19:00 UTC, tautschnig commented
The changes now look fine, but I'd really really appreciate a test here.

2018-01-10 08:13 UTC, mgudemann commented
@tautschnig @thk123 I added a public regression test for this

2018-01-10 09:01 UTC, tautschnig approved these changes

2018-01-10 10:00 UTC, thk123 approved these changes

2018-01-10 12:14 UTC, merged