Expose MiniSAT's `interrput()`
diffblue/cbmc pull request #1750
Opened 2018-01-17 21:00 UTC by pkesseli

Makes MiniSAT's `interrput()` and `clearInterrupt()` available to direct
users. This allows aborting a running SAT query, e.g. in the context of
multiple queries on different threads.

Once this feature is required with other solvers as well, it may be
useful to create a `virtual` function in `cnf_solvert` or even
`prop_convt`, but for now this feature is uniquely required for our
experiments with MiniSAT.

2018-01-17 21:35 UTC, peterschrammel requested changes
Requires consolidation with existing functionality: https://github.com/diffblue/cbmc/pull/1750/files#diff-06aa807a64c05c257f735d2f6868a5adR154

2018-01-17 21:35 UTC, peterschrammel commented on src/solvers/sat/satcheck_minisat2.cpp
> +void satcheck_minisat2_baset<T>::clearInterrupt()
`clear_interrupt`

2018-01-17 22:57 UTC, pkesseli commented
I think that `static` variable and the `signal` handler were created by @smowton. They're only used in the context of a timeout for MiniSAT using a `SIGALRM`. With this change we could theoretically store a pointer to the wrapper rather than the MiniSAT solver, but that seems more complicated.

2018-01-17 23:08 UTC, peterschrammel approved these changes
As I understand from our discussion, the purpose of this PR is not to provide a new propt feature, but to perform a proof-of-concept which is limited to Minisat.

Please fix the typos in the commit message.

2018-01-18 10:05 UTC, smowton commented
FWIW my SIGALRM stuff never ended up being used, because there are so many other potential sources of excessively time-consuming execution that managing them all is probably unworkable, cf. managing the problem at process granularity.

2018-01-18 10:13 UTC, tautschnig approved these changes

2018-01-20 10:33 UTC, merged