[WIP] Fix a problem with function pointers removal including the wrong functions as a target
diffblue/cbmc pull request #1754
Opened 2018-01-18 15:35 UTC by NlightNFotis

Hi. Please note that this is WIP, I haven't finished yet, I think it contains an issue which I am investigating, but I am publishing it in the hopes that it gets some early reviews now. Please keep in mind that the code will be cleaned up further, and commit names and everything is going to be cleaned up as well, once am done with what I am doing now.

Now, about the issue itself: One of the problems that had been reported to us was that `goto-instrument`, once directed to `--remove-function-pointers`, it would do that but the resulting simplification would include some erroneous functions. This happened because the simplification was applying some rules, including that the functions had the same type, when it calculated the targets. In the example included as the test, this meant that we were getting output such as:

```
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))g1 THEN GOTO 1
        // 3 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f4 THEN GOTO 2
        // 4 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f3 THEN GOTO 3
        // 5 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f2 THEN GOTO 4
        // 6 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))g2 THEN GOTO 5
        // 7 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f1 THEN GOTO 6
```

which includes the functions `g1` and `g2`, which is obviously wrong, as they are not present in the array `fptbl1`.

I would happy to see people's thoughts on the general solution.

2018-01-18 16:17 UTC, NlightNFotis commented
@martin-cs I only have one request for you in for this PR, to see if I can validate some results:

If I clone this repo, and clean build from `goto-analyzer-develop`, I get the following results:

```
IF fptbl1[(signed long int)id1][(signed long int)id2] == g1 THEN GOTO 1
        // 3 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == f4 THEN GOTO 2
        // 4 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == f3 THEN GOTO 3
        // 5 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == f2 THEN GOTO 4
        // 6 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == g2 THEN GOTO 5
        // 7 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == f1 THEN GOTO 6
```

Contrary to this, if I clean build from `develop`, I get the following results:

```
IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))g1 THEN GOTO 1
        // 3 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f4 THEN GOTO 2
        // 4 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f3 THEN GOTO 3
        // 5 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f2 THEN GOTO 4
        // 6 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))g2 THEN GOTO 5
        // 7 file function_pointer.c line 21 function func
        IF fptbl1[(signed long int)id1][(signed long int)id2] == (signed int (*)(void))f1 THEN GOTO 6
```

What's striking me is that the `goto-analyzer-develop` results are missing the function pointer cast that's present on the results from develop. Obviously this is something that I haven't introduced, and I can't judge if this is correct or not, so I would appreciate if you could explain to me where this was introduced and why, mostly for my own understanding.

2018-01-18 22:53 UTC, tautschnig requested changes
The code here seems to be written to deal with exactly that one regression test as it does not make any attempt to inspect the structure of an expression before recursing into it. Apart from that problem I have commented on a number of stylistic issues as such learning may be useful for future coding.

That said, I think this code is not taking the right approach, and indeed this constant folding attempt done in function-pointer removal is IMHO not appropriate. There are two different domains at play here: function pointers and constant propagation. The latter cannot be done soundly without the former, thus they must either operate in a Cartesian product (kind-of what is done here, but not actually doing constant propagation as an abstract domain), or be done in sequence. If it were me, I'd revert most of the changes that have been made to function-pointer removal, and instead do a constant-propagation pass after function-pointer removal. Yet @thk123 or @martin-cs might violently disagree.

2018-01-18 22:53 UTC, tautschnig commented on src/goto-programs/remove_function_pointers.cpp
> +          index_expr.array().get_sub()[0].get("identifier");
Some notes on style: this should be `index_expr.array().op0().get(ID_identifier)` (do not use `get_sub` and never use string constants).

2018-01-18 22:53 UTC, tautschnig commented on src/goto-programs/remove_function_pointers.cpp
> +        const int array_size=array.get_sub().size();
`.operands().size()`, and the return type is `std::size_t`, but really this shouldn't be necessary (see below).

2018-01-18 22:53 UTC, tautschnig commented on src/goto-programs/remove_function_pointers.cpp
> +        for(int i=0; i<array_size; i++)
Use iterators!

2018-01-18 22:53 UTC, tautschnig commented on src/goto-programs/remove_function_pointers.cpp
> +          const int subarray_length=first_array.get_sub().size();
How do you even know this is an array of arrays?

2018-01-18 22:53 UTC, tautschnig commented on src/goto-programs/remove_function_pointers.cpp
> +            const auto &typecast_first_element=element.get_sub()[0];
How do you know this going to be a typecast?

2018-01-18 23:23 UTC, martin-cs commented
<snip>
> That said, I think this code is not taking the right approach, and indeed this constant folding attempt done in function-pointer removal is IMHO not appropriate.
I agree.

>  There are two different domains at play here: function pointers and constant propagation.
I'm not sure how I feel about function pointers as a domain...

>  The latter cannot be done soundly without the former, thus they must either operate in a Cartesian product (kind-of what is done here, but not actually doing constant propagation as an abstract domain), or be done in sequence.
Yes.

>  If it were me, I'd revert most of the changes that have been made to function-pointer removal, and instead do a constant-propagation pass after function-pointer removal. Yet @thk123 or @martin-cs might violently disagree.
'fraid I do :-)

The additions to the function pointer removal to handle constant
expressions was meant for a very specific use-case.  When the expression
giving the function pointer can be resolved to one / a small number of
alternatives based purely on the structure of the expression and types
involved.  It is the:

const fp dispatch_table [10] = {&firstTask, &secondTask, ... };

CALL dispatch_table[3]

case.  Critically it *does not* and *should not* know anything about the
context / state of the process.  For me that is the dividing line.

There are issues elsewhere for how to handle function pointer removal
that requires context / state knowledge.  My suggested approach is:

1. Refactor function pointer removal slightly to give a set of
possibilities for each CALL site.

2. Get ai_baset to be able to tolerate function pointer being left in
(actually not too hard now).

3. Add domain support for tracking function pointers where needed.

4. Get goto-analyze --simplify to be able to do function pointer removal
based on the domain.

2019-04-05 10:23 UTC, NlightNFotis commented
There's a new plan for how to approach this, and my early investigation shows that this is not reusable at all, as this is as mentioned previously just a very narrow fix of a particular use case.

2019-04-05 10:23 UTC, closed without merging