Java: infer opaque type fields before method conversion
diffblue/cbmc pull request #1764
Opened 2018-01-23 15:36 UTC by smowton

Before, opaque types' fields were inferred after a method is converted to codet (for example,
if we converted a method that accessed field A.x and type A didn't have a field x yet,
we would add it at this stage). This was problematic when converting functions on demand, as
we might create instances of an opaque type but then realise upon converting a later method
that it ought to have had more fields than we realised.

This commit changes our strategy to infer the types earlier, before any methods are converted.
This may lead to unnecessary work, but the pass executes very quickly even if thousands of
classes are loaded, so I expect the penalty to be minimal compared to the advantage that the
layout of types is fixed and will not change under the feet of subsequent passes.

2018-01-23 15:36 UTC, smowton commented
@NathanJPhillips may be interested in reviewing this

2018-01-23 22:04 UTC, peterschrammel approved these changes
LGTM

2018-01-24 15:11 UTC, thk123 reviewed
A TG pointer bump would be appreciated.

2018-01-24 15:11 UTC, thk123 commented on src/java_bytecode/java_bytecode_language.cpp
> +/// them. Note that we don't yet try to infer inheritence between opaque types
It would be good if you could elaborate the comment on what happens in this case (where a field gets added twice)

2018-01-24 15:11 UTC, thk123 commented on src/java_bytecode/java_bytecode_language.cpp
> +            add_to_components.back().set_pretty_name(component_name);
I don't know if required here, but it might be sensible to put a default access using `set_access`?

2018-01-24 15:52 UTC, smowton commented
@thk123 changes applied. TG bump: https://github.com/diffblue/test-gen/pull/1411

2018-01-24 17:27 UTC, thk123 approved these changes
Thanks - that sounds fairly serious (casting between opaque types) is that a known limitation? Assuming TG bump passes LGTM

2018-01-24 17:30 UTC, smowton commented
Just thought of it while maintaining this code -- this doesn't add a new shortcoming, it just comments on an existing one.

Re: level of seriousness, yes it's clearly not ideal, though the use case is fairly fringe. We could observe attempted up- or downcasts and therefore infer a class hierarchy, but it's probably not high priority work.

2018-01-25 10:27 UTC, thk123 requested changes
Adding a blocker due to TG bump failure which needs to be fixed first

2018-01-25 17:45 UTC, smowton commented
@thk123 fixed.

2018-01-25 18:05 UTC, thk123 approved these changes
TG bump looks fine

2018-01-26 10:36 UTC, merged