Fix java harness for main()
diffblue/cbmc pull request #1768
Opened 2018-01-26 01:12 UTC by peterschrammel

This PR fixes 3 bugs:
1. the elements of the String[] args of main() must be non-null
2. the main() method was not correctly recognized (for two different reasons)
3. the maybe-null/not-null initialization of the elements of String[] was broken

The regression tests require https://github.com/diffblue/cbmc/pull/1735 to pass.

TG bump is coming...

2018-01-26 09:45 UTC, romainbrenguier approved these changes

2018-01-26 09:45 UTC, romainbrenguier commented on src/java_bytecode/java_entry_point.cpp
> +    is_main=(named_main && has_correct_type && public_access);
spacing is not consistent, can you run clang-format

2018-01-26 09:45 UTC, romainbrenguier commented on regression/cbmc-java/main-args-elements-non-null2/Main.java
> +	int i = s.length(); // must not fail
indentation look wrong

2018-01-26 09:45 UTC, romainbrenguier commented on regression/cbmc-java/main-args-elements-non-null3/Main.java
> +      assert(args[0] == null); // must fail
Since with your changes strings will be null when `--refine-strings` is not activated, does that mean that `args.length` will always be 0?

2018-01-26 10:05 UTC, smowton reviewed
Some problems with the tests when --java-throw-runtime-exceptions is not enabled, and the "null if string-refinement is not enabled" behaviour sounds odd.

Also I have a feeling this might be the only user we'll ever see of `max_nonnull_tree_depth`? Not sure if there's a better solution, but it seems an odd thing for the object factory to be able to do when anyone else wanting to use that feature sounds unlikely.

2018-01-26 10:05 UTC, smowton commented on regression/cbmc-java/main-args-elements-non-null2/Main.java
> +    catch(Exception e) {
This won't happen without `--java-throw-runtime-exceptions`. Perhaps it would be better to simply assert `s != null`?

2018-01-26 10:05 UTC, smowton commented on regression/cbmc-java/main-args-elements-non-null4/Main.java
> +	  int i = s.length(); // definitely must not fail
Again the exception path is unreachable, but what are you testing for here?

2018-01-26 10:05 UTC, smowton commented on regression/cbmc-java/main-args-non-null2/Main.java
> +    catch(Exception e) {
Same situation -- exception is unreachable whatever happens due to no `--java-throw-runtime-exceptions`.

2018-01-26 10:05 UTC, smowton commented on src/java_bytecode/java_object_factory.cpp
> +  if(struct_type.get_bool(ID_incomplete_class))
No String model does not imply incomplete-class -- for example, we might have a real java.lang.String in the classpath.

2018-01-26 10:05 UTC, smowton commented on src/java_bytecode/java_object_factory.cpp
> +  // Also, if the String model is not loaded then we can only
??? Even if we have an incomplete java.lang.String, we can supply `{ @class_identifier = "java.lang.String" }`

2018-02-16 15:34 UTC, thk123 requested changes
I'm pretty sure your last commit is wrong - specifically, I don't think `Ljava.lang.String;` is a valid signature/descriptor type string (the dots should be slashes in bytecode strings). 

More generally, I think a better approach to certain inputs being not null might be to mark them in the symbol table in some way (perhaps allowing future models to specify parts that are non-null and parts that are not in a more granular manner). 

There are lots of tests with quite a lot of overlap, but I think one that checks that more than the first element is guaranteed to be non-null in suitable cases is missing:

```java
public class Main
{
  public static void main(String[] args)
  {
    if(args.length>1)
      assert(args[0] != null); // must hold
      assert(args[1] != null); // must hold
  }
}
```

2018-02-16 15:34 UTC, thk123 commented on src/java_bytecode/java_entry_point.cpp
> +    bool public_access = function.type.get(ID_access) == ID_public;
Prefer storing `function.type` in a `code_typet` and use `get_access` rather than direct irep access.

2018-02-16 15:34 UTC, thk123 commented on src/goto-programs/convert_nondet.cpp
>    const goto_programt::targett &target,
Nit: typo in commit "Fix java harness for main()"
> argument to the main() functio

(`function`)

2018-02-16 15:34 UTC, thk123 commented on src/java_bytecode/java_entry_point.cpp
> +      parameters.max_nonnull_tree_depth = 1;
If it `is_main` doesn't this want to be `2`?

2018-02-16 15:34 UTC, thk123 commented on src/java_bytecode/java_entry_point.cpp
> +      parameters.max_nonnull_tree_depth = 1;
I see this is fixed in a later commit

2018-02-16 15:34 UTC, thk123 commented on regression/cbmc-java/main-args-elements-non-null3/Main.java
> +      assert(args[0] == null); // must fail
Not sure what this test tests that the first test doesn't?

2018-02-16 15:34 UTC, thk123 commented on src/java_bytecode/java_types.cpp
> +  std::replace(class_name.begin(), class_name.end(), '$', '.');
I need to verify this more carefully - but the reason for it being this way round is to get inner inner classes being represented in a specific manner. The example in your commit message is _not_ a valid java bytecode type descriptor by my reading of [4.2.1](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.2.1)

2018-02-28 13:02 UTC, thk123 approved these changes
Critical comments from previous review addressed - could you dismiss this if you think it requires a full re-review (looks similar enough to me)

2018-02-28 13:02 UTC, thk123 commented on src/java_bytecode/java_entry_point.cpp
> +    bool public_access = to_code_type(function.type).get_access() == ID_public;
Nit: you've already done a `to_code_type` on `function.type` (twice) so might as well put it out into a local var

2018-03-08 00:00 UTC, peterschrammel commented
@smowton, ready for re-review.

2018-03-08 09:49 UTC, smowton approved these changes

2018-06-10 21:56 UTC, peterschrammel commented
TG bump is passing

2018-06-10 22:44 UTC, merged