Add class-hierarchy variant based on grapht
diffblue/cbmc pull request #1776
Opened 2018-01-29 16:27 UTC by smowton

This mirrors the existing class_hierarchyt, except that it inherits from
grapht and so is suitable for use with generic graph algorithms.

2018-01-29 17:24 UTC, tautschnig requested changes
A nit-pick and some whitespace changes, please.

2018-01-29 17:24 UTC, tautschnig commented on src/goto-programs/class_hierarchy.cpp
> +        add_edge(nodes_by_name.at(parent), nodes_by_name.at(it->first));
Nit pick: How about `if(!parent.empty()) add_edge ...`?

2018-01-29 17:25 UTC, tautschnig commented on src/goto-programs/class_hierarchy.h
> + public:
My apologies, the key comments had gotten lost: weird 1-char indent and please merge the `public` sections, possibly by moving the `private` part to the bottom.

2018-01-29 17:38 UTC, smowton commented
@tautschnig changes applied

2018-01-29 17:49 UTC, tautschnig commented on src/goto-programs/class_hierarchy.h
> + public:
There's one 1-char indent left here.

2018-01-29 18:02 UTC, smowton commented
fixd

2018-01-29 18:02 UTC, smowton commented
@tautschnig fixed

2018-01-29 20:43 UTC, peterschrammel approved these changes
LGTM modulo clang-format

2018-01-29 21:12 UTC, tautschnig commented on src/goto-programs/class_hierarchy.h
> +  public:
Just noting that you've now got mixed indenting style for those.

2018-01-29 21:12 UTC, tautschnig approved these changes

2018-01-30 10:17 UTC, smowton commented
I was evidently not having a good day with formatting. Fixed all clang-format complaints, will merge once Travis passes.

2018-01-30 13:43 UTC, merged