Java arrays are instanceof Object
diffblue/cbmc pull request #1778
Opened 2018-01-29 20:04 UTC by peterschrammel

2018-01-30 10:13 UTC, smowton requested changes

2018-01-30 10:13 UTC, smowton commented on src/java_bytecode/java_bytecode_convert_class.cpp
> +    bases.push_back(base);
Use `struct_union_typet::baset` and `struct_union_typet::add_base`

2018-01-30 10:26 UTC, thk123 commented
A test gen bump would be appreciated for this change.

2018-02-02 13:56 UTC, thk123 requested changes
Looks good but TG pointer bump failing

2018-02-26 23:53 UTC, peterschrammel commented
@thk123, @smowton, TG is passing now.

2018-02-27 09:00 UTC, smowton approved these changes

2018-02-28 10:28 UTC, thk123 approved these changes

2018-02-28 10:28 UTC, thk123 commented on src/java_bytecode/java_bytecode_convert_class.cpp
> +    class_typet::componentt comp0(
Name suggestion: `base_class_component`

2018-02-28 10:28 UTC, thk123 commented on src/java_bytecode/java_bytecode_convert_class.cpp
> +    class_typet::componentt comp1("length", java_int_type());
Name suggestion: `length_component`

2018-02-28 10:28 UTC, thk123 commented on src/java_bytecode/java_bytecode_convert_class.cpp
> +    class_typet::componentt comp2(
Name suggestion: `data_component`

2018-03-08 15:28 UTC, merged