Documentation/review cbmc docs
diffblue/cbmc pull request #1780
Opened 2018-01-30 09:57 UTC by Charliemowood

Please look at the separate commits:

The focus of the first is to improve the layout of the table of contents.
The second commit is to make the front page more informative.
The third is separating the SATABS content from the CBMC user manual.

2018-01-30 10:14 UTC, Charliemowood commented
The layout is look like this: 
![screen shot 2018-01-30 at 09 51 01](https://user-images.githubusercontent.com/25271307/35560787-47bcc60e-05a6-11e8-80b7-0fa49be95e71.png)

2018-01-30 10:18 UTC, tautschnig commented
Could you please rebase to avoid merge commits in the pull request? Thanks!

2018-01-30 10:25 UTC, tautschnig reviewed
Looks good to me, except for the rebase to be done.

2018-01-30 10:25 UTC, tautschnig commented on doc/architectural/cbmc-guide.md
> +\page cbmc-guide CBMC Developer Manual
Nit pick: should live in the previous commit

2018-01-30 10:25 UTC, tautschnig commented on doc/architectural/front-page.md
> +overflows), pointer safety, exceptions and user-specified assertions.
I'd say "arithmetic exceptions"

2018-01-30 10:25 UTC, tautschnig commented on doc/architectural/howto.md
> +\page tutorial CBMC Developer Tutorial
As above: should go with the previous commit.

2018-01-30 11:03 UTC, Charliemowood commented
@tautschnig thanks for your thoughts. Now rebased and your docs change suggestion implemented.

2018-01-30 11:12 UTC, tautschnig approved these changes

2018-01-30 12:32 UTC, romainbrenguier approved these changes

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +and an a set of header files.
"and a set"

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +a code pre-processing environment comprising of a suitable preprocessor
"comprising a" or "including a"

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +    formulas that is currently bundled with BOPPO, but also available
nitpick: I would use which rather than that (in both occurrences)

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +CBMC and SATABS have their own requirements. As an example, both CBMC and SATABS require a suitable preprocessor and a set of header files. As
long line

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +the value of `random` is restricted to be 0 &le `random` ≤ 3 by a call
strange to have once &le and once ≤ do they both work well with doxygen?

2018-01-30 12:32 UTC, romainbrenguier commented on doc/SATABS.md
> +the models of the the string library and for `getenv`. Most of these
"of the string library"

2018-01-30 15:17 UTC, chrisr-diffblue approved these changes
Looks good - thanks for tidying this up! A couple of non-blocking comments, but won't hold this back just for those.

2018-01-30 15:17 UTC, chrisr-diffblue commented on doc/SATABS.md
> +    [XCode](http://developer.apple.com/technologies/xcode.html) prior to
Do we actually need full XCode installed for any of CBMC? Or do we just need the "XCode command line tools", which is a significantly more lightweight package to install? I think just the command line tools can be installed with 'xcode-select --install' ?

2018-01-30 15:17 UTC, chrisr-diffblue commented on doc/architectural/cbmc-guide.md
> +\page cbmc-guide CBMC Developer Manual
If the document title has changed (which I approve of) is it worth changing the file name as well to match?

2018-01-31 09:54 UTC, Charliemowood commented
@romainbrenguier and @chrisr-diffblue thanks for the feedback. Implemented those ideas.

2018-01-31 11:44 UTC, peterschrammel requested changes
@Charliemowood, please implement the structural changes and clean-ups as discussed in person.

2018-02-07 13:28 UTC, chrisr-diffblue commented on doc/architectural/front-page.md
>  3. Create a branch from the `develop` branch (default branch)
Points 1 and 2 should probably both be updated a touch too... I'd suggest something like:
1. For the CBMC repository on github
2. Clone your fork with `git clone......`

2018-02-07 13:28 UTC, chrisr-diffblue commented on doc/architectural/front-page.md
> +  the <a href="modules.html">Modules</a>.
Erroneous full stop at the end of this line - should be a comma?

2018-02-07 15:11 UTC, Charliemowood commented
@chrisr-diffblue thanks for the additional comments. Updated.

2018-02-27 18:48 UTC, Charliemowood commented
@peterschrammel the _hidden has been brought back in to deal with toc problems. This is by no means perfect but the overall structural changes we discuss are now in this. Could you please review again?

2018-03-22 22:27 UTC, peterschrammel approved these changes

2018-03-22 23:02 UTC, merged

2018-03-23 10:37 UTC, Charliemowood commented
👍