Fix process_array_expr to take into account pointer offset
diffblue/cbmc pull request #1800
Opened 2018-02-06 13:59 UTC by tautschnig

Includes code cleanup to remove an unnecessary use of process_array_expr.

2018-02-12 17:40 UTC, peterschrammel reviewed
Nice piece of work. 
Is there a test case for array_replace? I don't see how it is called in your test case.

2018-02-12 19:58 UTC, tautschnig commented
> Is there a test case for array_replace? I don't see how it is called in your test case.

It is called from (our models of) the C library functions, including `memcpy`. Is that sufficient?

2018-02-13 08:23 UTC, peterschrammel approved these changes
Found it. I searched in the wrong file.

2018-02-19 17:03 UTC, chrisr-diffblue commented on src/goto-symex/symex_clean_expr.cpp
> +      // T[S-(o/sizeof(T))]
I may have been particularly slow reading this comment (apologies if so) - but it wasn't immediately obvious to me that this it of type conversion (particularly the `o/sizeof(T)`) is to do the conversion from byte offset -> index. Maybe it's worth expanding the comment very slightly?

2018-02-20 20:18 UTC, martin-cs requested changes
Am concerned about the change in functionality but otherwise OK.

2018-02-20 20:18 UTC, martin-cs commented on src/ansi-c/ansi_c_internal_additions.cpp
>      // overwrite all of *dest (possibly using nondet values), even
I like the idea of removing special case passes, particularly ones that are sharing unaware BUT it seems like array_copy only captures some of the functionality of array_equals.  With array_equals I can build two arrays in different ways and then test their equality.

2018-02-20 20:18 UTC, martin-cs commented on src/goto-symex/symex_clean_expr.cpp
>    else if(expr.id()==ID_symbol &&
There seem to be quite a few cases that have been refactored here that, to my eyes, are not covered by the test case added.

2018-02-20 21:18 UTC, tautschnig commented
@martin-cs Thank you for getting me back on track, I'm not sure what I was doing when crafting ad728880fa55. I'll rework.

2018-02-20 21:53 UTC, martin-cs commented
@tautschnig As I said about another commit -- about half of it is "hell yes we should have done that years ago"...

2018-02-23 07:14 UTC, tautschnig commented
I have reworked all the array_equal stuff and now also included a specific regression test (rather than the more implicit ones before).

2018-03-01 12:59 UTC, tautschnig commented
@martin-cs Would you mind taking another look?

2018-03-01 14:24 UTC, martin-cs approved these changes
Looks much better.  I would still prefer some more tests for the second commit but I won't block the merge because of it.

2018-03-01 14:28 UTC, merged

2018-03-01 14:29 UTC, tautschnig commented
Just to note that the request for more tests is not being ignored: I'm trying to source them, but please bear with me as that might take some time.

2018-03-01 14:45 UTC, martin-cs commented
Sure; it wasn't supposed to be a blocking request more a "I'd feel more confident about this if...".