Introduce fieldref_exprt to represent a field reference
diffblue/cbmc pull request #1856
Opened 2018-02-16 15:03 UTC by thk123

Refactoring for some forthcoming unit tests for lamdbas - pull out this naked exprt into a reasonable type and removed a magic string while we're at it.

2018-02-16 19:26 UTC, tautschnig commented
It's surely a good idea to get rid of the local string `"fieldref"`, but why couldn't one just use a `member_exprt`?

2018-02-16 21:28 UTC, smowton commented
@tautschnig `member_exprt` isn't quite right as there is no instance of the compound type to put in `member_exprt`'s `compound` slot. `struct_componentt` is closer, but as the class we're referring to might not be loaded yet, we perhaps don't know the `struct_typet` it refers to yet. You'd need some sort of component-of-symbol_typet construction... which is more or less what we've got here ;)

2018-02-16 22:03 UTC, tautschnig commented
> You'd need some sort of component-of-symbol_typet construction... which is more or less what we've got here ;)

That sounds very much like what you get in C - all struct types in C are symbol types.

I do have a faint hope of getting rid of a bit of code?

2018-02-16 22:58 UTC, smowton commented
To the user of a concrete instance of one, sure, but does the ansi-c representation have a way to describe an abstract field of an opaque type?

2018-02-16 23:33 UTC, tautschnig commented
I don't know what an "abstract field" is?

2018-02-16 23:39 UTC, smowton commented
Describing accessing a field of a type without having a concrete instance you're making the access against. Something like `some_type::some_field` in C++ source.

2018-02-17 00:57 UTC, tautschnig commented
My take on that would be:
1. It's still a `member_exprt`, you might just need to set the `op`/`struct_op()` to `nil_exprt()`
2. The type is a symbol type.
3. There must be some  existing solution in the C++ front-end. @kroening?

Item 1 above might be a bad idea, and might be sufficiently bad to warrant a dedicated expression kind. At which point 3 kicks in, meaning that the C++ and the Java front-ends should be using the same solution.

2018-02-17 10:48 UTC, tautschnig commented
As I know very little about the Java front-end: does it make use of symbol types or `struct_tag` types? Just in case, here's what symbol/tag types provide: expressions will always retain the same type throughout their lifetime in the front-end, even when the definition of the type is not yet known. There is one single place where the definition is stored: the symbol table. Initially, the definition of the symbol type will be an `incomplete_struct`. Once the definition becomes available, the symbol table is updated. There is no need to change anything else at that point.

2018-02-18 09:54 UTC, smowton commented
Symbol types. I'm off on holiday now, and don't have a strong position on this anyhow, so I'm going to quit this thread :)

2018-02-19 14:11 UTC, thk123 commented
It is possible I'm not understanding the original design intent, but I think the more fundamental problem is using the `codet` style AST structures in the java bytecode front end before it is lowered into a language agnostic `codet`. 

I think in reality this class shouldn't be an `exprt` at all, since it would not be a valid node in a `codet` AST. That, however is a more sophisticated change that what I have time for at the moment.

2018-02-19 14:13 UTC, thk123 commented
Restarted travis as was a time out in compile which sounds like we just drew a bad box...

2018-02-21 10:38 UTC, tautschnig requested changes
I would like to send this back to the drawing board, because it unnecessarily pollutes the global string table (which also is embedded in every goto binary). The reason I view it as unnecessary is that the "fieldref"/`ID_fieldref` is not being read anywhere. Hence it would be equally fine to not set any `id()` at all.

2018-02-22 17:47 UTC, thk123 commented
@tautschnig There is clearly more work to be done to make this make sense, but looks like would need to at the very least make the `pool_entryt` not store an `exprt` and go through all the places that rely on just being able to access these arbitrary fields. For now, I've done as suggested and removed the unread string (since all I wanted was a common constructor to begin unifying this.

2018-02-23 10:07 UTC, tautschnig approved these changes
Approving with one nit-pick.

2018-02-23 10:07 UTC, tautschnig commented on src/java_bytecode/java_bytecode_parse_tree.h
> +    : exprt("", type)
Nit pick: `ID_empty_string`

2018-02-23 11:33 UTC, thk123 commented
TG pointer bump: diffblue/test-gen#1527

2018-02-23 13:33 UTC, thk123 commented
TG pointer passes :+1:

2018-02-23 13:38 UTC, thomasspriggs approved these changes
Looks fine to me.

2018-02-23 13:39 UTC, mgudemann reviewed
does this not need some `ID_fieldref_expr` ?

2018-02-23 13:42 UTC, thk123 commented
@mgudemann - see discussion with @tautschnig above - this string is not read anywhere. I think the proper fix is this wouldn't even be an `exprt`  (it certainly isn't valid to have this appear in a `codet` AST)

2018-02-23 13:48 UTC, mgudemann commented
@thk123  ok

2018-02-23 13:48 UTC, mgudemann approved these changes
LGTM

2018-02-23 14:55 UTC, merged