Unit test update for multiple java compilers [TG-2483]
diffblue/cbmc pull request #1894
Opened 2018-02-28 17:50 UTC by thomasspriggs

This is a modification to an existing unit test, to re-run the tests using class files which have been generated by various different java compilers.

2018-02-28 17:53 UTC, thomasspriggs commented
@thk123 Review this please.

2018-02-28 18:03 UTC, thk123 approved these changes

2018-03-01 09:21 UTC, tautschnig requested changes
I'm sure the changes in this PR are good and useful, but some further information is necessary for legal and maintenance purposes: how have all these binary files been generated and, which might then already be answered, is it actually legal to distribute them in this form? The answer should most likely be in the form of an extended commit message and/or a README file. Thanks!

2018-03-01 11:24 UTC, thomasspriggs commented
@tautschnig I have added a readme file, about generating the class files. The class files are the output from compiling our java files with various java compilers. They are not taken from the internals of any java compiler or internals of any java run time environment / library.

2018-03-01 11:48 UTC, tautschnig approved these changes

2018-03-01 11:48 UTC, tautschnig commented
> I have added a readme file [...]

Brilliant, thank you!

2018-03-01 15:34 UTC, thk123 approved these changes

2018-03-01 15:34 UTC, thk123 commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> +The proceedure for compiling with eclipse is different. Installing the java eclipse ide does not setup a version of javac command. So to produce the class files for eclipse, the proceedure is as foll
Nit: eclipse should be capitalised, IDE should be all caps

2018-03-01 15:34 UTC, thk123 commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> + 4. Compile the `.java` files using `javac -g ./*.java`. The `-g` flag switches on debugging output, which we require.
You can use `-d` on javac to specify the output directory, but it requires it to exist first, so don't know if it actually makes it much easier to follow the instructions...

2018-03-01 15:34 UTC, thk123 commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> +The proceedure for compiling with eclipse is different. Installing the java eclipse ide does not setup a version of javac command. So to produce the class files for eclipse, the proceedure is as foll
As above you should probably mention what version of Eclipse you are using.

2018-03-01 17:57 UTC, peterschrammel commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> +Each sub directory inside this one contains class files which have been compiled with specific java compilers. The proceedure taken to produce these files is as follows -
procedure

2018-03-01 17:57 UTC, peterschrammel commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> +The proceedure for compiling with eclipse is different. Installing the java eclipse ide does not setup a version of javac command. So to produce the class files for eclipse, the proceedure is as foll
procedure

2018-03-01 17:57 UTC, peterschrammel commented on unit/java_bytecode/java_bytecode_parser/lambda_examples/readme.md
> +The proceedure for compiling with eclipse is different. Installing the java eclipse ide does not setup a version of javac command. So to produce the class files for eclipse, the proceedure is as foll
You should be able to run the Eclipse compiler as explained here: https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

2018-03-02 11:23 UTC, hannes-steffenhagen-diffblue commented
Instead of a lengthy description, wouldn't it be easier (going forward) to include a Maven or Gradle build script that generates these class files? Both of them respect JAVA_HOME, so you don't need update-alternatives to pick different JDKs for those.

2018-03-02 11:59 UTC, thomasspriggs commented
@hannes-steffenhagen-diffblue I will bear in mind the option of using some type of build script for future instances of this type of use case. I would probably use a bash script instead of a maven file as there are no dependencies to resolve. Can JAVA_HOME be set from inside a Maven/Gradle build script or would a separate bash script be required to set this and run for each compiler anyway?

2018-03-05 17:28 UTC, merged