Update coding standard to reflect changes in #1919
diffblue/cbmc pull request #1934
Opened 2018-03-13 10:48 UTC by NathanJPhillips

See #1919.

2018-03-13 10:52 UTC, smowton approved these changes

2018-03-13 14:30 UTC, peterschrammel commented on CODING_STANDARD.md
> +  /// Author: Diffblue Ltd.
I'd rather say ` /// Author: Your Name`, because this is a guideline for all public contributors.

2018-03-13 15:25 UTC, martin-cs commented
+1 what Peter said.

2018-03-13 16:20 UTC, kroening requested changes
+1 Peter's comment

2018-03-14 11:05 UTC, NathanJPhillips commented
Good point.

2018-03-14 11:05 UTC, closed without merging