Partial solver cleanup (straightforward changes part 2)
diffblue/cbmc pull request #1956
Opened 2018-03-21 15:52 UTC by romainbrenguier

This is a subset of the changes in #1810 which shouldn't require much more discussion.

2018-03-21 16:10 UTC, tautschnig requested changes

2018-03-21 16:10 UTC, tautschnig commented on src/solvers/flattening/boolbv.cpp
> +    if(expr.op0().type().id() == ID_fixedbv)
Please remove those 'let's-remove-`else`' changes from this commit.

2018-03-21 16:10 UTC, tautschnig commented on src/solvers/flattening/boolbv_index.cpp
> +  DATA_INVARIANT(expr.operands().size() == 2, "index takes two operands");
This can be completely dropped, an `index_exprt` is guaranteed to have this.

2018-03-21 16:10 UTC, tautschnig commented on src/solvers/flattening/boolbv_abs.cpp
> +  DATA_INVARIANT(operands.size() == 1, "abs takes one operand");
May I suggest that instead the interface be changed to take a `const abs_exprt &`, which will ensure this property.

2018-03-21 16:10 UTC, tautschnig commented on src/solvers/flattening/boolbv_byte_extract.cpp
>    result.resize(src.size(), const_literal(false));
This seems redundant: use `reserve` here, and then do `push_back` in the loop.

2018-03-21 16:10 UTC, tautschnig commented on src/solvers/flattening/boolbv_byte_extract.cpp
>      return convert_bv(tmp);
`tmp` has no value - let's just do `return convert_bv(flatten_byte_extract(expr, ns));`

2018-05-17 19:22 UTC, martin-cs approved these changes
Approved assuming you'll handle the tweaks from @tautschnig

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv.cpp
> -    else if(expr.op0().type().id()==ID_fixedbv)
Why remove the else here?

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv.cpp
> +    if(expr.op0().type().id() == ID_fixedbv)
+1

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv.cpp
> +      const bvt &bv = convert_bv(operands[0]);
Yes; good catch!

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv_abs.cpp
> +  DATA_INVARIANT(operands.size() == 1, "abs takes one operand");
This would seem nice and type-safe-y.

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv_bitwise.cpp
> +            UNIMPLEMENTED;
Yes; good use of a legacy invariant macro!

2018-05-17 19:22 UTC, martin-cs commented on src/solvers/flattening/boolbv_index.cpp
> +  DATA_INVARIANT(expr.operands().size() == 2, "index takes two operands");
I agree that it should but am less opposed to checking invariants, until we have a system that hard enforces them.

2018-06-05 06:17 UTC, romainbrenguier commented on src/solvers/flattening/boolbv.cpp
> -    else if(expr.op0().type().id()==ID_fixedbv)
I reverted these changes

2018-06-05 06:17 UTC, romainbrenguier commented
@tautschnig I think I addressed all your comments

2018-06-05 07:58 UTC, tautschnig approved these changes
This is an ok first step, but it does make obvious that there is a lot of room for improvement in this code. One bit that I'd like to see happen is getting rid of all these number-of-operands checks and instead use, e.g., `to_bitnot_expr` so that the check and error message is just implemented in one place. (While at that I noticed that those checks are currently disabled in `to_bitnot_expr` for some reason.) Also, various cases of `conversion_failed` should be caught in the expression invariants.

2018-06-05 07:58 UTC, tautschnig commented on src/solvers/flattening/boolbv_byte_extract.cpp
> +  PRECONDITION(expr.operands().size() == 2);
That's guaranteed by `byte_extract_exprt`

2018-06-05 07:58 UTC, tautschnig commented on src/solvers/flattening/boolbv_byte_extract.cpp
> +      const exprt tmp = flatten_byte_extract(expr, ns);
Nit pick: `tmp` carries no value, just do `return convert_bv(flatten_byte_extract(expr, ns));`

2018-06-05 08:39 UTC, romainbrenguier commented
> This is an ok first step, but it does make obvious that there is a lot of room for improvement in this code. 
> One bit that I'd like to see happen is getting rid of all these number-of-operands checks and instead use, e.g., to_bitnot_expr so that the check and error message is just implemented in one place. 

I totally agree.

2018-06-05 12:25 UTC, merged