[SV-COMP'18 3/19] Avoid repeated hash computation, reduce irept::dt size
diffblue/cbmc pull request #1992
Opened 2018-04-03 13:43 UTC by tautschnig

On SV-COMP benchmarks, hashing accounts for >22% of CPU time (with
profiling enabled).

Do not merge: profiling data to be supplied and further improvements to SUB_IS_LIST are in the queue.

2018-04-09 08:45 UTC, smowton commented
@tautschnig could you explain why using `std::list` is related to hash caching? Or is that the reduce-dt-size bit (I guess from <start, end, capacity> for vector to <start, end> for list?)

2018-04-10 08:26 UTC, tautschnig commented
Yes, it's the reduce-dt-size bit. But it's not about going from a vector to a list (which as of C++ is three pointers as well), but instead about going from a `std::map` (which in GNU STL is six pointers) to a list.

2018-04-10 09:16 UTC, smowton commented
Ah, got you, I thought `SUB_IS_LIST` only affected `sub`, not `named_sub` / `comments`. If we're looking for space saving btw, I note `comments` is really quite rarely distinguished from `named_sub`, and by convention their names cannot clash. Should we combine them and filter when we actually want the distinction (during `operator==` only I think?)

2018-04-10 09:17 UTC, smowton commented
In fact it appears `SUB_IS_LIST` doesn't affect `sub` at all! Please rename it.

2019-03-29 23:10 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: e42bd6601aa8bd55618a5eba038fa3cfe4df20e6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/106400003
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-03-30 09:22 UTC, tautschnig commented
@peterschrammel @allredj Any idea why this is failing TG builds?

2019-03-30 12:35 UTC, tautschnig commented
> @peterschrammel @allredj Any idea why this is failing TG builds?

Never mind, @smowton confirmed that TG already builds with `-DHASH_CODE`. Will discuss on Monday whether to use `#ifndef` or just ask TG to remove that option from the build command line.

2019-03-30 12:42 UTC, smowton commented
I favour `#ifndef` for all such options as that allows `-DHASH_CODE=0` on the command-line to make a build without it

2019-03-30 12:43 UTC, tautschnig commented
> I favour #ifndef for all such options as that allows -DHASH_CODE=0 on the command-line to make a build without it

Fair point, will include this change in the next push to this branch.

2019-04-01 06:43 UTC, tautschnig commented
Commit message updated to include data points:

On some SV-COMP benchmark categories, hashing accounts for >20% of CPU
time (with profiling enabled) - top five:

* ReachSafety-BitVectors: 29.29% (470.54 seconds, which reduces to 4.39
  seconds; for benchmarks not timing out we save 170 seconds (25%) in
  non-profiling mode)
* Systems_BusyBox_NoOverflows: 27.98% (284.15 seconds, which reduces to
  1.74 seconds; for the 1 benchmark not timing out we save 23 seconds
  (6%) in non-profiling mode)
* Systems_BusyBox_MemSafety: 24.24% (194.74 seconds, which reduces to
  0.93 seconds; no measurable difference on the 2 benchmarks not
  failing/timing out)
* NoOverflows-Other: 18.84% (1127.61 seconds, which reduces to
  23.57 seconds; for benchmarks not timing out we save 5 seconds (7%) in
  non-profiling mode)
* ReachSafety-ControlFlow: 17.75% (1194.04 seconds, which reduces to
  29.17 seconds; for benchmarks not timing out we save 200 seconds (25%)
  in non-profiling mode)

For ReachSafety-ECA it's only 4.7%, which still amounts to 3006.7
seconds. With this change this reduces to 323.07 seconds. On
ReachSafety-ECA, this enables 3055.35 symex_step calls per second over
2752.28 calls per second without this change.

2019-04-01 07:34 UTC, martin-cs approved these changes
`HASH_CODE` is one of those things we probably should have been doing for some time.  If it doesn't work / has performance regressions then we should fix it and I think it should be fixable.

Semi-related : given all of the work on tidying up the constructors for exprts and the like.  How far are we from making `dt`s immutable?

2019-04-01 08:45 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 63081a5352cb8e26c57cc78ae7db66281319c95c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/106523249

2019-04-17 09:08 UTC, smowton requested changes
Your `#ifndef` actually doesn't permit manual override -- you need to do like
```
#ifndef HASH_CODE
￼ #  define HASH_CODE 1
￼ #endif

...

#if HASH_CODE == 1
```

At the moment since all the tests just use `#ifdef` there is in practice no way to override with `-D`

2019-04-17 13:01 UTC, tautschnig commented
> Your #ifndef actually doesn't permit manual override [...]

Good catch - that's now fixed!

2019-04-17 13:26 UTC, smowton approved these changes

2019-04-17 13:30 UTC, tautschnig commented
Marking do-not-merge until we have bisected a possible performance regression and also gathered feedback on this change from customers.

2019-04-17 15:59 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: abcb3c3700e2eace0463b602db50370f3c6dae5b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108705935
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-05-08 13:38 UTC, tautschnig commented
Customer feedback indicates that the degree of performance improvement may vary, but there are no red flags. Will merge as once CI completes its work.

2019-05-08 17:07 UTC, merged