minisat: use size_t to index clauses
diffblue/cbmc pull request #2034
Opened 2018-04-09 18:41 UTC by tautschnig

This enables Minisat to use more than 16GB of memory for storing clauses.

2018-04-10 08:37 UTC, smowton commented
Please add this to CMake as well -- I believe you'll want to use `ExternalProject_Add_Step` in https://github.com/diffblue/cbmc/blob/develop/src/solvers/CMakeLists.txt, probably with arguments `DEPENDEES patch DEPENDERS build` to get the step sequence download -> patch -> patch64 -> build.

2018-04-10 08:40 UTC, smowton commented
(Docs: https://cmake.org/cmake/help/v3.8/module/ExternalProject.html)

2018-04-10 11:47 UTC, tautschnig commented
@kroening Any guidance on why CodeBuild is unhappy here?

2018-04-10 12:27 UTC, smowton approved these changes
Checked cmake step; seems to be working as we'd hope

2018-04-26 09:02 UTC, kroening commented
This fails the "lots_of_local_variables" test. My suspicion is that some ordering here is undefined.

2018-04-26 09:38 UTC, kroening commented
BTW, does this impact performance on smaller instances?

2018-05-23 13:17 UTC, martin-cs requested changes
I'd like to see some performance numbers before we commit to this.

2018-05-23 13:17 UTC, martin-cs commented on scripts/minisat64.patch
> ++        p     = trail[index];
Ummm... why change this?

2018-05-23 13:17 UTC, martin-cs commented on scripts/minisat64.patch
> ++    static_assert(2 * sizeof(Lit) == sizeof(CRef), "CRef is 2*Lit");
This concerns me; do we have any performance data on the effects of this?

2021-03-12 10:53 UTC, NlightNFotis commented
Hi @tautschnig, this looks useful! Could we have it rebased on top of `develop` please?

2021-04-30 17:04 UTC, thomasspriggs commented
This may be something of a tangent to the subject of the review of this PR. However I think it is worth considering whether a set of patches like this is a good way of maintaining our variation of MiniSat; given that git a commit essentially is a patch. So if we could keep the patches as commits we would have better/standardised tools for maintaining version history and resolving any merge conflicts which occur.

2021-05-26 10:44 UTC, martin-cs commented
@thomasspriggs having Minisat as a git submodule with patches would also remove the download-during-build gotcha.

2022-11-08 12:33 UTC, tautschnig commented
Closing as it would not be right for us to carry such a patch. Could be upstreamed to [conp/merg](https://github.com/conp-solutions/mergesat) instead.

2022-11-08 12:33 UTC, closed without merging