[SEC-346] irep_ids: Adding in a NULL-object ID
diffblue/cbmc pull request #2048
Opened 2018-04-12 12:20 UTC by JohnDumbell

Originally I changed the existing null_object to an IREP_ID_TWO with the correct string in it, but then that would trip up anybody using "null_object" as a literal elsewhere, so for now reverted to having two identities instead.

Would you prefer me to change the existing null_object, leave it as-is in the current commit, or some other alternative?

2018-04-12 12:31 UTC, tautschnig requested changes
Thank you for raising this! I'm not sure what triggered your work on this - is there possibly a regression test that could be added? So why am I nevertheless requesting changes: I believe that all uses of "NULL-object" ought be replaced by the existing `ID_null_object`. Maybe @kroening can chime in as well?

2018-04-12 12:46 UTC, JohnDumbell commented
It was just triggered by general cleanup - we were going to use the ID, noticed literals were being used and looked into adding it as an ID. I could write a quick test to enforce that the new (or old) irep_id == the old string literal though and maybe test one of the changed paths.

2018-04-12 12:50 UTC, tautschnig commented
If you've got a use case for the ID then I think the absence of a new test is fine: the existing tests should guard against regressions anyway.

2018-04-12 13:38 UTC, smowton commented
My only concern was perhaps some external tool parsing the string "NULL-object"; if you think that's unlikely shall we merge the two similar IDs?

2018-04-12 13:54 UTC, tautschnig commented
If it's made an `IREP_ID_TWO` with "NULL-object" as the string representation then we should be fine (the only risk would be anyone using "null_object", but I don't think that's happening for anyone).

2018-04-13 12:18 UTC, JohnDumbell commented
I've made the changes, but during a double-check I found another string which might be a target for changing, but I'm a lot less sure about this one. I've added the change in the second commit, if that should also be changed I'll merge it into the original commit, otherwise revert.

2018-04-13 12:35 UTC, tautschnig approved these changes

2018-04-13 12:35 UTC, tautschnig commented on src/goto-programs/interpreter.cpp
> +  inverse_memory_map[0]=ID_null_object;
I think this change is fine. Strings used exactly once in the code base are very suspicious and should likely all be fixed.

2018-04-13 12:35 UTC, tautschnig commented on src/analyses/ai.cpp
> +  else if(function.id()==ID_null_object)
Nit pick (here and almost everywhere else in this PR): the clang-format Travis job has some suggestions to introduce whitespace around `==`. I'd follow that, but that's nit picking obviously.

2018-04-13 14:47 UTC, JohnDumbell commented
Squashed commits and fixed the formatting.

2018-04-13 14:49 UTC, owen-mc-diffblue approved these changes

2018-04-16 12:42 UTC, kroening approved these changes

2018-04-16 12:42 UTC, merged