Get legalistic about use of virtual with override
diffblue/cbmc pull request #2055
Opened 2018-04-13 16:30 UTC by NathanJPhillips

I recently had a comment on a PR complaining that I used the redundant `virtual` on a method declaration that I marked `override`.
I replied that the redundant virtual is useful documentation as it allows developers to see whether a function is virtual in a single place without having to check the beginning and the end of the declaration.
Another reviewer pointed out that our linter was specifically adjusted to allow this format here: https://github.com/diffblue/cbmc/commit/a7c24fb631d7ca017f4fad00320b6270ddc4f4c8#diff-4abdbb2a75f622bb69ca7ae19beee7c6R5647.
An analysis of the code base for CBMC shows that we have 457 uses of `override`, of which 154 combine it with `virtual`. Deeptest has a similar proportion with 22 of 64 uses using the combined version.
My hope with this PR is that it will ignite a style war that will get nowhere and result in this PR being closed. This will then be the definitive point of reference for allowing people to do whatever they feel most comfortable with.

2018-04-13 17:04 UTC, tautschnig commented
From my point of view you might as well flip a coin, but I'm a strong proponent of consistency: always use `virtual` with `override` or never do so.

2018-04-16 14:02 UTC, chrisr-diffblue approved these changes
I'm going to nail my colours to the mast...

2018-04-16 14:03 UTC, chrisr-diffblue commented
...but I'm not brave enough to merge it, so someone else can do that :-)

2018-04-16 14:38 UTC, hannes-steffenhagen-diffblue commented
My preference would be to not add the redundant override. Both the default cpplint and clang-tidy's `modernize-use-override` warn against this. Although I certainly agree if we're going to do it one way or the other we should be specific about this.

My argument against the consistency argument would be that if you're only going to check the prefix of the function for the behaviour you could also read an override as introducing a new virtual function instead. Also, you should always check the postfix anyway for `const`ness specifiers.

2018-04-16 16:11 UTC, smowton approved these changes
Yeah, it's a little clearer. Though an en-masse cleanup should also be submitted in this case.

2018-04-19 09:18 UTC, peterschrammel reviewed
Technically, neither `virtual` nor `override` are required. Using `virtual` to visually mark overridden functions is a relict from pre-C++11 times. 
I agree with @hannes-steffenhagen-diffblue that the fact that clang-tidy offers an option to clean up joint use of `virtual` and `override` is a strong argument for getting rid of the remaining redundancies in our code bases.

2018-04-26 14:41 UTC, kroening commented
So, are we doing override without virtual?

2018-04-26 15:33 UTC, NathanJPhillips commented
I think we have three votes for including virtual and two against. Is @kroening against? Then we can have an exact tie and do nothing.

2018-05-20 20:04 UTC, kroening commented
Hm, the Google C++ coding style (which we frequently follow) says use override but no virtual.

2018-05-21 16:34 UTC, martin-cs commented
@NathanJPhillips If you're intent on starting a war over this I can offer to supply one (or both) sides with ammunition at very reasonable prices...

I think I'm with the "does it really matter" faction, or possibly the "add it to the linter and let it change naturally" group,

2018-05-25 11:22 UTC, kroening requested changes
We'll go for 'no virtual', and it will be a linter recommendation.

2018-05-29 15:01 UTC, peterschrammel commented
https://github.com/diffblue/cbmc/pull/2253 clarifies the rule in the coding standard and enables the corresponding check in cpplint.

2018-05-29 15:01 UTC, closed without merging