Use adjust_float_expression in simplify
diffblue/cbmc pull request #2076
Opened 2018-04-16 16:43 UTC by hannes-steffenhagen-diffblue

This lets the simplifier rewrite generic arithmetic operations to their floating point equivalents, which can simplify floating point expressions respecting rounding mode.

2018-04-16 16:50 UTC, hannes-steffenhagen-diffblue commented
@martin-cs This has the floating point changes we were talking about last week. Can you please check if this is in line with what you were thinking? This doesn't have any goto-analyzer specific things in it (like trying to use different rounding modes), but I believe this is an independent step we can use as a starting point.

2018-04-16 17:16 UTC, tautschnig requested changes
There are a few smaller issues, but mainly I'm concerned about the use of the initial value as found in the symbol table. This value, if still in line with a program's semantics, should be forwarded via constant propagation.

2018-04-16 17:16 UTC, tautschnig commented on src/util/adjust_float_expressions.cpp
> +  goto_functionst::goto_functiont &goto_function,
This file will need to be split up, those functions can't live in `util/` as they have dependencies on `goto-programs`.

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +    if(expr.type().id() == ID_floatbv)
Please add braces here.

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +    if(expr.type().id() == ID_floatbv)
Braces, please.

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +    if(expr.type().id() == ID_floatbv)
Braces, please.

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +    if(expr.type().id() == ID_floatbv)
Braces, please.

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +      result = simplify_rec(expr);
Missing `&& result` (the same in all the other edits below)

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +      result = simplify_div(expr) && result;
Why not move the `if(expr.type().id() == ID_floatbv)` inside `simplify_div` etc?

2018-04-16 17:16 UTC, tautschnig commented on src/util/simplify_expr_floatbv.cpp
> +      attached_rounding_mode = p_rounding_sym->value;
How is using the initial value justified? It may, after all, change during program execution?

2018-04-17 09:17 UTC, hannes-steffenhagen-diffblue commented on src/util/simplify_expr_floatbv.cpp
> +      attached_rounding_mode = p_rounding_sym->value;
That was just me misunderstanding how `namespacet` is used, this indeed seems to be the wrong thing to do here.

I was thinking I could somehow do symbol evaluation in `simplify_expr`, but it seems that this will have to be done outside of it.

2018-04-17 09:56 UTC, hannes-steffenhagen-diffblue commented
Closing for now as per Michaels comments this seems like the wrong approach to take. I'll try moving `adjust_float_expressions` into `goto-models` instead, and do the call in `goto-analyzer` (the whole point of this is to improve the handling of floats by goto-analayzer)

2018-04-17 09:56 UTC, closed without merging