Move java new side-effect removal into separate pass
diffblue/cbmc pull request #2116
Opened 2018-04-25 20:58 UTC by peterschrammel

removes java-specifc code from goto_convertt

2018-04-25 21:26 UTC, tautschnig requested changes

2018-04-25 21:26 UTC, tautschnig commented on src/goto-programs/goto_convert.cpp
> -
I believe this is not preserved properly, and that's making the tests fail.

2018-04-25 21:26 UTC, tautschnig commented on src/goto-programs/goto_convert.cpp
> -    (rhs.get(ID_statement) == ID_allocate ||
I don't think the `ID_allocate` case is preserved?

2018-04-26 08:06 UTC, smowton approved these changes
Note this definitely needs concurrent test-gen change (@thk123)

2018-04-26 08:07 UTC, smowton commented
Scratch that; https://github.com/diffblue/test-gen/pull/1757

2018-04-26 08:17 UTC, peterschrammel commented
There's still a unit test failure that I have to fix.

2018-04-26 15:54 UTC, peterschrammel commented
@tautschnig, CI is passing, please re-review.

2018-04-26 16:31 UTC, tautschnig approved these changes

2018-04-26 19:46 UTC, merged