remove the --fixedbv command-line option
diffblue/cbmc pull request #2148
Opened 2018-05-03 17:52 UTC by kroening

The option was marked deprecated in January 2017. A similar effect can be achieved with #define float/double __CPROVER_fixedbv[].

2018-05-03 18:29 UTC, tautschnig requested changes
1) The fixedbv tests need to be removed.
2) Please add a note in the changelog.

2018-05-04 15:05 UTC, kroening commented
The fixedbv tests got fixed! (One of them needs new features, though).

2018-05-04 15:37 UTC, tautschnig reviewed
A request for explanation and the still outstanding request for an entry in the changelog file, please.

2018-05-04 15:37 UTC, tautschnig commented on regression/cbmc/Fixedbv7/test.desc
> +KNOWNBUG
Please add a comment at the end of the file describing what is going wrong here. And likely also create an issue.

2018-05-07 09:42 UTC, kroening commented
both done

2018-05-07 10:14 UTC, tautschnig approved these changes
Thanks a lot for the cleanup and all the updates!

2018-05-07 10:14 UTC, tautschnig commented on regression/cbmc/Fixedbv7/test.desc
> +numbers is required in solvers/flattening/boolbv_typecast.cpp. Issue #2158.
Nit pick: GitHub says there is no newline at end-of-file.

2018-05-07 17:49 UTC, merged