Use get_identifier() instead of get(ID_identifier) on symbols
diffblue/cbmc pull request #2206
Opened 2018-05-19 11:11 UTC by kroening

2018-05-19 13:01 UTC, tautschnig commented
The changes are probably good, but it's really hard to review: The commit messages and the actual changes seem largely unrelated, and few of the latter actually relate to the subject of this pull request.

2018-05-25 06:48 UTC, peterschrammel approved these changes

2018-05-25 06:48 UTC, peterschrammel commented on src/util/std_types.h
> +/*! \brief Cast a generic typet to a \ref tag_typet
We should converge towards using `/// comments` for doxygen.

2018-05-29 11:02 UTC, tautschnig requested changes
Echoing what I've said before as it got assigned to me: "The commit messages and the actual changes seem largely unrelated, and few of the latter actually relate to the subject of this pull request."

2018-05-30 18:18 UTC, kroening commented
This should now be straight-forward to review.

2018-06-01 10:25 UTC, tautschnig approved these changes

2018-06-01 15:54 UTC, merged