Add global null message handler
diffblue/cbmc pull request #2233
Opened 2018-05-23 17:01 UTC by thomasspriggs

The typical use case for `null_message_handlert` is to create an instance of it and then pass it into a method/function, where output messages are intended to be discarded. This PR creates a single global instance of the class, to save creating a new instance of it, each time it is used.

2018-05-23 17:31 UTC, tautschnig requested changes
This PR is a good ground for discussion, I'd say:
1) Using the `null_message_handlert` in unit tests makes, IMHO, perfect sense. Declaring a global one for everyone in some unit-test helper seems like a good idea.
2) Many other cases should never have used `null_message_handlert` in the first place. Indicated in detailed comments below.
3) I think this leaves a single valid use case left that isn't within unit tests. I would then argue against introducing a single, static object just for this one...

2018-05-23 17:31 UTC, tautschnig commented on jbmc/src/java_bytecode/java_object_factory.cpp
> +        struct_type, source_locationt(), ns, null_message_handler);
This code should likely use the exception-throwing variant of `zero_initializer` as the value isn't even sanity-checked afterwards. (And that variant would not require a message handler.)

2018-05-23 17:31 UTC, tautschnig commented on jbmc/unit/java-testing-utils/load_java_class.cpp
> +    null_message_handler);
I'd suggest to declare the null-message-handler once for all unit tests, because indeed it makes sense to silence output in unit tests.

2018-05-23 17:31 UTC, tautschnig commented on src/cbmc/xml_interface.cpp
> +    parse_xml(std::cin, "", null_message_handler, xml);
Discarding error messages here never was a good idea and should be fixed.

2018-05-23 17:31 UTC, tautschnig commented on src/langapi/language_util.cpp
> -  null_message_handlert null_message_handler;
I don't think discarding messages ever was a good idea here.

2018-05-23 17:31 UTC, tautschnig commented on src/xmllang/graphml.cpp
> +  if(parse_xml(is, "", null_message_handler, xml))
This is probably my code ... discarding error messages never was a good idea.

2018-05-23 17:31 UTC, tautschnig commented on src/xmllang/graphml.cpp
> +  if(parse_xml(filename, null_message_handler, xml))
... or here.

2018-05-23 17:31 UTC, tautschnig commented on src/goto-symex/symex_builtin_functions.cpp
> -        null_message);
This should use the throwing version, because really it actually throws below ...

2018-05-24 14:33 UTC, thomasspriggs commented
@tautschnig I came up with the idea for this PR whilst working on unit tests. I am willing to rework this PR, so that it only applies to the unit tests. However I don't want to get side tracked into making deeper changes elsewhere in the code base. Would you be willing to approve this PR if it applied only to unit tests?

2018-05-24 14:38 UTC, tautschnig commented
> Would you be willing to approve this PR if it applied only to unit tests?

I certainly would!

2018-05-24 15:59 UTC, thomasspriggs commented
@tautschnig I have performed the update discussed.

2018-05-29 12:06 UTC, tautschnig approved these changes

2018-05-29 12:06 UTC, tautschnig commented on unit/testing-utils/message.h
> +null_message_handlert extern null_message_handler;
Nit pick: elsewhere in the code we place the storage class at the front.

2018-06-04 16:04 UTC, thk123 approved these changes
Please fix the nit from @tautschnig then will merge.

2018-06-05 16:05 UTC, thomasspriggs commented
@thk123 I have fixed the nit and Travis has passed.

2018-06-05 16:15 UTC, merged