Test to trigger CI on private repository [DO NOT MERGE]
diffblue/cbmc pull request #2266
Opened 2018-06-01 08:10 UTC by romainbrenguier

2018-06-07 12:48 UTC, allredj requested changes
This PR failed Diffblue compatibility checks.
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

2018-06-07 13:06 UTC, allredj approved these changes
Passed Diffblue compatibility checks.

2018-06-07 13:38 UTC, allredj requested changes
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 14:28 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 14:44 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 15:01 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 15:08 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 16:31 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 16:35 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 16:41 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 17:24 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-07 17:30 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 17:49 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 17:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 17:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 19:31 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 19:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 20:24 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 20:48 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 20:58 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 21:02 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 21:42 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 22:40 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-07 23:00 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 07:29 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 08:29 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 09:09 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 10:57 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 11:35 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 11:50 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 12:17 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 12:24 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 13:52 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 14:02 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 14:40 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 15:40 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 15:58 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 16:02 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 16:23 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 17:06 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 17:23 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 17:31 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 17:36 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 17:51 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 18:09 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 18:12 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 18:15 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 18:22 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 18:40 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-08 19:46 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-08 19:48 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 00:41 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 00:45 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 08:57 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 09:54 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 09:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 10:35 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 11:45 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 11:56 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 12:24 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 14:16 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 16:13 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 16:15 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 16:38 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 16:44 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 17:16 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 18:12 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 20:28 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 22:05 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-09 22:33 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 16:07 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 16:46 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 18:16 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 20:00 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 22:42 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-10 23:31 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 09:06 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-11 13:24 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 14:30 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 14:57 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 15:45 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 15:59 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 16:08 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 16:10 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 17:46 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 17:56 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 18:04 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 18:17 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 18:27 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 18:34 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 18:54 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-11 23:16 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 06:01 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 08:13 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 08:30 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 08:35 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 08:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 09:54 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 09:54 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 10:13 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-12 11:40 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:42 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:45 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:49 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:52 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:57 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 11:59 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 12:07 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 13:39 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 13:48 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 14:52 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 14:58 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 15:14 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 15:16 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 16:19 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 17:42 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 18:52 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 19:20 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 19:41 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 21:01 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-12 22:31 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 00:38 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 01:11 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 08:59 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 09:33 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 09:41 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 10:30 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 11:17 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).
Status will be re-evaluated on next push.
Please contact peterschrammel, thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-06-13 11:42 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-13 11:46 UTC, tautschnig commented
@allredj Is this still work in progress?

2018-06-13 11:57 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: f1e81e2a2e587608de94ccb9d73f0e7fa71cfe9f).

2018-06-13 12:01 UTC, allredj commented
@tautschnig yes, but I think I've solved most of the remaining issues. I'm attempting to deploy now. You should get notified on your future PRs.

2018-06-13 12:07 UTC, tautschnig commented
@allredj Ok, thanks, I was just wondering as this PR kept sending the same notifications.

2018-06-14 10:32 UTC, closed without merging