Make sure code_typet always has parameters property
diffblue/cbmc pull request #2269
Opened 2018-06-01 16:31 UTC by peterschrammel

The existence of the parameters property may depend on
whether parameters() has been called or not, which can
lead to unexpectedly unequal instructions in goto programs.

A regression test is coming.

2018-06-01 17:13 UTC, tautschnig approved these changes
Just a procedural suggestion: split this in two commits, with the first one doing the changes to std_types.h and the second one being a clean revert of 0b3170d425.

2018-06-02 07:18 UTC, kroening commented
I would then do the same with return_type().
Also, I'd mark the () constructor as deprecated, as this is another case of "problem caused by partially-constructed object".

2018-06-02 07:19 UTC, kroening requested changes
do same with return_type, and make () constructor deprecated.

2018-06-04 08:25 UTC, smowton approved these changes
As per @tautschnig, once @kroening's reservations are addressed

2018-06-04 22:08 UTC, peterschrammel commented
@kroening, I've introduced new constructors, deprecated the old one and cleaned up its occurrences.

2018-06-05 12:15 UTC, kroening commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
Note that we've got java_lang_object_type()

2018-06-05 12:24 UTC, tautschnig commented
Not there isn't enough work in here already, but "Use the two-param code_typet constructor" would now also enable a lot of use of `const` for almost all of the `code_typet` objects being declared.

2018-06-05 12:26 UTC, kroening commented
Note that this also tweaks the remove_returns behavior, which may not have been intended.

2018-06-05 12:27 UTC, kroening approved these changes

2018-06-05 12:33 UTC, tautschnig commented
> Note that this also tweaks the remove_returns behavior, which may not have been intended.

In what way is that impacted here?

2018-06-05 20:15 UTC, peterschrammel commented
> Note that this also tweaks the remove_returns behavior, which may not have been intended.

I deliberately changed that because silently ignoring the failure and returning a nil-irept through a code_typet (!) didn't seem appropriate to me. That case can only occur when the symbol table is out-of-sync with the goto-program, which is clearly a programming error elsewhere.
Since this is changing behaviour, I will put that change into a separate commit.

2018-06-05 20:58 UTC, peterschrammel commented
I revise my statement above. The code is actually used in cbmc/symex_coverage. However, I think that the call there can be simplified if `original_return_type` behaved slightly differently. @tautschnig, please check b29b043 whether this follows your intentions.

2018-06-06 07:30 UTC, tautschnig commented
> please check b29b043 whether this follows your intentions.

This looks good to me, and certainly improves the clarity of the code.

2018-06-06 08:56 UTC, chrisr-diffblue approved these changes
Looks OK to me.

2018-06-06 10:21 UTC, merged

2018-06-06 10:42 UTC, tautschnig commented
I don't think this should have been merged just yet. I have created #2287 to track this.