Unstall AppVeyor by checking for the correct file path
diffblue/cbmc pull request #2283
Opened 2018-06-05 18:26 UTC by tautschnig

AppVeyor found files existed already:

Extracting archive: jml.zip
--
Path = jml.zip
Type = zip
Physical Size = 89524
Comment = f8c2338ab30278f951c542c7049a0b591689679f
Would you like to replace the existing file:
  Path:     .\java-models-library-master\.gitignore
  Size:     36 bytes (1 KiB)
  Modified: 2018-06-04 10:53:06
with the file from archive:
  Path:     java-models-library-master\.gitignore
  Size:     36 bytes (1 KiB)
  Modified: 2018-06-04 10:53:06

2018-06-05 20:45 UTC, Degiorgio approved these changes

2018-06-05 20:57 UTC, Degiorgio requested changes
@tautschnig should it be  
`.\java-models-library-master\.gitignore`   
as AppVeyor is still not passing :(

2018-06-05 21:05 UTC, peterschrammel reviewed
I've cancelled all appveyor builds that blocked the queue. The build is running now.

2018-06-05 21:46 UTC, peterschrammel approved these changes
Passes now

2018-06-05 21:54 UTC, merged

2018-06-06 07:26 UTC, tautschnig commented
@Degiorgio as the AppVeyor builds are passing that seems to be ok as-is. Yet I am wondering whether the overall behaviour is really what you want for 1) updates to the Java models library don't propagate in a deterministic fashion and 2) the version of the Java models library being used may differ across runs in a non-predictable fashion.

2018-06-06 08:44 UTC, Degiorgio commented
@tautschnig, yes currently this is not an ideal situation, but due to possible licensing  issues (which we are still trying to resolve) it's what we can do. The ideal situation would be a submodule approach.

2018-06-06 09:01 UTC, tautschnig commented
@Degiorgio I think there is an partial solution by creating a tag or branch in the Java models repository and referring to that instead of master. Moving to an updated version would then require an update of the appveyor file here, but at least you would have a fully deterministic solution.

2018-06-06 12:47 UTC, Degiorgio commented
@tautschnig  that solution is better. Will do a PR later. Thx!