Revert undocumented change of 27153d142e
diffblue/cbmc pull request #2316
Opened 2018-06-08 17:23 UTC by tautschnig

While the functional behaviour is identical, there is a ~10% performance penalty
during symbolic execution when using the non-optimised version.

2018-06-08 17:34 UTC, smowton requested changes
Blocking for now as afaik the optimised version is broken with respect to Java identifiers. I had a PR to do this both cleanly and quickly that never got anywhere IIRC, I will dig it out on Monday...

2018-06-08 18:40 UTC, tautschnig commented
@smowton Are you sure a change beyond what you fixed in d9026ae79e5f9 is required?

2018-06-10 08:01 UTC, smowton approved these changes
Aha, that change is indeed the fix I expected. Looks like I flipped the `#if` at that time, then it was flipped back, perhaps by accident, in https://github.com/diffblue/cbmc/commit/27153d142eb07dc0e78eb47d72e52b877af5d776. If @peterschrammel can confirm there was no particular motive for the second flip then this is fine.

2018-06-10 10:00 UTC, merged

2018-06-10 12:35 UTC, peterschrammel commented
Since there is no comment in the code or commit message why it was changed in 27153d1, we can only assume that it was accidental.