boolbvt error handling for byte_extract
diffblue/cbmc pull request #2501
Opened 2018-07-01 11:52 UTC by kroening

boolbvt does not throw exceptions in case unsupported expressions are given; instead, it calls conversion_failed, which calls ignoring().

2018-07-01 12:25 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 83017431c979d2640e4a899c8ce64b8f70e430ef).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/77795181

2018-07-02 16:39 UTC, tautschnig commented
I'll take a look and provide comments on this: it should be co-ordinated with existing open issues on cleaning up exceptions and also the refactoring of `flatten_byte_extract`.

2018-11-07 16:54 UTC, tautschnig commented
In light of #3290 merged, this needs to be reconsidered and at bare minimum rebased.

2018-11-07 21:29 UTC, martin-cs approved these changes
OK but I agree with @tautschnig 's comments about whether this is the thing to do.

2018-11-08 14:42 UTC, allredj reviewed
:warning:
Diffblue compatibility check is currently unavailable.
Please create manual bump.
(cbmc commit: 56194efc65815c17c7ce2a5426e83bf88034ff9a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90716260

2019-03-03 21:36 UTC, tautschnig requested changes
Now that we've merged the various byte extract/byte update fixes: this seems like the right thing to do, except it's actually needed in more places: https://github.com/tautschnig/cbmc/commit/deaa887dffaefc0d190360c8b27fd7778aa70c72 might provide guidance.

2019-05-19 20:09 UTC, tautschnig commented
I'm of course biased, but I'd by now actually prefer #4651 (plus a follow-up PR that replaces the two remaining two throws by invariants).

2019-05-22 14:02 UTC, tautschnig commented
I've not put up #4691, which ought to make this one unnecessary.

2019-05-30 11:55 UTC, tautschnig commented
Closing as this is no longer applicable with #4691 merged.

2019-05-30 11:55 UTC, closed without merging