added support for _int64 keyword
diffblue/cbmc pull request #2608
Opened 2018-07-24 17:34 UTC by kroening

Visual Studio understands _int64 in addition to __int64. I tried _int32, etc., but these don't seem to exist.

2018-07-24 18:14 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: cb39363bcf53b5424439c169029105c410238c09).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/79886035

2018-07-25 21:03 UTC, peterschrammel commented
"For backward compatibility, single-underscore versions of the rest of the keywords are supported." (https://msdn.microsoft.com/en-us/library/befeaky0.aspx) would indicate that there are a lot more of that sort...

2018-07-25 21:04 UTC, peterschrammel approved these changes

2018-07-29 18:49 UTC, tautschnig requested changes
The change looks good, but requires a regression test, possibly extending `regression/ansi-c/VS_extensions1/main.c`.

2018-07-30 07:20 UTC, kroening commented
Done

2018-07-30 11:34 UTC, tautschnig approved these changes

2018-07-30 11:35 UTC, tautschnig commented
Ok from my point of view, but I have no idea what the CodeBuild failure is about. (I have restarted the failing Travis tasks.)

2018-07-30 11:52 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: cbfcc5c5d3616206c4600f6bf83973660b9c4897).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80357896

2018-07-30 17:59 UTC, kroening commented
The CodeBuild failure is caused by a failing Ubuntu server. These could be avoided using a custom image.

2018-07-30 17:59 UTC, merged