Improvements to code contracts
diffblue/cbmc pull request #2677
Opened 2018-08-03 14:12 UTC by qaphla

This provides a few changes which together serve to improve the havocking of variables when dealing with function calls (as well as a patch [02eb459] which doesn't really seem to fit anywhere else).

63b2af3 fixes a soundness issue with contract application by havocking the variables which could be touched by the function call being abstracted out.
2ec8f88 resolves an issue wherein function contracts were checked before initializing the dead and deallocated objects, and so any check that a pointer was not dead or deallocated would fail.
c3fcb36 switches contracts from using the local_may_alias analysis to the goto_rw analysis for finding the write sets of functions or loops.
f0fc9d3 improves the documentation of the contracts feature.

This builds on https://github.com/diffblue/cbmc/pull/2646 because the changes in c3fcb36 benefit greatly from a less conservative approximation in goto_rw.

2018-08-03 18:29 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 522c765291533358fa274cd272881fa2fbaa21c4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/80904637
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).
##

2018-08-04 16:26 UTC, kroening requested changes

2018-08-04 16:26 UTC, kroening commented on .gitignore
Is this not redundant with the above?

2018-08-04 16:26 UTC, kroening commented on src/analyses/dependence_graph.cpp
>      }
The change to this file appears unrelated.

2018-08-04 16:26 UTC, kroening commented on src/analyses/goto_rw.cpp
>       object.id() == ID_label ||
The ID_symbol case overrides the case below.

2018-08-04 16:26 UTC, kroening commented on src/ansi-c/c_typecheck_expr.cpp
>      dynamic_object_expr.operands()=expr.arguments();
Use is_dynamic_object_exprt, which you are adding.

2018-08-04 16:26 UTC, kroening commented
Given that new syntax is proposed here, did you consider ACSL?
https://github.com/acsl-language/acsl

2018-08-06 14:16 UTC, martin-cs reviewed
Although I appreciate it is a pain, could we get the supporting PRs merged first and then look at this?  I'm also very much with @kroening on the idea of annotation languages : the world may need another annotation language for C but it won't be one that is a partial subset of the features of an existing one.  Interoperability is good and being able to compare wih / share benchmarks with tools like Frama-C would be great.

2023-05-03 15:22 UTC, TGWDB commented
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

2023-05-03 15:22 UTC, closed without merging