Add support for getting components by name to `struct_exprt`
diffblue/cbmc pull request #2710
Opened 2018-08-10 11:13 UTC by thomasspriggs

Add support for getting components by name to `struct_exprt`

2018-08-10 11:23 UTC, tautschnig requested changes
Good idea, but more defensiveness required as outlined below.

2018-08-10 11:23 UTC, tautschnig commented on src/util/std_expr.h
> +    return operands()[to_struct_type(type()).component_number(name)];
Please do
````c++
const auto index = to_struct_type(type()).component_number(name);
DATA_INVARIANT(index < operands().size(), "component matching index should exist");
return operands()[index];
````

2018-08-10 11:23 UTC, tautschnig commented on src/util/std_expr.h
> +  exprt &component(const irep_idt name)
Pass as a reference

2018-08-10 12:18 UTC, thomasspriggs commented on src/util/std_expr.h
> +    return operands()[to_struct_type(type()).component_number(name)];
Done.

2018-08-10 12:18 UTC, thomasspriggs commented on src/util/std_expr.h
> +  exprt &component(const irep_idt name)
Done.

2018-08-10 12:28 UTC, tautschnig approved these changes
Thanks a lot for the immediate updates, I'd suggest squashing before the merge.

2018-08-10 12:30 UTC, thomasspriggs commented
@tautschnig Will do. My responses to comments are in separate commits for convenience of reviewing only.

2018-08-10 12:33 UTC, thk123 approved these changes

2018-08-10 12:41 UTC, tautschnig commented
> My responses to comments are in separate commits for convenience of reviewing only.

Yes, thank you, I should have explicitly ack'ed that. My note was mainly aimed at anyone else overly eager to merge this, which I hadn't quite made clear.

2018-08-10 15:06 UTC, kroening requested changes
This won't work.
We don't want the struct_type to be the type of the struct_expr (which can be huge, esp. in OO languages), but we want the struct_tag type (which is constant size).
Thus, I recommend passing a namespace, and then using .follow() to get the struct_type.

2018-08-13 15:02 UTC, thomasspriggs commented
@kroening I have added a commit which uses `ns.follow` in order to address your comment. Please can you re-review?

I have also added a commit which uses a template to de-duplicate the const and non-const overloads of `struct_exprt::component`, as there was slightly more code duplication than I was happy with. However if there is a view that the duplication is better than adding template usage, I am ok with dropping the extra commit.

My intention is to squash all the commits together before this PR is merged. The commits are currently separate for ease of reviewing.

2018-08-14 16:31 UTC, kroening approved these changes

2018-08-14 16:32 UTC, kroening commented
A rebase should fix the problem with AWS CodeBuild.

2018-08-15 11:36 UTC, merged