do not attempt to havoc void-typed objects; fixes issue #2663
diffblue/cbmc pull request #2735
Opened 2018-08-14 22:12 UTC by kroening

2018-08-15 05:20 UTC, tautschnig requested changes
See below; also lacks tests and I am not sure the commit message would make GitHub automatically close the issue.

2018-08-15 05:20 UTC, tautschnig commented on src/goto-programs/generate_function_bodies.cpp
> +        parameter.type().subtype().id() != ID_empty)
I think this should instead fall back to `char`, doing whatever would happen if the parameter were of type `char*`. Leaving the pointed-to object unmodified may fail to meet the user's expectations.

2018-08-15 08:42 UTC, kroening commented on src/goto-programs/generate_function_bodies.cpp
> +        parameter.type().subtype().id() != ID_empty)
I'd say that the user's expectation will be that the entire object that the 'void *' points to gets havoc'ed. 'char' seems arbitrary.

2018-08-15 09:02 UTC, tautschnig commented on src/goto-programs/generate_function_bodies.cpp
> +        parameter.type().subtype().id() != ID_empty)
So should we just refuse to generate code? Most cases using `void *` as parameter type will accept more than a single object type (e.g., arrays of varying length).

2018-08-22 09:00 UTC, tautschnig commented
After some further discussion with @polgreen: in the same way that void pointers are skipped, so should be function pointers.

2018-08-22 09:07 UTC, kroening commented
Indeed, done.

2018-09-21 23:44 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: d02cf3044fb9b10209ad1d7ca2e1e6e5d2622683).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85620044

2021-03-12 10:32 UTC, NlightNFotis commented
Hi @kroening, is this PR still relevant? If yes, can we get it rebased on `develop`? If not, can we get it closed?

2023-05-03 15:27 UTC, TGWDB commented
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

2023-05-03 15:27 UTC, closed without merging