need to check lower bound on index in rw_range_sett::get_objects_byte_extract
diffblue/cbmc pull request #2822
Opened 2018-08-22 16:11 UTC by kroening

This addresses part of issue #2653

2018-08-22 16:27 UTC, peterschrammel commented
This seems related to https://github.com/diffblue/cbmc/issues/2524.

2018-08-23 06:38 UTC, kroening commented
Ok, let's see whether that can do a KNOWNBUG -> CORE.

2018-08-23 07:41 UTC, tautschnig requested changes

2018-08-23 07:41 UTC, tautschnig commented on src/analyses/goto_rw.cpp
> +       index>=pointer_offset_bits(be.op().type(), ns))
I'm afraid this code has more flaws (yes, my fault): the offset must be computed relative to the root object, which may or may not be the same as `be.op()`. Consider the case of a byte_extract within a struct member (and the test that's now supposedly fixed is exactly of that nature).

2021-03-12 10:45 UTC, NlightNFotis commented
Hi @kroening, is it possible that you address the issues that Michael raised?

If not, shall we have this closed please?

2022-02-15 21:24 UTC, tautschnig approved these changes

2022-02-26 11:06 UTC, chris-ryder approved these changes

2022-02-26 17:11 UTC, merged