Fix --string-non-empty option
diffblue/cbmc pull request #2909
Opened 2018-09-06 12:18 UTC by romainbrenguier

This was broken and the option had no effect

2018-09-06 12:38 UTC, tautschnig requested changes
Let's please stop doing any command-line option parsing in the language front-end. Undocumented command-line options are a no-go.

2018-09-06 12:38 UTC, tautschnig commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +    object_factory_parameters.min_nondet_string_length = 1;
Can we please not have more command-line parsing in the language front-end? See
#2907 and #2908. Let alone doing so via an undocumented option?

2018-09-10 16:36 UTC, thk123 commented on jbmc/src/java_bytecode/object_factory_parameters.h
> +  /// Maximum value for the non-deterministically-chosen length of a string.
:no_entry_sign: :pick: Typo: `Minimum`

2018-10-02 08:31 UTC, romainbrenguier commented
@thk123 @tautschnig this is ready for review

2018-10-02 09:09 UTC, thk123 reviewed
Test is missing one assertion status - please add. Also, any reason to have a binary flag rather than just a `min-string-length` option?

2018-10-02 09:09 UTC, thk123 commented on jbmc/regression/jbmc-strings/string-non-empty-option/test_non_empty.desc
> +assertion.* line 11 function java::Test.checkMinLength.*: SUCCESS
:no_entry_sign: This `desc` file is missing the line 17 assertion

2018-10-02 09:20 UTC, tautschnig approved these changes
Ok from my point of view, except the *.desc files as noted below. The where-to-parse-command-line-options is postponed.

2018-10-02 09:20 UTC, tautschnig commented on jbmc/regression/jbmc-strings/string-non-empty-option/test.desc
> +
No blank lines here please, it confuses test runs on Windows. The same applies to the other *.desc files in this commit.

2018-10-02 09:20 UTC, tautschnig commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +    object_factory_parameters.min_nondet_string_length = 1;
While I remain unhappy it seems that #2908 is not currently progressing so I won't further block on this.

2018-10-02 09:23 UTC, romainbrenguier commented
@thk123 
> Also, any reason to have a binary flag rather than just a min-string-length option?

No particular reason, I'm just fixing the previously existing feature that was broken, but it could be replaced by a min-string-length option in the future.

2018-10-02 09:43 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 0e36b4df0a9fb1376ea5689ab976a3af50d41d6b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86575976
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-10-02 09:44 UTC, thk123 approved these changes

2018-10-02 10:04 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 2d7e636b5efb991d7827a8479d030d7e2d85b89d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86578648
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-10-02 10:15 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 72350c2b5e131494d2c925a88b45921ae271d8a1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86579860
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-10-02 10:23 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: cf123f06e879cc14ef87414a67c6308cf2f00a8c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86580449

2018-10-02 11:07 UTC, peterschrammel approved these changes

2018-10-02 12:47 UTC, merged