Add brief documentation of overlay classes
diffblue/cbmc pull request #2947
Opened 2018-09-13 14:19 UTC by owen-jones-diffblue

It could be expanded in future, but it's better than what was there
before

2018-09-13 14:32 UTC, NathanJPhillips approved these changes

2018-09-13 15:13 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 25fb9befb2b2875816effbb623f62e592b80a994).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84714306

2018-09-13 20:26 UTC, antlechner approved these changes

2018-09-13 20:26 UTC, antlechner commented on jbmc/src/java_bytecode/java_class_loader.cpp
> +/// \@OverlayClassImplementation. They serve the following purpose. When the JVM
There should also be some documentation for the other two annotations (`IgnoredMethodImplementation` and `OverlayMethodImplementation`). Could you add a `TODO` for these here or wherever would be a good place to document them?

2018-09-14 08:06 UTC, owen-jones-diffblue commented on jbmc/src/java_bytecode/java_class_loader.cpp
> +/// \@OverlayClassImplementation. They serve the following purpose. When the JVM
I've added documentation for them

2018-09-14 09:53 UTC, antlechner approved these changes

2018-09-14 09:53 UTC, antlechner commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +  /// \@OverlayMethodImplementation. They should only appear in
:+1: Thanks for explaining this, I wasn't sure if `@OverlayClassImplementation` automatically turned all methods into overlay methods, of if within an overlay class methods could still be declared to be overlay methods or not.

2018-09-14 09:53 UTC, antlechner commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +  /// will be loaded by JBMC instead of the corresponding method in the
:bee: Could you explain what "the corresponding method" is (i.e. method with the same signature in a class of the same name that was loaded before)?

2018-09-14 09:53 UTC, antlechner commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +  /// to overlay the corresponding method in the
:bee:

2018-09-14 11:00 UTC, owen-jones-diffblue commented
I've improved the documentation and also added a test for ignored methods. I've done it in the context of an overlay class, although they do not need to be used in that context, because that is what they were created for.

2018-09-14 11:26 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: ae0bb0a203fe807074206869620ff9b8cdc98d41).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84818067

2018-09-14 12:57 UTC, NathanJPhillips requested changes
At least one typo

2018-09-14 12:57 UTC, NathanJPhillips commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +  /// \return true if the method is an overlay method, else false
Whoops

2018-09-14 12:57 UTC, NathanJPhillips commented on jbmc/src/java_bytecode/java_class_loader.cpp
> +/// following ways: adding a field (by having a  new field), adding a method
Double space.

2018-09-14 12:57 UTC, NathanJPhillips commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +      + ":" + method.descriptor;
Is this clang? Seems like it should be indented to me.

2018-09-14 13:13 UTC, owen-jones-diffblue commented on jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
> +  /// \return true if the method is an overlay method, else false
Whoops

2018-09-14 13:26 UTC, NathanJPhillips approved these changes

2018-09-14 13:47 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 3a2a898c0068ca151982972806b7baffec017b6a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84832959
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-09-14 13:52 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 41300064067d3cd61b9543076fad88aed48c1071).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84833676

2018-09-14 13:58 UTC, merged