Cleanup error handling in solvers/qbf
diffblue/cbmc pull request #2961
Opened 2018-09-14 16:44 UTC by xbauch

2018-09-14 17:21 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 6a24c2c6b239e069a0e27005aa3de9b55d01fe57).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/84858721

2018-09-17 17:07 UTC, peterschrammel commented on src/solvers/qbf/qbf_bdd_core.cpp
>    return tvt(false);
Why is this required here and not below, eg in `m_get`?

2018-09-17 17:07 UTC, peterschrammel commented on src/solvers/qbf/qbf_bdd_core.cpp
> +        "Only handles quantified variables.");
start with lower case (several occurrences)

2018-09-18 14:44 UTC, xbauch commented
Lower cases and full stops fixed, redundant return statements removed.

2018-09-18 15:18 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: fb13b743ff2963a836799d11508da0d6fae581d5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85159051

2018-09-18 21:58 UTC, tautschnig requested changes

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_bdd_core.cpp
> +      model_bdds[l.var_no()] != NULL,
While at it: please use `nullptr` instead of `NULL`

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_quantor.cpp
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_qube.cpp
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_qube_core.cpp
> +#include <util/invariant.h>
Move one line down to group with the `mp_arith.h` include

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_qube_core.h
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_skizzo.cpp
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_skizzo_core.cpp
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qbf_skizzo_core.cpp
> +    INVARIANT(!result, "existential mapping from sKizzo missing");
Remove the negation, i.e., the invariant is `result`, not `!result`

2018-09-18 21:58 UTC, tautschnig commented on src/solvers/qbf/qdimacs_cnf.cpp
> +#include <util/invariant.h>
Nit-pick: add a blank line before this include.

2018-09-19 07:53 UTC, xbauch commented
Added blank lines before `util/invariant.h` includes, fixed the skizzo invariant condition typo.

2018-09-19 08:42 UTC, tautschnig approved these changes
Looks good to me, please squash and rebase.

2018-09-19 09:23 UTC, xbauch commented
Squashed and rebased.

2018-09-19 10:02 UTC, merged

2018-09-19 10:05 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 706a529c9611142af1b71c4fb9408fc042e27304).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85264387