--show-vcc now uses format()
diffblue/cbmc pull request #2977
Opened 2018-09-18 14:46 UTC by kroening

2018-09-18 16:52 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 145603cc5519da3cc483496c437b5bf819c6f8a2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85176699

2018-09-18 21:00 UTC, tautschnig reviewed
Mostly looks good to me except for the below questions, but I'm a bit surprised that none of the regression tests need to be adjusted.

Edit: I am deducing that we are not properly testing this. That needs to be fixed.

2018-09-18 21:00 UTC, tautschnig commented on src/goto-symex/show_vcc.cpp
> +#include <sstream>
While that is now certainly necessary: are `fstream` and `iostream` actually required?

2018-09-18 21:00 UTC, tautschnig commented on src/goto-symex/show_vcc.cpp
> +      out << s_it->source.pc->source_location << '\n';
Ok, but unrelated?

2018-09-18 21:00 UTC, tautschnig commented on src/goto-symex/show_vcc.cpp
> +          out << '\n';
Is there actually value in this? If there is, then it should likely be guarded by `#ifdef DEBUG` instead of `#if 0`

2018-09-18 21:00 UTC, tautschnig commented on src/goto-symex/show_vcc.cpp
> +    out << '{' << 1 << "} " << format(s_it->cond_expr) << '\n';
How about `out << "{1} " ...` unless some magic is happening here?

2018-09-21 18:55 UTC, kroening commented on src/goto-symex/show_vcc.cpp
> +#include <sstream>
Yes, still needed.

2018-09-21 18:56 UTC, kroening commented on src/goto-symex/show_vcc.cpp
> +      out << s_it->source.pc->source_location << '\n';
Ok, will split

2018-09-21 18:58 UTC, kroening commented on src/goto-symex/show_vcc.cpp
> +    out << '{' << 1 << "} " << format(s_it->cond_expr) << '\n';
Ok

2018-09-21 18:58 UTC, kroening commented on src/goto-symex/show_vcc.cpp
> +          out << '\n';
Ok

2018-09-22 12:16 UTC, tautschnig requested changes
The changes in here all look good, but (as stated in #2978) changes to the output should really break some tests. Is it really the case that the output has not changed at all, despite now using unicode symbols for all sort of operators? I'd rather think that we are not testing this output anywhere, and this makes me nervous. I think there are already several regression tests using `--show-vcc`, but apparently these don't actually inspect the output.

2018-09-22 12:47 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: a74e0516840867e3ea2532762054080f7e1bfa14).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85634310

2018-10-11 14:37 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 8d3b637a4fda900bff457b3a60b84fdd5cac42f6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87640378
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-10-15 00:54 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 857797c239e164e245b42c2062b4b927362ad22b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87897393

2018-10-17 20:20 UTC, kroening commented
There's now a test that looks at the output.

2018-10-18 08:06 UTC, tautschnig approved these changes

2018-10-18 08:06 UTC, merged