format(expr) beautification for quantifiers and = on booleans
diffblue/cbmc pull request #2978
Opened 2018-09-18 14:59 UTC by kroening

2018-09-18 15:51 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: fa434a597a62f4e3658b3ee058d39ace43ab0f3b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85166064
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-09-18 16:11 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 3629a4ae57914d12fb16245efd8445577ac7b383).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85169864

2018-09-19 09:23 UTC, smowton commented on src/util/format_expr.cpp
> +      operator_str = u8"\u21d4"; // <=>, U+21D4
I think this would confuse someone using the output to debug, since they'd go looking for ID_iff

2018-09-19 16:30 UTC, kroening commented on src/util/format_expr.cpp
> +      operator_str = u8"\u21d4"; // <=>, U+21D4
Remove ID_iff?

2018-09-19 16:55 UTC, tautschnig commented on src/util/format_expr.cpp
> +      operator_str = u8"\u21d4"; // <=>, U+21D4
It's used only four times across the code base, that makes for an almost trivial PR.

2018-09-19 21:43 UTC, kroening commented on src/util/format_expr.cpp
> +      operator_str = u8"\u21d4"; // <=>, U+21D4
#2999

2018-09-19 23:43 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: be0aa3201dd19aa645b254f6958c46b1c9125cd0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85359340

2018-09-20 07:39 UTC, tautschnig requested changes
The fact that user-visible output changes but no changes to tests were necessary implies that we don't actually test this code. This might change if #2977 were merged, so let's get that merged first.

2018-09-20 07:59 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 37f5b8eeb8a29ff7baff60f912cea01a2476f8ff).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85388192

2018-09-20 09:26 UTC, smowton approved these changes

2018-09-20 10:57 UTC, kroening commented
@tautschnig This is now somewhat circular: to get #2977 merged, a lot of tests need to pass, and it's easier to achieve that if the output of format() is moved to be more similar to that what's there right now.
This PR was motivated by getting #2977 to merge.

2018-09-20 11:08 UTC, tautschnig approved these changes
Ok, let's add the tests in #2977 then.

2018-09-20 11:08 UTC, merged