use format() for --show-symbol-table
diffblue/cbmc pull request #2984
Opened 2018-09-19 00:21 UTC by kroening

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-09-19 07:15 UTC, tautschnig approved these changes
Looks ok to me modulo CI passing.

2018-09-19 07:57 UTC, peterschrammel approved these changes

2019-02-05 20:19 UTC, tautschnig requested changes
A lot of tests are disabled without providing a justification or a path forward.

2023-05-03 15:29 UTC, TGWDB commented
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

2023-05-03 15:29 UTC, closed without merging