Test Pointer_byte_extract8 now passes
diffblue/cbmc pull request #2995
Opened 2018-09-19 14:46 UTC by kroening

Pointer_byte_extract8 now passes, with minor adaptation to changes
that have happened in the meantime.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-09-19 14:56 UTC, tautschnig commented
It would be desirable to `git bisect` this to identify which commit actually fixed the problem.

2018-09-19 17:28 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 119d9da0d1d1623711f2b35b890f14815099d5e9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85319556

2018-09-26 13:24 UTC, tautschnig requested changes
I believe Pointer_byte_extract8 should be removed completely: we have Pointer_byte_extract5/no-simplify.desc (as of efea5c44759e) that covers this. It should probably have been removed as part of efea5c44759e (sorry, my bad).

2021-03-12 10:39 UTC, NlightNFotis commented
I'm closing this PR, having created a new one (https://github.com/diffblue/cbmc/pull/5917) that implements the fix that Michael has blocked this PR on.

2021-03-12 10:39 UTC, closed without merging