Console colors
diffblue/cbmc pull request #3015
Opened 2018-09-21 16:18 UTC by kroening

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-09-21 16:19 UTC, kroening commented
This will be hard to test: The effect is only visible when output is _not_ redirected.

2018-09-21 16:40 UTC, tautschnig requested changes
Essentially items 3 and 7 of the PR checklist. Please don't assign others when those cannot (yet) be ticked as it really means that the focus when reviewing shifts from the meat of the work to those superficial bits.

2018-09-21 16:40 UTC, tautschnig commented on src/util/cout_message.cpp
> +std::string console_message_handlert::command(unsigned c) const
Missing documentation. The name does not in an obvious way relate to it's functionality, and what values `c` should take is a mystery.

2018-09-21 16:40 UTC, tautschnig commented on src/util/cout_message.h
> +  bool use_SGR;
?

2018-09-21 16:40 UTC, tautschnig commented on src/util/message.h
> +  std::string command(unsigned c) const
Docs.

2018-09-21 16:40 UTC, tautschnig commented on src/util/message.h
> +  // return to default
What is the "default"? Default of what? Also: not Doxygen.

2018-09-21 16:40 UTC, tautschnig commented on src/util/message.h
> +  // set red foreground color
Doxygen, please.

2018-09-21 16:40 UTC, tautschnig commented on src/util/ui_message.cpp
> +        : cmdline.isset("json-ui") ? uit::JSON_UI : uit::PLAIN,
No change?

2018-09-21 16:40 UTC, tautschnig commented on src/util/ui_message.cpp
> +                                 : timestampert::clockt::NONE)
?

2018-09-21 17:51 UTC, kroening commented on src/util/ui_message.cpp
> +                                 : timestampert::clockt::NONE)
clang-format has had fun. Manually reverted.

2018-09-21 17:52 UTC, kroening commented on src/util/ui_message.cpp
> +        : cmdline.isset("json-ui") ? uit::JSON_UI : uit::PLAIN,
Also spurious clang-format change.

2018-09-21 20:16 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 2c09f3b62d1761e089a5cef93f8212738cf3bb8a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85603358

2018-09-25 17:27 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 8a40b36ed21260eb8aa151ea48d5943dd44b20ac).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85897347

2018-09-25 18:20 UTC, tautschnig commented on src/util/message.h
> +  /// return to default formatting, as defined by clienta
"clienta" is probably a typo, but I wouldn't understand what the "client" is either.
Nit-pick: Change is in the wrong commit (should just be part of the original commit introducing the documentation).

2018-09-25 18:20 UTC, tautschnig approved these changes

2018-09-26 10:53 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: d999a3e6f9b7fe55f0228e257f3a46dcd3d90f83).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85985276

2018-09-27 20:27 UTC, peterschrammel approved these changes

2018-09-27 21:55 UTC, merged