nullary and ternary expressions
diffblue/cbmc pull request #3017
Opened 2018-09-21 19:23 UTC by kroening

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [x] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-09-21 21:51 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 9c1f6281939469b7e40735dd038f325d98413648).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85611876

2018-09-22 06:20 UTC, smowton requested changes

2018-09-22 06:20 UTC, smowton commented on src/util/std_expr.h
> +class nullary_exprt:public exprt
Nitpick here and elsewhere: spacing: `...exprt : public exprt`

2018-09-22 06:20 UTC, smowton approved these changes
oops

2018-09-22 11:20 UTC, tautschnig approved these changes
Looks good modulo the below (partly required - to make CI happy) comments.

2018-09-22 11:20 UTC, tautschnig commented on src/util/std_expr.h
> +  /// remove all operand methods
What about copy_to_operands, move_to_operands?

2018-09-22 11:20 UTC, tautschnig commented on src/util/std_expr.h
>    /// \param : type Type of symbol
The `:` is in the wrong place, tripping up Doxygen. Not your fault, but nowadays it stops CI...

2018-09-22 11:20 UTC, tautschnig commented on src/util/string_constant.cpp
> +string_constantt::string_constantt() : nullary_exprt(ID_string_constant)
Should this one also be deprecated?

2018-09-22 14:46 UTC, kroening commented on src/util/std_expr.h
> +  /// remove all operand methods
yes, can go away as well

2018-09-22 14:55 UTC, kroening commented on src/util/string_constant.cpp
> +string_constantt::string_constantt() : nullary_exprt(ID_string_constant)
yes, while at it

2018-09-22 14:56 UTC, kroening commented on src/util/std_expr.h
>    /// \param : type Type of symbol
fixed

2018-09-22 16:25 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: dfb1c9575f6f5d3b2f7c96ff56f98407bfb24ff7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85638395

2018-09-22 16:28 UTC, merged