Invariant cleanup in flattening/boolbv_if
diffblue/cbmc pull request #3043
Opened 2018-09-25 15:03 UTC by hannes-steffenhagen-diffblue

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-09-25 16:22 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 3779e522d85b36e37e9600eb0bb9eab438bfd938).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/85890465

2018-09-25 18:24 UTC, tautschnig requested changes

2018-09-25 18:24 UTC, tautschnig commented on src/solvers/flattening/boolbv_if.cpp
> +  if(true_case_bv.size() != width || false_case_bv.size() != width)
I think `width` should just be passed as second argument to `convert_bv` thanks to your earlier work?!

2018-09-26 10:35 UTC, NlightNFotis commented on src/solvers/flattening/boolbv_if.cpp
> +  if(true_case_bv.size() != width || false_case_bv.size() != width)
@hannes-steffenhagen-diffblue `convert_bv` in `boolbv.cpp` was changed recently to take an optional size. https://github.com/diffblue/cbmc/blob/develop/src/solvers/flattening/boolbv.cpp#L114 That makes the invariant present here as well unnecessary.

2018-09-26 10:35 UTC, NlightNFotis requested changes
The data invariant is not needed, just pass the width as an extra argument to `convert_bv`. The invariant is being enforced inside `convert_bv` now.

2018-09-26 10:42 UTC, hannes-steffenhagen-diffblue commented
Apologies, the changes to `convert_bv` hadn't been made when I committed these changes. I'll revise them.

2018-09-26 14:37 UTC, hannes-steffenhagen-diffblue commented
@NlightNFotis @tautschnig I believe I've addresses your comments, can you rereview?

2018-09-26 14:44 UTC, tautschnig approved these changes

2018-09-26 15:14 UTC, NlightNFotis approved these changes
Looks good to me.

2018-09-26 15:31 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 2ab7ac72749b04ca8bad3fcb3fc3dc950bb74542).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86025732

2018-09-26 15:50 UTC, merged