deprecates exprt::move_to_operands(...)
diffblue/cbmc pull request #3073
Opened 2018-10-01 11:26 UTC by kroening

Since sharing has been introduced there is no measureable performance
benefit when using move_to_operands compared to copying.  Moving has the
disadvantage that there is a side-effect on the object that is moved.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-10-01 12:33 UTC, tautschnig requested changes
Sorry, a bit of a silly request-for-changes: could you please copy your analysis details from the other PR into the commit message? I think it's worth preserving that for the future, and it will be rather hard to find as this is across different PRs. Thank you!!!

2018-10-01 13:16 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: d9d34280bcea14a606e6ac6dd02fc3106bf05dbe).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/86459004

2018-10-06 09:19 UTC, kroening commented
@tautschnig Done.

2018-10-06 09:21 UTC, tautschnig approved these changes

2018-10-06 10:57 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 6f4274da4e2b5dcac026c828844b7f16e93b53a7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87094284

2018-10-06 13:11 UTC, merged

2018-10-06 14:45 UTC, smowton commented
Given the discussion in the code_blockt::add / move PR, quite surprised this got merged. There is only no performance difference when using copy doesn't cause any extra CoW breaks; would prefer to revert this and use move judiciously.