Java now uses struct_tag types
diffblue/cbmc pull request #3102
Opened 2018-10-05 18:44 UTC by kroening

Note that this does two things (switching base classes to struct_tags and switching the Java front-end to struct_tags). However, they can't be done separately.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-10-06 09:29 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 64bfc034386f8bc5c3592adbda7148ade2fb4d9b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87092812
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

2018-10-06 14:52 UTC, tautschnig approved these changes
Changes appear to be consistent.

2018-10-07 07:03 UTC, owen-jones-diffblue commented on src/cpp/cpp_typecheck_bases.cpp
>        error() << "expected type symbol as struct/class base" << eom;
Does this error message need to be updated?

2018-10-08 15:56 UTC, smowton commented
Reviewed the first 30% or so, seems ok so far but don't have time to read the whole thing

2018-10-11 12:01 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 24aa5f90b4dffdadcb1e120aa8a5e477082a3b9a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87616503
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-10-11 12:43 UTC, martin-cs approved these changes
The four lines that are in my area seem OK.

2018-10-11 22:19 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: d846585fa7a32eb313c884b297034abdec56a8cc).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87698036
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-10-12 06:39 UTC, peterschrammel commented
@thk123,  @allredj, please create a TG bump for this.

2018-10-12 09:24 UTC, allredj commented
will do

2018-10-12 11:55 UTC, allredj reviewed
This PR failed Diffblue compatibility checks (cbmc commit: 5f18b69cbb779cd58ff286d78b2e1887582668f6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87756938
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-10-22 09:40 UTC, allredj requested changes
This breaks test-generator. We're working on a fix but so far we were not able to make test-gen live with that change.

2018-11-08 18:17 UTC, allredj reviewed
:warning:
Diffblue compatibility check is currently unavailable.
Please create manual bump.
(cbmc commit: 39e5ab697b0f1b0907e75418feee35666d47f32a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90749965

2018-11-17 21:00 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 4b981568cfab44c796b64f6266215ad50198930d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/91761785
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-11-25 14:17 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 708a46d338045a6057fc29a5f3d6c3e9cc99934d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92467085
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-11-30 17:16 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: ddcf2c8e7c82f3c7bc1d6401ef4bdaa12dac94a0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93180215
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-12-07 20:00 UTC, closed without merging