smt2_parser: declare-datatypes for records
diffblue/cbmc pull request #3162
Opened 2018-10-14 13:39 UTC by kroening

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [X] My contribution is formatted in line with CODING_STANDARD.md.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-10-14 15:33 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 2be6d66c9976ca1444ab33a851d36ca7cde928b0).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/87881689

2018-10-14 18:20 UTC, tautschnig requested changes
This seems rather misleading to me: 1) the comment in the code says "process" but then the method doesn't actually do anything other than discarding tokens; 2) I failed to decipher the commit message.

2018-10-15 15:04 UTC, martin-cs reviewed
I think I'm with @tautschnig on this one; this just seems to ignore them.

2018-10-15 15:04 UTC, martin-cs commented on src/solvers/smt2/smt2_parser.cpp
> +/// process a datatype declaration (a Z3 extension)
Datatypes are in SMT-LIB; they aren't a Z3 extension any more.

2018-11-25 13:13 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8cbdec49c1a460c1b0b477249d6d2a75bf387f42).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92465976

2018-11-30 17:18 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5653817d708488c9867f61ea8acd94d47358ef6f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93183039

2018-12-01 12:10 UTC, tautschnig commented
The comment that @martin-cs made is still left to be addressed, otherwise this would be good to go.

2018-12-08 13:47 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 874ff04c648d7f51d75460e9ac2502b25fd931f5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94083271

2021-06-09 13:58 UTC, TGWDB commented
Closing this PR as no longer being worked on. Also linking to #6134  since the work here may be of interest there.

If you believe this is erroneous, please reopen and note why.

2021-06-09 13:58 UTC, closed without merging