JBMC: support list-symbols
diffblue/cbmc pull request #3207
Opened 2018-10-19 16:20 UTC by smowton

Add `--list-symbols` argument to JBMC (matching existing argument in CBMC), and fix the accidental inclusion of the symbol value in the JSON output even in `list` mode.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in ODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-10-20 10:03 UTC, kroening approved these changes

2018-10-20 10:55 UTC, peterschrammel approved these changes
Clang-format is complaining: https://travis-ci.org/diffblue/cbmc/jobs/443779256#L547

2018-10-20 10:55 UTC, peterschrammel commented on jbmc/src/jbmc/jbmc_parse_options.h
> +  "(show-symbol-table)(list-symbols)(show-parse-tree)" \
Preferably put on separate lines.

2018-10-20 15:55 UTC, tautschnig requested changes
I am struggling to reconcile the commit subject with the actual changes. The notes in the PR make more sense, but seemingly those haven't made it into the commit message.

2018-10-22 08:38 UTC, smowton commented
@tautschnig oops, was from a subtree cherry-pick. Fixed.

2018-10-22 15:30 UTC, tautschnig approved these changes

2018-10-22 23:01 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 74c9ff9351337a571ad708ad1d22d574f547c688).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/88760621

2018-10-23 08:00 UTC, allredj reviewed
Passed Diffblue compatibility checks (cbmc commit: 87581eb741ef24ce4a9259adae65404189568fa7).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/88799241

2018-10-23 14:36 UTC, merged