split up property_checkert
diffblue/cbmc pull request #3268
Opened 2018-11-04 12:49 UTC by kroening

This class has two functionalities, which are now separate.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-11-04 13:29 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: f1e7869dc0d48f9dcd16ae8e915d5a78473ccc19).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90191304
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-11-04 18:28 UTC, tautschnig requested changes

2018-11-04 18:28 UTC, tautschnig commented on src/goto-programs/property_checker.h
> +class property_checkert : public messaget, public property_resultst
I don't know what the reason for the proposed change is, but moving from membership to inheritance-by-a-single-class single class seems strange. And "a property checker _is a_ property result" does not seem meaningful I must say.

2018-11-05 08:33 UTC, kroening commented on src/goto-programs/property_checker.h
> +class property_checkert : public messaget, public property_resultst
Ok, now different approach.

2018-11-05 08:49 UTC, tautschnig requested changes
I'm afraid you've opened Pandora's Box. I had some months ago already complained about ~the completely undocumented `safety_checkert`, and now we're in the same place with~ `property_checkert` (#2212). This is an undocumented interface that seems to add a layer of obfuscation rather than providing an intuitive API. It's unusable unless one does RTFS. Maybe now is a time to fix this? And why does it actually live in `goto-programs`?

2018-11-05 08:49 UTC, tautschnig commented on src/goto-programs/property_checker.h
> +  property_checkert()
Is the default constructor actually meaningful?

2018-11-05 08:49 UTC, tautschnig commented on src/goto-programs/property_checker.h
> +  virtual property_resultst operator()(const goto_modelt &) = 0;
I note that this is returning a large structure by value.

2018-11-05 08:49 UTC, tautschnig commented on src/goto-programs/property_checker.h
>    void initialize_property_map(const goto_functionst &);
This method no longer exists.

2018-11-05 08:49 UTC, tautschnig commented on src/goto-programs/property_checker.h
> +class property_checkert : public messaget
So what is this class actually good for? The use of `operator()` instead of a named method unfortunately does not add clarity either.

2018-11-05 08:49 UTC, tautschnig commented on src/goto-programs/property_checker.h
> +  void initialize(const goto_functionst &);
Why is this not the constructor?

2018-11-05 09:11 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 4c017a441640532c50cb70abd105ba3bd70e3db1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/90237753
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2018-11-06 03:56 UTC, peterschrammel commented
Maybe look at what is coming here: 
* https://github.com/peterschrammel/cbmc/blob/bmc-utils/src/goto-checker/goto_verifier.h
* https://github.com/peterschrammel/cbmc/blob/bmc-utils/src/goto-checker/goto_checker.h
This an attempt at unifying all BMC interfaces that we have. It's not fully complete yet and we should discuss about naming these classes appropriately, but I'm not far away from it.

The final result will then be invoked as follows, which IMO is a huge improvement over what we have now:
https://github.com/peterschrammel/cbmc/blob/bmc-utils/src/cbmc/cbmc_parse_options.cpp#L535

2018-11-06 06:03 UTC, tautschnig commented
Thanks @peterschrammel! Is there some story how these (which?) PRs fit together and lead us to the desired state?

2018-11-06 19:24 UTC, peterschrammel commented
I haven't split up my changes into proper PRs yet. I'm currently making sure that I haven't overlooked anything fundamental in the integration with cbmc, jbmc, symex and TG. 
At the current pace it will probably take 2 weeks until I have cleaned up the stuff.

2018-12-08 13:58 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bb3c98296b05c962fb871bee67913b1cc1d7ba15).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94084024

2019-02-05 19:45 UTC, tautschnig commented
@kroening @peterschrammel Is this one still relevant?

2019-05-16 07:08 UTC, tautschnig commented
@kroening @peterschrammel ping?

2019-05-16 07:32 UTC, peterschrammel reviewed
That's obsolete and can be deleted.

2019-05-16 07:33 UTC, closed without merging