Adding smallest_unused_suffix cache
diffblue/cbmc pull request #3296
Opened 2018-11-08 18:27 UTC by JohnDumbell

This just speeds up symbol name generation in situations where there are large amounts of symbols already existing with the same prefix. A similar approach to the journalling_symbol_tablet in how it works - you just wrap any current symbol table, and as long as that instance lasts it'll store what the next available index is so usually you'll only need to do a minimal amount of finds to get the next free suffix.

It doesn't go overboard with trying to work out if there are any holes in the symbol table that we could re-use because it's essential that each suffix + prefix combo be predictable, so only clears the cache when you clear the whole symbol table.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-11-08 19:29 UTC, tautschnig requested changes
I would like to see an analysis as to why it is even happening that there are this many symbols with the same prefix. And then data (how much faster is it, on which benchmarks). And commits that actually provide a rationale for the change happening.

I dare saying this because ff25b2cffd0.

2018-11-09 09:56 UTC, smowton commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +        symbol_table_buildert suffix_aware_table =
`suffix_aware_table` -> `symbol_table_builder`

2018-11-09 09:56 UTC, smowton commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +            symbol_table_buildert::build(symbol_table);
`::build` -> `::wrap`

2018-11-09 09:56 UTC, smowton commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +          journalling_symbol_tablet::wrap(suffix_aware_table);
To check: does the journalling table forward `next_suffix` to its wrapped table?

2018-11-09 09:56 UTC, smowton commented on src/goto-cc/compile.cpp
> +  symbol_table_buildert suffix_aware_table =
suffix_aware_table -> symbol_table_builder

2018-11-09 09:56 UTC, smowton commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +          symbol_table_buildert::build(symbol_table);
Ideally squash this formatting commit into the appropriate precessor commits

2018-11-09 10:00 UTC, smowton commented
In brief your previous fix changed the complexity of generating N symbols with the same prefix in a symbol table of size M from O(NM) to O(N^2), which is definitely an improvement, but this patch bumps it to O(N). I believe the typical case where this really bites us is e.g. 1000 `some.package.SomeClass.somefunction::new_tmp` symbols costing ~500000 string-concats and symbol-table lookups, but we'll put a concrete benchmark together soon.

2018-11-09 10:03 UTC, tautschnig commented
Why do we ever have
>  I believe the typical case where this really bites us is e.g. 1000 `some.package.SomeClass.somefunction::new_tmp` symbols 

?

2018-11-09 10:04 UTC, tautschnig commented
That is: can we really not do any better than calling all of them `new_tmp`?

2018-11-09 10:21 UTC, smowton commented
They're temps generated at a `new` site. We've also got return-value temps, temps created by `goto_convertt` e.g. to isolate side-effects (`f() + 2` -> `tmp = f(); tmp + 2`), and so on: there are 20 `get_fresh_aux_symbol` or `goto_convertt::new_tmp_symbol` in cbmc and another 30 in jbmc.

Possible solutions:

1. For each user, give the variable some appropriate qualifier that makes clashes less likely --  for example, something derived directly from Java bytecode could be named after its bytecode index. This puts extra burden on new users though, and people making future changes will continue to be tempted to use `get_fresh_aux...` naively. It's also likely we would not bother to upgrade some use sites on the rationale "eh, when will this ever be frequently visited," which will doubtless bite us in the future.

2. Introduce module-scoped name allocators. For example, `goto_convertt::new_tmp_symbol` would be an ideal place to count newly-allocated symbols and try harder to avoid the quadratic cost with an educated guess. However this is quite intrusive -- for example if `goto_convertt` calls `some_utility` which allocates symbols we must teach `some_utility` how to use `goto_convertt`'s name allocator, probably by parameterising it.

3. Improve `symbol_tablet` so it can always answer repeated fresh-name queries in linear, not quadratic time. This is very unintrusive, but @kroening doesn't like it because the next-name map would stick around consuming memory even when we proceed to phases when the symbol table is read-mostly.

4. The solution adopted here: a symbol-table wrapper that holds the next-name map, and whose lifespan is chosen to include the table-building phase but not the mostly-read phase. The wrapped table has an efficient get-fresh-symbol operation without needing each individual user to solve that problem, and can be passed to any utility expecting a `symbol_table_baset` without that utility needing specific modification.

2018-11-09 10:27 UTC, smowton commented
Also @JohnDumbell recommend separating a commit that just turns `symbol_tablet` -> `symbol_table_baset` from one that actually introduces uses of the new wrapper.

2018-11-09 10:29 UTC, tautschnig commented
> Also @JohnDumbell recommend separating a commit that just turns `symbol_tablet` -> `symbol_table_baset` from one that actually introduces uses of the new wrapper.

+1 to that, and possibly even do so in a separate PR: this is quite likely the syntactically most intrusive part of this PR, and at the same time actually just the right thing to do irrespective of this PR.

2018-11-09 10:38 UTC, tautschnig commented
@smowton, in response to your earlier elaboration: this PR, and thus item 4 from your list, may be absolutely the right thing to do. But I want to make as sure as by any means possible that we are not fixing symptoms, but actually treat the root cause. And having symbols named `tmp` seems like a bad idea either way, so I would strongly encourage also investing in item 1 from your list. If we are naming a symbol "tmp", then you might as well argue that we are wasting three bytes in the string table as using just a number would be about as informative. (And indeed translating `f() + 2` to `tmp = f(); tmp + 2` is just bad, the name ought to reflect that it's about `f`.) So let's please try to fix this wherever we can, and then we can also include the changes proposed in this PR as a safety net. But there must be data, and there must a clear rationale for each change.

2018-11-09 10:42 UTC, JohnDumbell commented
I'll apply the recommendations / git changes now and then get to work on an actual benchmark. In the particular case where I saw this (and then thought doing something about it might be useful) the actual suffix was in the 4000's.

2018-11-09 10:50 UTC, smowton commented
@tautschnig that sounds good -- better names wherever possible, *and* a fresh-symbol routine that can be relied upon not to explode when there are a few thousand name clashes.

2018-11-09 10:57 UTC, tautschnig commented
@JohnDumbell 4000+ name clashes seem scary - wouldn't that imply that the function as at least 4000 instructions? Of course that's possible, but it seems worth taking another look. Taking action to fix a problem is good, but I want to be really sure we are fixing the right problem.

2018-11-09 10:58 UTC, smowton commented
At a guess the pathalogical cases will be mechanically-generated code

2018-11-09 11:34 UTC, chrisr-diffblue commented
@smowton I've also seen such pathological code in certain embedded systems.... sigh.

2018-11-22 15:31 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7f5890d89ae322600ce68c0d6511b9ecc3ce737c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92299022

2018-11-22 15:53 UTC, JohnDumbell commented
@tautschnig Sorry it took a little while, but we did some tests on a c method with 10,000 lines of `x += argc ? f() : g();` to generate a large amount of temp symbols needing to be created, and with this PR applied it took 1:11 to finish generating the GOTO (it then got stuck on symex), and without it, I stopped timing after 30 minutes of it not finishing the generation.

I tried recreating the test on some less extreme Java examples and only got around a 5% reduction in run-time due to bytecode per method limitation and me not knowing the absolute best way to generate as many temporaries as possible, but I also didn't recognise any noticeable slowdown either. I know it provides similar benefits to the c benchmark on the library I originally found the issue in (Groovy), but trying to measure them precisely is a bit harder because something else is going on to cause that many temporaries to be needed in the first place which slows it down elsewhere.

If you need anything more precise just say.

(Also thanks to @smowton on this)

2018-11-22 15:59 UTC, smowton commented
(the reason for that particular formulation btw: ternary conditionals get a temporary allocated if either of their branches may have side-effects)

2018-11-26 18:36 UTC, peterschrammel approved these changes
Could we create names with `function_id::tmp::<hash of expr/symbol names in expr>::tmpX` to make clashes less likely?

2018-11-27 14:36 UTC, JohnDumbell commented
@peterschrammel don't see any reason why not, beyond the hashing/name creation overall might be slower than just accepting any clashes and doing one additional find using the wrapper? (also more unique names = more instances in the map with smaller counts against them) 

I guess the differences would be minor either way though, and you'd definitely benefit if you didn't have the wrapper. I think I'd like to do it either way though, better to do it in a different PR?

2018-11-28 22:54 UTC, tautschnig approved these changes
Looks good except for the comments below. Also it would be nice to copy the report on the experiment into one of the commit messages as it's somewhat cumbersome to go from the git history to GitHub to then find the data.

2018-11-28 22:54 UTC, tautschnig commented on src/util/symbol_table_builder.h
> +// Copyright 2016-2018 Diffblue Limited. All Rights Reserved.
This is different from any other file headers in use. The "All Rights Reserved." scares me.

2018-11-28 22:54 UTC, tautschnig commented on src/util/symbol_table_builder.h
> +#include "symbol_table.h"
Why is this header required here?

2018-11-28 22:54 UTC, tautschnig commented on src/util/symbol_table_builder.h
> +                         .insert(std::pair<std::string, std::size_t>(prefix, 0))
You should be able to use `{prefix, 0}` instead of `std::pair<....>(prefix, 0)`

2018-11-28 22:54 UTC, tautschnig commented on src/util/journalling_symbol_table.h
> +  std::size_t next_unused_suffix(const std::string &prefix) const override
A comment about the commit message: I don't understand "Due to the inclusion of another method we just need to make sure any calls are routed to the wrapped table and not the parent." Which method is this "another" method that's causing trouble?

2018-11-28 22:54 UTC, tautschnig commented on jbmc/src/java_bytecode/java_bytecode_language.cpp
> +#include <util/symbol_table_builder.h>
Place this include with the other ones from `util` above.

2018-11-29 20:54 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6425eb1c703fa4f644f08f869d88550038e0fd42).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93065007

2018-11-29 22:12 UTC, merged