fix function depth display in case of hidden calls/returns
diffblue/cbmc pull request #3439
Opened 2018-11-18 12:40 UTC by kroening

Previously, hidden function calls or hidden functions could cause the depth
count to get out of sync.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [X] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-11-18 13:16 UTC, tautschnig commented
Would it be possible to include a test, please?

2018-11-18 14:14 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: eeed8957dfc5982019039e6e8282e837c0cf7d75).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/91782598

2018-11-19 10:14 UTC, smowton approved these changes

2018-11-19 11:33 UTC, NlightNFotis approved these changes

2018-11-24 11:10 UTC, peterschrammel approved these changes

2018-11-24 14:22 UTC, tautschnig requested changes
Please add a test.

2018-11-29 03:37 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5cb5d7e2479d182709b5048bac9437b6901a9c91).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92946675

2019-05-19 20:06 UTC, tautschnig commented
How would counters actually get out-of-sync here? After all, a hidden call is always paired with a return from the same function?

2023-05-03 15:30 UTC, TGWDB commented
Closing due to age (no further comment on PR content), please reopen with rebase on develop if you intent to continue this work.

2023-05-03 15:30 UTC, closed without merging