Generate function bodies with nondet return values
diffblue/cbmc pull request #3457
Opened 2018-11-24 13:09 UTC by danpoe

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-11-26 09:21 UTC, smowton reviewed
Cursory review because this is *big*. For a more thorough look over I recommend introducing this in stages

2018-11-26 09:21 UTC, smowton commented on src/langapi/language.h
> +  virtual bool generate_support_functions(symbol_tablet &symbol_table) = 0;
Unrelated restyle in commit

2018-11-26 09:21 UTC, smowton commented on src/langapi/language_file.cpp
> +#include <util/object_factory_parameters.h>
Adding an include but nothing that uses it (in this commit)?

2018-11-26 09:21 UTC, smowton commented on src/ansi-c/c_nondet_symbol_factory.cpp
> -/// \param prefix: The prefix to use for the symbol's basename
Why is this in this PR?

2018-11-26 09:21 UTC, smowton commented on regression/cbmc/pointer-function-parameters-struct-simple-recursion-2/main.c
> +  assert(p->next != &dummy);
Also assert p->next != p->prev?

2018-11-26 09:21 UTC, smowton commented on src/ansi-c/c_nondet_symbol_factory.cpp
> -/// \param allow_null: Whether to allow a null value when type is a pointer
does removing this unused parameter belong in a different commit?

2018-11-26 09:21 UTC, smowton commented on src/util/allocate_objects.cpp
> +  const typet &allocate_type,
allocate_type and alloc_type are very similar names

2018-11-26 09:21 UTC, smowton commented on src/util/allocate_objects.h
> +  /// Allocate dynamic objects (using MALLOC)
now using ALLOCATE

2018-11-26 11:01 UTC, danpoe commented
@smowton Thanks for the review! The PR is based on another open PR (#3455) and in this one only the last two commits are new (see PR description).

2018-11-28 20:25 UTC, kroening commented
Should this live in goto-instrument? It's an instrumentation.

2018-11-28 20:26 UTC, kroening requested changes
Should be in goto-instrument!

2018-11-29 13:58 UTC, danpoe commented
@kroening One thing this PR does is move `generate_function_bodies.h/cpp` from `goto-programs` to `goto-instrument`. However I left the C object factory in `ansi-c` (just like the Java object factory is in `java_bytecode`). Are you suggesting to move the C object factory to `goto-instrument` as well?

2018-11-29 19:22 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f2506f96a48257944df5ef908182c824648b30ee).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93055935

2019-01-22 15:01 UTC, danpoe commented
@kroening This is now done in goto-instrument.

2019-01-22 16:49 UTC, chrisr-diffblue approved these changes
LGTM

2019-01-22 17:42 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: cc4baa5b3b7d3c5354806d54fb76b343e5ca2a4e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98196114
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-22 22:44 UTC, kroening approved these changes

2019-01-23 12:23 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5fa9452d56904051f480d5595ffdf64432e80018).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98301475

2019-01-23 12:32 UTC, merged