Add optional_lookup utility function
diffblue/cbmc pull request #3473
Opened 2018-11-27 16:41 UTC by hannes-steffenhagen-diffblue

This provides a more ergonomic interface over map::find for the case when you don't need an iterator

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-11-27 16:53 UTC, xbauch approved these changes
Looks good, would be nice to generalise it to use `std::find` in the general case. Then a specialisation for containers that implement their own `find` function.

2018-11-27 17:06 UTC, hannes-steffenhagen-diffblue commented
@xbauch Thought about it, wasn't completely sure if it was a good idea because for _most_ containers the result should be `optional<value_type>`, _except_ for `map` where we only want the value but `value_type` is a key-value pair...

2018-11-27 18:29 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5139616f756f1609d187ef24d923e6d691106ecb).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/92738933

2018-11-28 02:13 UTC, sonodtt commented
Interesting. As a generic problem, this becomes quite non-trivial. 

As I understand it, specialisation in the generic scenario "has a method .find()" would involve the member detection idiom. Can define a trait for checking for find(). Quite an issue to make robust considering inherited methods et al. 
But essentially a form of contract.

In the non generic scenairo specialisation for std::map or other known types, which must be explicit.

These guys, who quite definitely know what they're doing - found a simple edge case, that seemed surprisingly hard to get right:
https://web.archive.org/web/20180409123554/https://blog.quasardb.net/sfinae-hell-detecting-template-methods

2018-11-28 02:14 UTC, sonodtt approved these changes

2018-11-28 13:46 UTC, tautschnig requested changes
This strictly needs a unit test. At present, we don't even know whether this is syntactically acceptable to all our compilers used in CI.

2018-11-28 13:46 UTC, tautschnig commented on src/util/optional_utils.h
> +#include <map>
Why are those includes required here?

2018-11-29 12:39 UTC, hannes-steffenhagen-diffblue commented
@tautschnig Removed vestigial includes and added a unit test

2018-11-29 13:29 UTC, tautschnig approved these changes

2018-11-29 13:41 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4e506bc20a6f8a3d85d421ca2dad8644074c45cf).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93002859

2018-11-29 17:10 UTC, hannes-steffenhagen-diffblue commented
CodeBuild failure due to spurious network issues, restarting CI

2018-11-29 17:47 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: fa39d19e9de42f71381f5518ccb161e828543719).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/93043043

2018-11-30 10:14 UTC, merged