Add `-f` option to `test.pl` to forward the test description
diffblue/cbmc pull request #3571
Opened 2018-12-14 19:37 UTC by thomasspriggs

Adding this option enables the command called by `test.pl` to use name
of the test in its processing. This is usefull where there are multiple
tests in a directory and we want the command to write additional files
based on the name of the test.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-12-14 20:07 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 9b65b1a7618e8869b9ded7f8f8af33a8c1a78d03).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/94827406

2018-12-17 13:34 UTC, thk123 requested changes
Code changes look fine but new flag needs documenting

2018-12-17 13:34 UTC, thk123 commented on regression/test.pl
> +our ($opt_c, $opt_f, $opt_i, $opt_j, $opt_n, $opt_p, $opt_h, $opt_C, $opt_T, $opt_F, $opt_K, $opt_s, %defines, @include_tags, @exclude_tags); # the variables for getopt
:no_entry_sign: Needs documenting (line 261 onwards)

2018-12-17 13:35 UTC, thk123 commented on regression/test.pl
> +our ($opt_c, $opt_f, $opt_i, $opt_j, $opt_n, $opt_p, $opt_h, $opt_C, $opt_T, $opt_F, $opt_K, $opt_s, %defines, @include_tags, @exclude_tags); # the variables for getopt
Nope it's there and I am blind.

2018-12-17 13:35 UTC, thk123 approved these changes

2018-12-17 13:40 UTC, LAJW approved these changes
I don't like polluting test output with unnecessary information, but whatever.

2018-12-17 13:42 UTC, merged