Constant propagation of nondet-symbol
diffblue/cbmc pull request #3619
Opened 2018-12-21 16:00 UTC by tautschnig

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-12-21 16:01 UTC, tautschnig commented
@smowton I'd be curious whether this can do some of what otherwise might only be achievable via field sensitivity for Java.

2018-12-21 16:28 UTC, smowton commented
Propagating a nondet symbol? I don't see how, could you elaborate what you think it might do?

2018-12-21 16:28 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3714d2507bda17b1d1924e3bee3d8c3f018af4dd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95553013

2018-12-21 16:38 UTC, tautschnig commented
> Propagating a nondet symbol? I don't see how, could you elaborate what you think it might do?

A nondet symbol is a constant, we just don't know its value. The gain is that it does not interfere with structs that are otherwise constants (those of the kind that we know their value), see also the regression test that's included.

2018-12-26 14:43 UTC, kroening commented
We should probably rename is_constantt to something like "forward_substitution".

2018-12-26 14:44 UTC, kroening commented
Specifically on Java: in principle, Java objects should get zero initialised -- this should enable the propagation without this PR. It may be worth checking whether that actually works.

2018-12-27 10:06 UTC, smowton commented
@kroening they do get zero-init'd; this would catch a case such as `otherwise_const_thing->field = nondet_value;`. Because various arithmetic operations on constants are themselves considered constants quite a lot would get propagated -- I think the objects would only stop getting propagated once there's a phi node, as `if_exprt` does not inherit constant-ness from its arguments.

2019-01-24 17:57 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: f241b8be9d694ed2749f56b1e9eb7d19c65e023b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98502213
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-26 14:30 UTC, smowton commented
My inclination is this is a bad thing (propagating not just `nondet_symbol#1` but also a big ball of non-constant arithmetic containing `nondet_symbol#1`) and will be rendered redundant by field sensitivity

2019-01-26 14:46 UTC, tautschnig commented
> [...] and will be rendered redundant by field sensitivity

I would have liked to believe this, but in fact these are very much complementary. On one of our verification tasks field sensitivity works as expected, but in order to handle a call to `memset` we need a pointer offset to propagate, which is computed from a sequence of pointer arithmetic. The simplifier is then able to figure out that all the nondets do not matter for the pointer offset, and yields a much-needed constant.

2019-01-26 15:27 UTC, smowton approved these changes
Fair enough, this is easy to revert if it has bad side-effects, so let's try it

2019-01-26 15:27 UTC, smowton commented on src/goto-symex/goto_symex_state.cpp
> +      if(
Seems oddly specific, add a comment saying why this particular restriction?

2019-01-26 15:27 UTC, smowton commented on src/goto-symex/goto_symex_state.cpp
> +      const irep_idt &obj_identifier = to_ssa_expr(expr).get_object_name();
Similarly could use a comment: why this policy for guards only?

2019-01-28 23:18 UTC, peterschrammel approved these changes

2019-01-28 23:18 UTC, peterschrammel commented on src/goto-symex/goto_symex_state.cpp
> +      const irep_idt &obj_identifier = to_ssa_expr(expr).get_object_name();
Suggest to take the guard prefix from a single place of definition.

2019-01-30 20:28 UTC, tautschnig commented on src/goto-symex/goto_symex_state.cpp
> +      if(
Comment added.

2019-01-30 20:44 UTC, tautschnig commented on src/goto-symex/goto_symex_state.cpp
> +      const irep_idt &obj_identifier = to_ssa_expr(expr).get_object_name();
Comment added and a refactoring commit added that makes all users use a single definition.

2019-01-31 08:09 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3a747ed82f5a9cb4df9316328ae9986e35865f89).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99236122

2019-01-31 08:23 UTC, tautschnig commented
I'm quite keen to merge this, but I am worried that it produces different test results: @allredj @romainbrenguier could you please set up some test to check that merging this PR won't break TG?

2019-01-31 09:29 UTC, romainbrenguier commented
@tautschnig 
> @romainbrenguier could you please set up some test to check that merging this PR won't break TG?

I've made the PR, I will update you when we get the results.

2019-01-31 13:06 UTC, tautschnig commented
Marking as do-not-merge as there appear to be TG failures that need investigation.

2019-01-31 13:37 UTC, romainbrenguier requested changes
I tested this branch on the following example:
```
public class andNot_Bug {
    public static void main(int capacity) {
        if(capacity < 1)
            return;
        boolean b1 = true;
        boolean b2[] = new boolean[capacity];
        b2[0] = false;

        for (int i = 0; i < b2.length; i++) {
            b1 = b1 && !b2[i];
        }
    }
}
```
and jbmc aborts with an invariant failure. This needs to be addressed before it can be merged.

2019-01-31 14:41 UTC, tautschnig commented
Just noting that this test also fails with current develop (and would likely be fixed by #2068). We'll work on narrowing this down a bit further.

2019-01-31 20:39 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 794d0e93387eca1df573405d56519c372f5a0ce1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99337131

2019-02-04 15:03 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: fe3aad48855247ba0d0484aad78565334077602b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99637451

2019-02-05 00:07 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: f5e5d3e38b23279183bb2e0b4a9eb7220d98254d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99708343

2019-02-07 14:21 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3600644dd04ad3d3cdb3597a8d413370a2c9b66a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100086630

2019-02-14 19:33 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b9cd724d165bc1b36434df719d890709344c005d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100985691

2019-03-01 13:22 UTC, romainbrenguier commented
I updated the manual bump and it failed but less badly than before. @tautschnig maybe you can rebase this PR, it will make it easier to see if there is something wrong.

2019-03-01 14:01 UTC, tautschnig commented
@romainbrenguier Rebased - thank you very much for your help, please let me know if there is anything I could do to make debugging any easier for you!

2019-03-01 15:22 UTC, tautschnig commented
@romainbrenguier Updated again as one test now "failed," because it had become trivial. Checked in with @smowton about that and it seems ok for the test to be trivial.

2019-03-01 16:25 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bfb3fa4f26b885ce8fb91f85c2d68de028764752).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/102836965

2019-03-04 18:47 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 1dfd196522d60d7b27528bb419f3b312d6e04b1b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103082443
Status will be re-evaluated on next push.
Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

  - the compatibility was already broken by an earlier merge.

2019-03-06 16:29 UTC, romainbrenguier commented
Sorry about making this wait. The problems I see now seem to be related to strings. In this example:
```java
public class Test {
    public String foo() {
        final int i = 10;
        final String retval = Integer.toHexString(i);
        assert(false);
        return retval; 
    }
}
```
running `jbmc Test.class --function Test.foo --trace` used to give a trace in which we had:
```
State 30 function java.lang.Integer.toHexString() thread 0
----------------------------------------------------
  dynamic_object1={ 'a' } ({ 00000000 01100001 })
```

but with these changes, it is replaced by:
```
State 30 function java.lang.Integer.toHexString() thread 0
----------------------------------------------------
  dynamic_object1=dynamic_object1#2 (?)
```

2019-03-12 10:06 UTC, tautschnig commented
@romainbrenguier I have now tracked down the problem and have added a second commit that addresses it, including the test that you provided. Would you be able to take another look that fully addresses the problem in your tests? Thanks!

2019-03-12 11:41 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4d0f07367c2d7c1c752b196226666e6fef5546c4).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/104052645

2019-03-12 13:33 UTC, romainbrenguier commented
I don't remember if I sent a similar example before, but here is a test for `jbmc` which was passing before, but fails on this branch:
```java
class BitSet {
    boolean bits[];
    public BitSet()
    {
        int size = org.cprover.CProver.nondetInt();
        org.cprover.CProver.assume(size >= 0);
        bits = new boolean[size];
    }
    public void set(int i)
    {
        org.cprover.CProver.assume(i < bits.length);
        bits[i] = true;
    }
    public boolean get(int i)
    {
        if(i < bits.length)
            return bits[i];
        return false;
    }
    public void andNot(BitSet other)
    {
        for (int i = 0; i < bits.length; i++) {
            bits[i] = bits[i] && !other.get(i);
        }
    }
}

public class andNot_Pass {
    public static void main(String args[]) {
        BitSet b1 = new BitSet();
        b1.set(1);
        b1.set(2);
        BitSet b2 = new BitSet();
        b2.set(0);
        b2.set(2);
        b1.andNot(b2);
        
        assert(!b1.get(0));
    }
}
```

2019-03-25 13:20 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 69012b3ec11873a129dd299f3b336ba5e4e57f42).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105668394

2019-03-25 14:59 UTC, martin-cs approved these changes
Seems reasonable.

2019-03-26 08:27 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ef4b9bb92797f45b1940992897a4e9d07443a22d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105797178

2019-03-26 10:19 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5caef7417670014d11cbb7ba83570c6ded43c156).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105812275

2019-03-27 11:17 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 90c4a756894fa1e17bbea30c926a3a07a0ce24f5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/105987217
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-04-04 11:57 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bcb894d960f99d6403c403b951bb954ef798177e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/107052342

2019-04-06 16:50 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 77f93e971e61c710ddab5b15bbfbe446d04a585a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/107328775
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-04-10 14:04 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0c848d6f332971ac5bf33407132077172f714389).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/107800556

2019-04-13 16:35 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 85c963cb9fc10df833b579fffd22456d45335667).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/108226898

2022-08-01 08:18 UTC, TGWDB commented
Closing due to age. If you believe this is erroneous please reopen and update the PR.

2022-08-01 08:18 UTC, closed without merging