replace incomplete compound types
diffblue/cbmc pull request #3643
Opened 2018-12-29 17:50 UTC by kroening

A key benefit will be that follow_tag will then be able to return the corresponding compound type.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2018-12-29 21:41 UTC, tautschnig requested changes
These are large changes without a commit message (plus the commit subjects don't parse for me), cpplint requests one `assert` to be replaced, and a rebase is required.

For the record: I am no longer going to review PRs containing commits without proper commit messages. Unfortunately GitHub does not support providing feedback on commit messages. The pull-request template contains a link to guidance on how to write commit messages. Should I receive a review request for a PR containing a commit violating commit-message guidance I'll reassign it to the author without comment. I am simply not willing to spend my time reverse engineering what a commit is about and why it is being proposed or why a change is the right thing to do.

2018-12-30 11:07 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ede451285b019f857aa1e23ab9be839246ce8af3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/95950633

2019-01-02 14:11 UTC, smowton approved these changes

2019-01-02 14:11 UTC, smowton commented on src/ansi-c/c_typecheck_base.cpp
> -    else if((final_old.id()==ID_incomplete_c_enum ||
Shouldn't we check the new is-incomplete flag here?

2019-01-02 14:11 UTC, smowton commented on src/ansi-c/c_typecheck_type.cpp
> +      compound_symbol.type.set(ID_incomplete, true);
Provide a setter for this on `struct_union_typet` rather than directly twiddle IDs?

2019-01-02 14:11 UTC, smowton commented on src/cpp/cpp_instantiate_template.cpp
> +  new_symbol.type = typet(ID_struct);
Use constructor? Or add a static `struct_typet::make_incomplete_struct(const irep_idt &tag)` or something?

2019-01-02 14:11 UTC, smowton commented on src/cpp/cpp_typecheck_compound_type.cpp
> +      new_type.set(ID_incomplete, true);
Use `struct_union_typet` interface?

2019-01-04 18:47 UTC, kroening commented on src/cpp/cpp_instantiate_template.cpp
> +  new_symbol.type = typet(ID_struct);
ok

2019-01-04 18:48 UTC, kroening commented on src/ansi-c/c_typecheck_type.cpp
> +      compound_symbol.type.set(ID_incomplete, true);
ok

2019-01-04 18:49 UTC, kroening commented on src/cpp/cpp_typecheck_compound_type.cpp
> +      new_type.set(ID_incomplete, true);
ok

2019-01-04 21:15 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0df2c3611d072c7d98092171d853f2e319ca2596).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96342190

2019-01-08 11:55 UTC, tautschnig approved these changes
@kroening Thank you very much for the elaborate commit messages, these are very helpful!

2019-01-08 12:21 UTC, chrisr-diffblue approved these changes

2019-01-08 13:15 UTC, merged

2019-01-08 13:40 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4e031ff33dcdc08a9ed2cba08d2dafd40cfee0cf).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/96604942