Maintain nondet and dynamic counters across symex instances
diffblue/cbmc pull request #3959
Opened 2019-01-26 22:32 UTC by tautschnig

- [x] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-01-27 11:26 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 93ac08fd38367341d8082a744ca8efd1202233d9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98729940

2019-01-28 20:05 UTC, peterschrammel approved these changes
Not for this PR, but maybe worth a performance test in future: Could `util/fresh_symbol` do the job?

2019-01-29 09:18 UTC, romainbrenguier requested changes
I'm not sure why there would be several `goto_symext` instantiations, which need to share symbols. But please don't introduce global variables.

2019-01-29 09:18 UTC, romainbrenguier commented on src/goto-symex/goto_symex.h
> +  static unsigned nondet_count;
:-1:

2019-01-29 09:22 UTC, tautschnig commented
> I'm not sure why there would be several `goto_symext` instantiations, which need to share symbols. 

cbmc --paths (`path_explorert`) creates a new `goto_symext` instance for each path.

> But please don't introduce global variables.

Ack, but that's just the first commit here, which is a clean revert of your earlier patch. The second commit fixes this. But I can probably also get away without doing that revert and just directly make the modifications done in the second commit.

2019-01-30 20:05 UTC, tautschnig commented
@romainbrenguier I have now largely redone this, avoiding any reverts.

@peterschrammel I have followed your suggestion, and that change is now no longer present in here and #3999 takes care of it instead.

2019-01-31 07:28 UTC, romainbrenguier approved these changes

2019-01-31 07:31 UTC, romainbrenguier commented
@tautschnig 
> cbmc --paths (path_explorert) creates a new goto_symext instance for each path.
> > But please don't introduce global variables.

> Ack, but that's just the first commit here, which is a clean revert of your earlier patch. The second commit fixes this. But I can probably also get away without doing that revert and just directly make the modifications done in the second commit.

Thanks for the explanation and sorry I didn't get this was fixed in the second commit, I think it's clearer without the revert.

2019-01-31 07:54 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 321402d3247b79f63b9ed7e717c98d8229a45cf9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99235044

2019-01-31 08:11 UTC, merged