enable .clang-format-ignore
diffblue/cbmc pull request #3963
Opened 2019-01-27 14:20 UTC by kroening

We do have files that are imported as a whole, and clang-formatting them is
a distraction.  The requirement to add // clang-format-off to external files
makes imports via scripts more difficult.

This tweaks the build script to exclude files given in .clang-format-ignore
from git-clang-format.  The same naming convention is used by other
projects.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-01-27 14:26 UTC, smowton approved these changes

2019-01-27 14:47 UTC, tautschnig requested changes
This seems like a great idea that should help us quite a bit, but the implementation is simple enough that I expect to be able to understand it -- which I currently don't, see comment below.

2019-01-27 14:47 UTC, tautschnig commented on .travis.yml
> +        git-clang-format-7 --binary clang-format-7 "${TRAVIS_BRANCH}" -- $EXCLUDES
My `git-clang-format-6.0 --help` output suggests that listing file names after `--` would mean that _only_ those files are checked. Has this changed in `git-clang-format-7`? But then there's the `(top,exclude)` magic being added, where is that documented?

2019-01-27 14:47 UTC, tautschnig commented on .travis.yml
> +        git diff -- > formatted.diff
Why is the additional `--` necessary?

2019-01-27 15:07 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 91971293e289a1b175e8346e243fa268634073a5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98735692
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-27 15:12 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 25e5084011828999d2f5d17d76354a1b87664a93).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98735820
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-27 15:20 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c7e7cb965307500257ff958db3f34f3d44c1b9ed).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98736157

2019-01-27 16:28 UTC, kroening commented on .travis.yml
> +        git-clang-format-7 --binary clang-format-7 "${TRAVIS_BRANCH}" -- $EXCLUDES
Look for the `pathspec` entry in https://git-scm.com/docs/gitglossary

2019-01-27 16:29 UTC, kroening commented on .travis.yml
> +        git diff -- > formatted.diff
Not at all, removed.

2019-01-27 16:43 UTC, tautschnig commented on .travis.yml
> +        git-clang-format-7 --binary clang-format-7 "${TRAVIS_BRANCH}" -- $EXCLUDES
Thanks!

2019-01-27 16:43 UTC, tautschnig approved these changes

2019-01-27 17:19 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 2ece5f0bf916686ac1a0fcfa7d0c91ebab49387d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98740066

2019-01-28 10:54 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 8edc5049cd4300572ee2f981e09fb0b16d6a46eb).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98791193

2019-01-28 20:21 UTC, peterschrammel approved these changes

2019-01-28 23:09 UTC, merged