Additional goto-symex documentation
diffblue/cbmc pull request #3975
Opened 2019-01-28 12:40 UTC by JohnDumbell

Added some comments around areas in symex where it wasn't immediately obvious from a relative newcomer to the code about what precisely they did and why it was important (I was the newcomer in this situation). The field rename touches quite a bit of code, but there's nothing in there beside the rename and required clang-format changes.

Feel free to mention if there's another important area that I should try and document, as I mostly focused on areas that would've been useful to me when I originally started looking around.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-01-28 13:06 UTC, tautschnig approved these changes
Looks good except for the "loop id" part. It may also be worth linking to the documentation that @johanneskloos has put together about symbolic execution, where the SSA renaming is already being explained (doc/architectural/background-concepts.md).

2019-01-28 13:06 UTC, tautschnig commented on src/goto-symex/goto_symex_state.h
> +  // symex variable can be on. L0 relates to thread ID, L1 relates to loop ID,
No, L1 is the frame id (the number of times a function has been called).

2019-01-28 13:06 UTC, tautschnig commented on src/goto-symex/goto_symex_state.h
> +  // If looking at the VCC they are shown as !{threadID}@{loopID}#{generationID}
s/loopID/frameID/

2019-01-28 14:54 UTC, martin-cs reviewed
Patch 1, the comment changes, are good and I would support.  Patch 2, s/pc/program_counter/ TBH I'm not sure it is worth the churn.  Would a comment / description where it is declared suffice?  I'm not sure that there are many people who know what a program counter is but don't know that it is often abbreviated to PC.

2019-01-28 15:41 UTC, JohnDumbell commented
It helps in reading the code if you don't know the terminology but are relatively comfortable in how code like this should work. Just reading 'pc' as you scan a method gives very little information, but 'program_counter' combined with it being an iterator gives a few solid guesses about what it's doing without going any deeper.

This may be a niche situation though, and once you know the abbreviation you're all good anyway. I have no strong opinions either way - I just felt it helped clarity.

2019-01-28 16:20 UTC, smowton commented on src/analyses/dirty.h
> +/// escape their local scope and are also considered shared state in the
Nitpick: usually "escape" would mean live longer than the scope, which isn't true here -- they just might be accessed indirectly and/or by callees

2019-01-28 16:38 UTC, smowton approved these changes
Some nitpickery otherwise lgtm

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +/// reference and then merged again once it reaches a control-flow graph
Mention the name of the merge function

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +  // been worked out to only have one viable value.
viable -> possible

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +  // L1. Actual integer literals (for example) aren't symbols, and so aren't
I'd drop the mention of integer literals, it adds more confusion than it removes imo

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +  ///     L2. Applies a suffix giving the latest generation of this variable.
strike "latest" (writes are always to the latest / fresh generation, but reads can be from past generations, especially in phi nodes)

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +  /// instance of x (L1 renaming), and the most recent write to x (L2 renaming).
Give an example, `x -> x!threadno@loopno#generation` or similar

2019-01-28 16:38 UTC, smowton commented on src/goto-symex/goto_symex_state.h
> +  /// goto_symex_statet at a control-flow fork and then back into it (at some
back into it at a control-flow merge

Strike "and not the other way around," since we've just said state goes into it *and* out of it

2019-01-28 17:28 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: a16bf207f2fb14689a6e5b2759430f988cdf0bd9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98846560
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-28 19:17 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 956d240582f0b3503ee22d8ba50809ef700e8331).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98858825
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-28 20:17 UTC, peterschrammel requested changes
Please separate the `pc` renaming into another PR - that's a breaking change.

2019-01-29 10:52 UTC, JohnDumbell commented
@peterschrammel Done.

2019-01-29 13:11 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: c352c9045ec3425b74fb254b3d6b9ce7f61733d9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98957513
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-29 16:01 UTC, allredj reviewed
:no_entry_sign:
This PR failed Diffblue compatibility checks (cbmc commit: 663f6e3bdb98a82ac57dd90604e410e015341845).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/98983334
Status will be re-evaluated on next push.
Please contact @peterschrammel, @thk123, or @allredj for support.

Common spurious failures:
  - the cbmc commit has disappeared in the mean time (e.g. in a force-push)
  - the author is not in the list of contributors (e.g. first-time contributors).

The incompatibility may have been introduced by an earlier PR. In that case merging this
PR should be avoided unless it fixes the current incompatibility.

2019-01-30 16:26 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: dd518a9ee891265be324ab8e90edaa5882d739e5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99143224

2019-02-01 10:46 UTC, peterschrammel approved these changes

2019-02-01 18:31 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 20a84fb5f42a6bd8fd0495c0d4eade8e7e693361).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/99462351

2019-02-02 17:29 UTC, merged