Use make x2
diffblue/cbmc pull request #4001
Opened 2019-01-31 08:52 UTC by kroening

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-01-31 09:13 UTC, tautschnig requested changes
"added goto_programt::insert_X(t, i) variants" is incomprehensible.

2019-01-31 10:29 UTC, smowton approved these changes

2019-02-10 10:52 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 432ade20904a8b7fce9226e50be317f6e5a1546c).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100357517

2019-02-10 13:02 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: aa85fb25955b2a1d5809fb80cec449a9c79ea74a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/100360946

2019-02-11 07:24 UTC, tautschnig approved these changes

2019-02-11 07:25 UTC, merged