Big rewrite of smt2_conv
diffblue/cbmc pull request #4100
Opened 2019-02-05 19:06 UTC by romainbrenguier

This defines an AST class for smt2 instances, and modify convert_expr to return one of this instances.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-02-05 19:25 UTC, tautschnig commented
Why not use `irept` instead of introducing this new AST class?

2019-02-06 06:40 UTC, romainbrenguier commented
@tautschnig 
> Why not use `irept` instead of introducing this new AST class?

The original reason was type safety, so that we couldn't mix ASTs and exprt.
A harder constraints is that we want to print without using a recursive function (or a stack), which I'm not sure we can do with `irept`. I think this has caused problems in the past.

2019-02-06 06:55 UTC, tautschnig commented
I had expected some collection of classes that would do actual typed AST nodes, but it seems this is just another string-based approach so I’m not particularly convinced there is added type safety?

For printing, I have not yet understood what makes this new AST class so fundamentally different- irept can happily be used without recursion, as is done in the depth iterator.

2019-02-06 14:20 UTC, romainbrenguier commented
> I had expected some collection of classes that would do actual typed AST nodes, but it seems this is just another string-based approach so I’m not particularly convinced there is added type safety?

Yes for now there are only strings and mp_integer and we don't do many checks, but we can slowly transition to stricter type checking. The idea would be to avoid direct calls to smt2_node and instead used typed functions like `smt2_extract`, `smt2_bv`, etc

> For printing, I have not yet understood what makes this new AST class so fundamentally different- irept can happily be used without recursion, as is done in the depth iterator.

I thought depth iterator were using a stack, but apparently it's a deque, so yes it could work.
But it seems wrong to use irept for something much more specific. It would be like using a tree to encode a list, or a vector to encode a pair; it's inefficient and confusing.

2019-02-06 15:53 UTC, tautschnig commented
> It would be like using a tree to encode a list, or a vector to encode a pair; it's inefficient and confusing.

Well, there are different approaches to building ASTs. One school of thought is to use dedicated classes/data types for each kind, and another approach is to have a generic representation with information held in strings (or some other sufficiently general data type). Of course the latter doesn't give you compiler-supported type checking, but it makes it much easier to extend a language.

If you would like to pursue the first approach with dedicated data types that's fine, but I just don't see how the PR achieves this at the moment. As far as I understand (and I might be wrong) the PR introduces just a new generic data type to hold AST nodes. Maybe it's in some way more efficient than `irept`, but again I don't understand where exactly that's the case.

So I'll keep fighting what currently feels like not-invented-here-syndrome until sufficient documentation, commit messages, etc. is provided to clearly describe why a new AST base class is needed, and what it characteristics/limitations are.

2019-02-06 21:19 UTC, kroening commented
BTW, for type safety, simply derive from `irept`.
Also, is there any benefit in building that AST? If the only purpose is to output it to the SMT2 solver, that could be done instead of building.

2019-02-08 15:42 UTC, romainbrenguier commented
@kroening 
> Also, is there any benefit in building that AST? If the only purpose is to output it to the SMT2 solver, that could be done instead of building.

The goal is to separate conversion from printing. The immediate benefit is the syntax correctness is easier to check (in particular we don't have to worry about unmatched parenthesis)  and the code should be clearer. Ultimately we could pass the AST directly to the smt solver without having to print it and then parse it back. 

@tautschnig 
I get your point about not having two data structures for the same thing. I see a couple of issues with irept but it can be worked around. I will try something in that direction.

2019-03-06 16:34 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 2862c2b7891fa6b0a6771c90d0f748aa1a16f4bd).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103395150

2019-03-06 16:53 UTC, romainbrenguier commented
@tautschnig @peterschrammel I refactored the branch to use `non_sharing_treet` so that we reuse existing tree structures (and add a bit more type-safety compared to using irept). This should be ready for review.

2019-03-06 18:09 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 606f67c9ca5cacf59b95600f683fc40f8777b1a6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/103410424

2019-03-07 07:40 UTC, romainbrenguier commented
@kroening I made sure the print function does not use recursion because you mentioned stack overflows of smt2_conv in the past, do you have tests for that?

2019-03-11 15:47 UTC, peterschrammel commented
I don't see any advantage of this approach over building `smt2_expr`s based on `irept`.
I'd also include the top-level commands (`assert`, `declare-fun`, etc) in the structure.

2019-03-11 16:02 UTC, romainbrenguier commented
@peterschrammel 
> I don't see any advantage of this approach over building smt2_exprs based on irept.

The advantages are we cannot inadvertently insert an `exprt` in an smt2_ast because they are seperate type, so we gain a bit of type safety, and we do not have to use sharing when we wouldn't use it. And I don't see what advantage using `irept` would have. 

> I'd also include the top-level commands (assert, declare-fun, etc) in the structure.

Yes but this could come later. I was focusing on the expression conversion in this PR. Once we agreed on the basic structure, it can be extended to commands

2019-03-20 07:29 UTC, romainbrenguier commented
@peterschrammel this is still failing some tests but can you quickly check this looks more like what you wanted?

2019-03-21 21:02 UTC, martin-cs requested changes
I'm with @tautschnig and @peterschrammel on this one; we don't need another tree data structure.  I see your point about not mixing with them with `exprt`s but I don't think this is really a problem we have ever had.  They are also largely semantically compatible (and where they aren't, it probably wouldn't be a bad thing to be more compatible).  There used to be `irept` <-> SExpression parsing and printing, with that, a visit and maybe a single rewrite pass this could all be way simpler.

2019-03-22 10:54 UTC, romainbrenguier commented
@martin-cs 
> I'm with @tautschnig and @peterschrammel on this one; we don't need another tree data structure.

I rewrote it so that we inherit from an existing tree data structure rather than having a new one.

> I see your point about not mixing with them with exprts but I don't think this is really a problem we have ever had. 

Not specifically for SMT but I think it's a problem we have all the time in CBMC, lot of things are `exprt`s which make it impossible to distinguish from the type what is a C expression, a Java expression,  a goto-program expression, a solver expression, etc... and makes it difficult to implement new features.

> There used to be irept <-> SExpression parsing and printing, with that, a visit and maybe a single rewrite pass this could all be way simpler.

Is this code still somewhere? Also I'm not totally sure about how to do the printing with one of the existing visitors (that's why I added a custom one)

2019-03-22 12:57 UTC, martin-cs commented
On Fri, 2019-03-22 at 03:54 -0700, Romain Brenguier wrote:
> @martin-cs 
> > I'm with @tautschnig and @peterschrammel on this one; we don't need
> > another tree data structure.
> 
> I rewrote it so that we inherit from an existing tree data structure
> rather than having a new one.

exprt is fine though.


> > I see your point about not mixing with them with exprts but I don't
> > think this is really a problem we have ever had. 
> 
> Not specifically for SMT but I think it's a problem we have all the
> time in CBMC, lot of things are `exprt`s which make it impossible to
> distinguish from the type what is a C expression, a Java
> expression,  a goto-program expression, a solver expression, etc...
> and makes it difficult to implement new features.

These are not different things.  The I/O functions should put things
into a standard syntax / semantics, which is exprt.  This is a
deliberate design feature.  Why do you need to be able to distinguish
them?  I feel I am missing a use-case here.


> > There used to be irept <-> SExpression parsing and printing, with
> > that, a visit and maybe a single rewrite pass this could all be way
> > simpler.
> 
> Is this code still somewhere? Also I'm not totally sure about how to
> do the printing with one of the existing visitors (that's why I added
> a custom one)

`util/lispirep.h`

2019-03-23 09:24 UTC, tautschnig commented
This seems to solve a problem that in theory we could have (and maybe in practice even do, but I haven't heard of any bug being discovered here). I wouldn't have considered this the top priority in the SMT back-end, but if it helps to solve some actual problems then so be it. Given that this now uses an existing data structure I'm a "don't care" on this one, no intention to block it. (But I won't be pushing it forward either, because I'm not authoritative on this code.)

2019-04-03 16:58 UTC, romainbrenguier commented
@peterschrammel I added a class for smt2 commands and made the smt2_ast use already defined `irep_idt`s. I think this is ready for review.

2019-05-17 08:57 UTC, romainbrenguier commented on src/solvers/smt2/smt2_ast.h
> +  smt2_sortt(smt2_symbolt symbol, std::vector<smt2_astt> &&parameters)
The parameters should be `smt2_sortt`s and symbol should be `smt2_identifiert`

2019-05-17 08:59 UTC, romainbrenguier commented on src/solvers/smt2/smt2_ast.h
> +    : smt2_astt(smt2_identifiert{smt2_symbolt(symbol), std::move(parameters)})
there shouldn't be a need for this constructor if the one above is made to take a `smt2_identifiert`

2019-05-17 10:06 UTC, romainbrenguier commented on src/solvers/smt2/smt2_command.h
> +class smt2_commandt final : public smt2_command_or_commentt
Reference the SMT-LIB standard http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r10.12.21.pdf

2019-05-17 10:23 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 9dd2ff405a38e143b1989bc5691ded4c614b62c3).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/112202263

2019-06-07 09:00 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4ddd58fd11ce7d490991249e44b26f2113ac24d9).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114702452

2019-06-24 11:47 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 84b0a90d9d156fe217a22200fa3d37602cc68e5e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/116629722

2021-09-15 09:07 UTC, TGWDB commented
Closing as this is now out of date and being done in another series of PRs, for details see #6134

2021-09-15 09:07 UTC, closed without merging