C/JBMC: support distinguishing recursion from loop unwinding
diffblue/cbmc pull request #4617
Opened 2019-05-03 16:30 UTC by smowton

Specifying --unwind-loops and --unwind-recursion allows us to distinguish the two cases.

2019-05-07 11:30 UTC, hannes-steffenhagen-diffblue commented on src/goto-instrument/unwindset.cpp
> +  bool is_iteration) const
Please don't use a boolean flag for this, they have too many overloaded meanings already. Either pass in the applicable global limit directly (+ possibly refactor this into `get_loop_limit` and `get_recursion_limit`?) or use an enum like

```
enum class unwind_kindt { loop, recursion };
```

2019-05-07 11:30 UTC, hannes-steffenhagen-diffblue commented on src/goto-checker/bmc_util.h
> +  "(unwind-recursion):" \
These should be documented in the user facing documentation (i.e. help message and cprover-manual).

2019-05-07 12:26 UTC, tautschnig requested changes
From a purely technical point of view this change looks fine. But still there are two blockers for me here which are all about the user interface (at different levels):
1) All user-facing documentation needs to be updated. Any place where we talk about unwinding needs to have this change reflected. Loop (and recursion) unwinding is probably the single most used command-line option. 
2) I'm missing the "why do we want this" explanation. This change is nicely done so that it doesn't break existing set-ups, but it still makes the command-line interface a bit bigger. It may actually make things easier (because it's not as implicit as `--unwind` is), but raises questions about the interaction between those options (which needs to be document) and also whether we should have the same refinement for `--unwindset`, `--partial-loops`, `--unwinding-asseritions`.

2019-05-07 16:27 UTC, smowton commented
Docs: will do. Why: I found it useful because in both C and Java recursion and iteration are stereotypically used quite differently (and recursion can have exponential cost if there are multiple recursive calls in a particular function or SCC-of-functions), so I found myself wanting to construct the particular `unwindset` that sets all recursion bounds shorter than the bound for loops.

2019-05-18 20:30 UTC, peterschrammel reviewed
`partial-loops` and `unwinding-assertions` could be refined as @tautschnig suggests. I don't see why `unwindset` would need any change.

2021-09-15 09:30 UTC, TGWDB commented
Closing due to age and lack of update. Please reopen if you believe this is erroneous and plan to update as discussed in the conversation (and rebase).

2021-09-15 09:30 UTC, closed without merging