Document byte_update_exprt and rename non-const functions
diffblue/cbmc pull request #4675
Opened 2019-05-20 15:26 UTC by romainbrenguier

In some cases the non-const version was unnecessarily called because it
has the same name as the const version.
This pull requests avoids that from happening in 9 cases for op, 2 for value and 3 for
offset.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [na] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [na] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-05-20 15:31 UTC, tautschnig requested changes
Renaming functions without following an appropriate deprecation path is a no-go.

2019-05-21 10:58 UTC, romainbrenguier commented
@tautschnig 
> Renaming functions without following an appropriate deprecation path is a no-go.

I've now kept both versions and deprecated the old one.

2019-05-22 13:21 UTC, tautschnig approved these changes
Looks good to me - except I'd prefer if the `set_*` methods actually took an argument as discussed.

2019-05-22 13:21 UTC, tautschnig commented on src/util/simplify_expr.cpp
> +  const byte_update_exprt &expr_const = as_const(expr);
Is this use of `as_const` actually necessary?

2019-05-22 19:11 UTC, merged