Add function that checks if function id represents a clinit.
diffblue/cbmc pull request #4706
Opened 2019-05-24 14:00 UTC by jeannielynnmoulton

A utility for checking whether the supplied function id corresponds to a
clinit.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-05-24 14:07 UTC, thomasspriggs approved these changes
Unit test, as well please. You know it makes sense :)

2019-05-24 15:11 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 7f1830eb4f1cc2f96fd1c210c58cedfe7d2c3b12).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113106427

2019-05-24 15:42 UTC, LAJW approved these changes

2019-05-24 15:42 UTC, LAJW commented on jbmc/src/java_bytecode/java_static_initializers.cpp
> +bool is_clinit_function(const irep_idt &function_id)
🚫 Function not used.

2019-05-24 16:00 UTC, smowton requested changes
Indeed, no unused code in the cbmc codebase please :)

2019-05-28 09:50 UTC, jeannielynnmoulton commented
@smowton No problem, added.

2019-05-28 09:59 UTC, smowton commented
Add to https://github.com/diffblue/cbmc/blob/develop/jbmc/unit/Makefile

2019-05-28 12:41 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c227ab5ca65bb56d2099e5b0214fed9d9b1e3af5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/113421780

2019-05-29 14:36 UTC, smowton approved these changes

2019-05-29 15:43 UTC, merged