fix constructor of string_builtin_functiont
diffblue/cbmc pull request #4744
Opened 2019-06-02 10:56 UTC by kroening

The default constructor cannot exist; marking it as `delete` re-enables
compilation with clang.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- na Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- n/a Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-06-02 11:36 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5f94d92f45ec9455510bd17321bc2a49e7599083).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114010088

2019-06-02 14:16 UTC, tautschnig requested changes
It’s still not clear to me why those aren’t caught in CI. We need to fix this while we still have a known-bad state.

2019-06-03 06:15 UTC, owen-mc-diffblue approved these changes

2019-06-03 09:38 UTC, romainbrenguier approved these changes

2019-06-04 09:43 UTC, kroening commented
I have looked into this.

clang-8 is stricter than clang-7 (but correctly so).

To catch these, we could switch the existing clang-7 build to clang-8. That will add a bit to the build time, and add some risk of that build failing, since the clang-8 binaries would need to be downloaded from apt.llvm.org

2019-06-04 10:25 UTC, tautschnig commented
I am a bit worried, because #4746 appears to be passing even though this PR hasn't been merged.

2019-06-04 13:13 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: ef1737b406cd6d7358cbb48cc4350b85d1b19d6d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/114260970

2019-06-06 12:58 UTC, tautschnig commented
I believe this has actually been merged as part of #4746 @kroening @peterschrammel ?! If so, please close this one.

2019-06-07 10:31 UTC, peterschrammel commented
yes, has been merged.

2019-06-07 10:31 UTC, closed without merging