STL Frontend: Full verification of arithmetic instructions
diffblue/cbmc pull request #4867
Opened 2019-07-02 16:01 UTC by MatWise

Adds support for comparing `Int`, `DInt` and `Real` data types. Also includes modifications to the way of how constants are being created and were they can be used in order to simplify the writing of assertions and to expand the language subset.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-07-02 17:52 UTC, pkesseli requested changes

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/converters/convert_dint_literal.cpp
> +    offset++;
`++offset;`

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/converters/convert_int_literal.cpp
> +    offset++;
`++offset;`

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +#define ROUNDING_MODE_NAME CPROVER_PREFIX "rounding_mode"
Missing documentation on all constants.

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +  rounding_mode.value = dest;
The value of `rounding_mode` should just be `rounding_val`, not a `code_blockt`.

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +  dest.add(code_labelt(CPROVER_HIDE, code_skipt()));
`CPROVER_HIDE` is only insertet once, at the top of the `__CPROVER_start` and `__CPROVER_init` function, and should not be part of the `value` of `__CPROVER_rounding_mode` or any symbol other than functions.

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/statement_list_parse_tree_io.cpp
> +        mp_integer ivalue;
The conversion of the value is duplicated. Extract to a `static` function which accepts an `std::ostream &` to only write the resulting value to the stream, e.g.:
```
out << '\t';
print(out, constant);
```

2019-07-02 17:52 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +  return to_symbol_expr(op_code.op0());
Prefer `expr_try_dynamic_cast` over `can_cast` and `to_symbol_expr`.

2019-07-02 20:26 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 3c3b7a310594caecbf7f7d35b4fae5962179b697).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/117716628

2019-07-03 11:15 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 5d8c472a12774888fc9d40de2a52b31f68478e98).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/117802606

2019-07-03 16:18 UTC, pkesseli requested changes

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +  init.value = dest;
`init.value = std::move(dest);`

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
>    init.value = dest;
Redundant, see line 99. Remove.

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +    if(pair.second.is_static_lifetime && pair.second.value.is_not_nil())
```
const symbolt &symbol = pair.second;
if(symbol.is_static_lifetime && symbol.value.is_not_nil())
  dest.add(code_assignt(symbol.symbol_expr(), symbol.value));
```

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
>      {
Omit braces if not necessary.

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_parse_tree_io.cpp
> +#include "converters/statement_list_types.h"
Empty line between `#include`s of different packages.

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_parse_tree_io.cpp
> +      else if(can_cast_expr<constant_exprt>(expr))
Prefer `expr_try_dynamic_cast` over `check-to_XXX` combination:
```
auto constant = expr_try_dynamic_cast<constant_exprt>(expr);
if(constant)
{
  out << '\t';
  output_constant(out, *constant);
}
```

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +  if(can_cast_expr<symbol_exprt>(op_code.op0()))
Prefer expr_try_dynamic_cast over check-to_XXX combination.

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +const symbol_exprt *const
The return value of this function should never be `nullptr`. Thus return a reference instead of a pointer.

2019-07-03 16:18 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +  if(!symbol)
Flip condition:
```
if(symbol)
  return *symbol;

error() << "Instruction is not followed by symbol" << eom;
throw TYPECHECK_ERROR;
```

2019-07-03 17:23 UTC, pkesseli approved these changes

2019-07-03 18:35 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: fb3328580ab43aafb2421454f066e2833340e888).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/117865814

2019-07-09 14:33 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 4625edefc3ba0c4c6128944a5c221ee0809a19f6).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118453031

2019-07-09 15:11 UTC, merged