Statement List: Return value assignment
diffblue/cbmc pull request #4890
Opened 2019-07-11 11:10 UTC by MatWise

When calling a function in STL, it's return value is present inside of the parameter assignment list as `Ret_Val`. The typecheck must search for this identifier in the assignment list. The symbol that should receive the return value can then be assigned to the `lhs` of the function call.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-07-11 12:41 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: b4e58eda254ffd7069216d49eba8abd2438ed186).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118771672

2019-07-12 11:57 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 20deb5ee1942d34306a51ff48b9fc28ce99f6a44).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/118923496

2019-07-15 15:27 UTC, pkesseli requested changes

2019-07-15 15:27 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +    if(param.get_base_name() == lhs.get_identifier())
Extract into temp before loop to avoid repeated invocation.

2019-07-15 15:27 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +    if(RET_VAL_NAME == id2string(lhs.get_identifier()))
Change `RET_VAL_NAME` to `ID_xxx` so we don't have to perform a string comparison here.

2019-07-16 17:49 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 0ad55a4055f1b591cb52c9265724a02eedef291e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119351388

2019-07-18 09:24 UTC, pkesseli approved these changes

2019-07-18 09:24 UTC, merged