STL frontend: "Main" entry point
diffblue/cbmc pull request #4915
Opened 2019-07-17 11:20 UTC by MatWise

Expands the current entry point selection by an additional check for a block with the name "Main". Note: This does not reflect the typical behaviour of the Siemens TIA portal as the main block can have any name. In order to find the 'true' main block it is necessary to parse block properties, which is not possible yet. The check for "Main" is intended to be the last resort if no entry point is specified (or if the true main block could not be resolved in the future).

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-07-17 13:28 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: c8c0f748383dbc11779d37da7cbed9466e6f7755).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119469000

2019-07-18 09:39 UTC, pkesseli requested changes

2019-07-18 09:39 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +  unsigned matches = 0u;
Replace by boolean `found`.

2019-07-18 09:39 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +static bool search_main_symbol(
Rename: `is_main_symbol_invalid`

2019-07-18 09:39 UTC, pkesseli commented on src/statement-list/statement_list_entry_point.cpp
> +  const symbolt &main_symbol = symbol_table.lookup_ref(main_symbol_name);
Don't repeat type name in the variable name (unless there is a conflict): `main`

2019-07-18 14:11 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: dee10712ba97df43b08aab5ccce9f88c787c7bb5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119640442

2019-07-18 14:48 UTC, pkesseli approved these changes

2019-07-18 14:48 UTC, merged