Statement List: Language additions for boolean instructions
diffblue/cbmc pull request #4924
Opened 2019-07-17 18:53 UTC by MatWise

This PR expands the language subset of STL. 
- Adds support for STL `X`, `XN`, `X(` and `XN(` instructions (XOR and XOR NOT).
- Enables the use of constants as function parameters.
- Fixes an issue that modified the RLO in a wrong way when a variable that contributed to the RLO was modified.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-07-17 20:45 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 397be23c5d6918cde97a0adbc963cb1ed9e8cb6d).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119539272

2019-07-18 10:12 UTC, pkesseli requested changes

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_parse_tree_io.cpp
> +/// \param [out] out: Stream that should receive the result.
Call such streams `os` and `is` respectively.

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +void statement_list_typecheckt::typecheck_statement_list_xor_not(
These two functions are highly redundant. Extract `static` function invoked from both of them, and perhaps only pass a `bool negate`:
```
  const exprt op{typecheck_identifier(tia_element, sym.get_identifier())};
  const not_exprt not_op{op};
  const exprt &arg = negate ? not_op : op;
```

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +void statement_list_typecheckt::typecheck_statement_list_nested_xor_not(
This is an exact copy of `typecheck_statement_list_nested_xor`.

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +    exprt assigned_operand;
Exactly the same code as above, except for assumptions vs. assertions. Either extract to `static` function or handle them in the same branch, and only differentiate once you instantiate either `code_assertt` or `code_assumptiont`.

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +    const exprt &arg{
Remove reference, `typecheck_function_call_arguments` returns by value.

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
>      args.push_back(arg);
Why even have that temporary variable? Just:
```
args.emplace_back(typecheck_function_call_arguments(...));
```

2019-07-18 10:12 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +      // Is constant_exprt.
Is that meant to mark the `else` case? Then:
```
else // constant_exprt.
```

2019-07-19 14:48 UTC, pkesseli requested changes

2019-07-19 14:48 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +    symbol_table.get_writeable_ref(CPROVER_TEMP_RLO).symbol_expr()};
No mutable reference needed: `symbol_table.lookup_ref(CPROVER_TEMP_RLO).symbol_exor()}`

2019-07-19 14:48 UTC, pkesseli commented on src/statement-list/statement_list_typecheck.cpp
> +  rlo_bit = temp_rlo;
```
rlo_bit = std::move(temp_rlo);
```

2019-07-19 15:17 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 2a66edf1fdc04a5a44a390ce4e1e013ba6fa559f).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119811122
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-07-19 15:45 UTC, pkesseli approved these changes

2019-07-19 15:58 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: e01c4b53ec872ec7daa21c3d230acb5396c4077e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/119817074

2019-07-19 16:18 UTC, merged