fix exprt::opX accesses in analyses
diffblue/cbmc pull request #4963
Opened 2019-07-30 11:43 UTC by kroening

This improves type safety.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-07-30 12:24 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 6b031078c03bc945ca98855c48daeec036046385).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121242609

2019-07-30 13:22 UTC, owen-mc-diffblue requested changes

2019-07-30 13:22 UTC, owen-jones-diffblue commented on src/analyses/local_may_alias.cpp
> +    const auto &op0 = to_minus_expr(rhs);
```suggestion
    const auto &op0 = to_minus_expr(rhs).op0();
```

2019-07-31 15:01 UTC, owen-mc-diffblue approved these changes

2019-07-31 15:35 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 458c3c2a416dc93f331ebc4bc3f6521931ecdb5a).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/121437877
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-08-04 07:19 UTC, merged