Remove symbol_module_map from `symbol_tablet`
diffblue/cbmc pull request #5148
Opened 2019-10-04 11:46 UTC by thomasspriggs

The `symbol_module_map` is not referenced from outside of the symbol
table. It is only read from inside the symbol table for consistency
checking purposes. Therefore the `symbol_module_map` and all code
referring to it can be removed resulting in less code to maintain.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-10-04 13:05 UTC, smowton requested changes
Believe this is used in derivative products such as the Verilog frontend (EBMC?), blocking until we know otherwise (@kroening ?)

2019-10-04 13:05 UTC, chrisr-diffblue commented
@xbauch - Any thoughts?

2019-10-04 13:39 UTC, thomasspriggs commented
My motivation for making this change is that in the case where all symbols have the same module, then `symbol_tablet::erase` has to effectively iterate over the entire symbol table in order to find the particular entry to erase. This then caused a performance problem in my use case. If there is however a motivation for keeping this otherwise unused data structure, then I can investigate alternative solutions.

2019-10-04 13:40 UTC, chrisr-diffblue commented
@martin-cs might also have some thoughts on the history/uses of this data structure.

2019-10-04 13:41 UTC, xbauch commented
@thomasspriggs I confirm that `ebmc` uses that map.

2019-10-04 14:02 UTC, thomasspriggs commented
@xbauch If I were to make an alternative change which prevented adding symbols to the module map in the case where the symbol's module was empty, would that be compatible with the existing ebmc code base?

2019-10-04 14:17 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: bbb8f9bfd27c95a3b5d39763ef84f4fe9065fee5).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/130421593

2019-10-04 14:28 UTC, xbauch commented
> @xbauch If I were to make an alternative change which prevented adding symbols to the module map in the case where the symbol's module was empty, would that be compatible with the existing ebmc code base?

It seems that `ebmc` only every iterates over the module-map using some identifier so symbols without a module wouldn't be found anyway.

2019-10-07 09:05 UTC, thomasspriggs commented
Given that this is used in EBMC, I am going to close out this PR, rather than making extra work for ebmc maintainers.

2019-10-07 09:05 UTC, closed without merging

2019-10-08 08:59 UTC, thk123 commented
@xbauch doesn't need to be done now, but longer term, ebmc derive from `symbol_table_baset` and add this field itself, or is there some technical reason this wouldn't' work?