Native CMake support in VisualStudio
diffblue/cbmc pull request #5162
Opened 2019-10-13 00:27 UTC by LAJW

These changes let you compile and run this project using [VisualStudio's native CMake support](https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/).

To achieve this, I dropped the dependency on Cygwin, and only require git bash (which you're bound to have if you're using git) and the chocolatey `winflexbison3` package (chocolatey is already used/preinstalled on CI).

Tested on VS2019 community edition, developer experience is much better than manually generating projects with CMake - it uses Ninja by default, which uses multi core compilation, unlike manually generated CMake projects.

Setup on VS with this PR boils down to two steps:

 - `choco install winflexbison3`
 - File -> Open -> CMake -> CBMC

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [n/a] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [n/a] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [n/a] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [n/a] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2019-10-14 08:45 UTC, smowton approved these changes

2019-10-14 08:46 UTC, smowton commented
Oh actually, question: since at the moment we require VS 2015+, does this degrade the experience on VS2015 or 2017?

2019-10-14 10:04 UTC, LAJW commented
@smowton, nope, you still can configure cmake the old way (and with less dependencies). This is just adding cmake native as an option (which is available even in 2017). The only downside is you need to have git.

2019-10-14 10:25 UTC, chrisr-diffblue requested changes
The CMake changes look OK to me - might also be worth @hannes-steffenhagen-diffblue taking a look at those too. One thing I am a bit concerned about is that, if I'm reading this PR correctly, you've switched the CI builds from Makefile based builds to CMake based builds, yes? We have end users that depend on Windows *Makefile* based builds, so I would like to see those builds still exercised in CI somewhere so that they don't bit rot... Unless @peterschrammel is happy for CI to change if he thinks the users I have in mind might be willing to change their build system?

2019-10-14 10:34 UTC, LAJW commented
@chrisr-diffblue Fair enough, I'm not particularly attached to CI changes. I just wanted to try to see them work on CI. Removed.

2019-10-14 10:38 UTC, chrisr-diffblue approved these changes
Thanks @LAJW - the other option would be to liaise with Peter S about potentially adding a second Windows CI build, so that both the CMake and Make based builds get exercised in CI.

2019-10-14 10:40 UTC, chrisr-diffblue commented
Oh, and one other thought (sorry! :-) ) - I believe the Windows Makefile builds use CLCACHE - do the CMake based builds do the same?

2019-10-14 10:49 UTC, LAJW commented
@chrisr-diffblue That was the intent in the CI changes. We're gonna have to make it work for test-gen too, so it'll come around. Outside of that you can use whichever generator you want.

2019-10-15 17:33 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: ecce25fbc8fbc2104df7e62d121b7655f6995910).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132017019
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-10-16 10:29 UTC, LAJW commented
fixup - I misunderstood how ansi_c_library_sources file was created

2019-10-16 14:53 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 676cb0beeefb38823b3172b0d63b37ba9095fde2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132178299
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-10-16 15:22 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 77076056e6c544caca62f03dc6c188d2b550b68e).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132184613

2019-10-17 12:07 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 85d15a5b5ed074d2d81edd0e9972471f6684fc7b).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132325446

2019-10-17 12:26 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 069c761dd5b43c13554d31db09348916f65b9c47).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132328171

2019-10-17 15:22 UTC, LAJW commented
@peterschrammel windows/cmake codebuild added (with ninja and clcache)!

2019-10-17 15:32 UTC, peterschrammel approved these changes

2019-10-17 15:34 UTC, peterschrammel commented
@kroening, @tautschnig, this is ready to go.

2019-10-17 16:19 UTC, allredj reviewed
:warning:
This PR failed Diffblue compatibility checks (cbmc commit: 1cf005682a78b98152819261682cd74ead77fad1).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132386896
Status will be re-evaluated on next push.
Common spurious failures include: the cbmc commit has disappeared in the mean time (e.g. in a force-push); the author is not in the list of contributors (e.g. first-time contributors); compatibility was already broken by an earlier merge.

2019-10-17 18:48 UTC, allredj reviewed
:heavy_check_mark:
Passed Diffblue compatibility checks (cbmc commit: 519a802a1e02ea6dc95b086f926d881c72bbdaa2).
Build URL: https://travis-ci.com/diffblue/test-gen/builds/132408233

2019-10-18 20:55 UTC, tautschnig approved these changes

2019-10-18 20:55 UTC, merged