Allow file-local symbol mangling for multi-file compilation
diffblue/cbmc pull request #5353
Opened 2020-05-21 16:35 UTC by azcwagner

Addresing issue https://github.com/diffblue/cbmc/issues/4689, this makes the goto-cc utility mangle exported function symbols when multiple files are compiled and linked in a single run of goto-cc, as it does when files are compiled separately.

A compile-and-link argument has also been added to chain.sh under regression/goto-cc-file-local to test this compilation scenario.

2020-05-21 18:33 UTC, karkhaz requested changes
Thanks for this! I'm not sure why the CodeBuild job is failing, but please address my comment and force-push. If that still doesn't make CodeBuild happy, we'll ask diffblue for the CodeBuild log.

2020-05-21 18:33 UTC, karkhaz commented on regression/goto-cc-file-local/chain.sh
> +          /Fo"${OUT_FILE}"
I believe this should be `/Fe` rather than `/Fo`, since we're compiling and linking at the same time

2020-05-21 18:35 UTC, karkhaz commented
Also, when you force-push, could you please use the phrase "fixes #4689" in the commit message? That will autoclose that issue as soon as this PR gets merged.

2020-05-22 12:59 UTC, karkhaz commented
@tautschnig @chrisr-diffblue do you have any insight about why the Windows CodeBuild job is hanging? This was pushed yesterday, all the other jobs have finished

2020-05-22 13:01 UTC, karkhaz approved these changes

2020-05-22 13:04 UTC, chrisr-diffblue commented
@karkhaz Sadly, no - it looks like the windows job never even got started. Probably the best thing to do would be a rebase+force push to trigger a new CI run.

2020-05-22 15:14 UTC, karkhaz commented
Looks like this is ready for review, all checks have passed!

2020-06-05 18:46 UTC, chrisr-diffblue approved these changes
Thanks for this (and apologies for the long delayed review). LGTM!

2020-06-05 22:06 UTC, merged