xen-cbmc: fix ci script
diffblue/cbmc pull request #5508
Opened 2020-09-29 13:41 UTC by nmanthey

This script has been broken, and not been picked up in CI until now.

This change fixes the script, as well as makes sure that the relevant
steps are executed, and the resulting build artefacts have the required
goto-cc section in them.

This CI script has been refered to as part of the paper:
"Using model checking tools to triage the severity of security bugs in
the Xen hypervisor", that has been presented at FMCAD 2020.

Signed-off-by: Norbert Manthey <nmanthey@amazon.de>

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2020-09-29 13:47 UTC, kroening approved these changes

2020-09-29 14:25 UTC, NlightNFotis requested changes
Thanks for the fix! I would say it's much needed 👍 

May I ask why the file was renamed from `.yml` to `.yaml`? This has the unfortunate side effect of breaking file revision history, which makes it hard to detect what the actual change here is (the one that actually fixed the broken CI issue).

2020-09-29 15:02 UTC, hannes-steffenhagen-diffblue commented on .github/workflows/build-and-test-Xen.yaml
> +        run: one-line-scan/one-line-scan --add-to-path $(pwd)/src/cbmc --add-to-path $(pwd)/src/goto-diff --add-to-path $(pwd)/src/goto-cc --no-analysis --trunc-existing --extra-cflags -Wno-error -o
Could you split this over multiple lines? This is a bit hard to read.

2020-09-29 15:17 UTC, martin-cs approved these changes
Does this mean I will stop getting e-mails saying "Run failed: Build and Test Xen" whenever I push to a PR?

2020-09-30 13:03 UTC, nmanthey commented on .github/workflows/build-and-test-Xen.yaml
> +        run: one-line-scan/one-line-scan --add-to-path $(pwd)/src/cbmc --add-to-path $(pwd)/src/goto-diff --add-to-path $(pwd)/src/goto-cc --no-analysis --trunc-existing --extra-cflags -Wno-error -o
Yes, will split.

2020-09-30 13:05 UTC, nmanthey commented
> Thanks for the fix! I would say it's much needed +1
> 
> May I ask why the file was renamed from `.yml` to `.yaml`? This has the unfortunate side effect of breaking file revision history, which makes it hard to detect what the actual change here is (the one that actually fixed the broken CI issue).

I will split the commit into (1) file rename, and (2) actual diff. The rename is basically for consistency.

Yes, I can split that over multiple lines.

Yes, this fix should stop those PR emails (I hope, I did not push PRs recently ;) )

2020-09-30 13:28 UTC, NlightNFotis approved these changes
Thanks for the explanation. 

Good to go from me 👍

2020-09-30 22:45 UTC, merged