Adds code contracts regression tests that involve function calls
diffblue/cbmc pull request #5911
Opened 2021-03-10 21:27 UTC by ArenBabikian

This PR adds regression tests for code contracts. 
7 test directories are added, for a total of 17 regression tests. They involves recursive and non-recursive function calls.

Among the 17 added tests, 7 are marked as `KNOWNBUG`, which means that they are skipped.

- 4 tests ( [03-enf](regression/contracts/function-calls-03/test-enf.desc), [03-1-enf](regression/contracts/function-calls-03-1/test-enf.desc), [04-enf](regression/contracts/function-calls-04/test-enf.desc), [04-1-enf](regression/contracts/function-calls-04-1/test-enf.desc) ) require unwinfing in `chain.sh`, which is not currently handled
- 7 tests ( [02-enf](regression/contracts/function-calls-02/test-enf.desc), [02-1-enf](regression/contracts/function-calls-02-1/test-enf.desc), [03-enf](regression/contracts/function-calls-03/test-enf.desc), [03-1-enf](regression/contracts/function-calls-03-1/test-enf.desc), [04-enf](regression/contracts/function-calls-04/test-enf.desc), [04-mix-2](regression/contracts/function-calls-04/test-mix-2.desc), [04-1-enf](regression/contracts/function-calls-04-1/test-enf.desc) ) have an issue that is solved by #5538 
---------
- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [x] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [x] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2021-03-11 17:33 UTC, feliperodri requested changes

2021-03-11 17:33 UTC, feliperodri commented on regression/contracts/function-calls-01/test-enf.desc
> +This confirms the accuracy of the postconditions.
Could you elaborate a bit more? What do you mean by accuracy? For this test, we want to check the behavior of pre- and post-conditions using the `--enforce-all-contracts`, correct? In that case, we assume `requires` and assert `ensures`. It'd be helpful to document that here too. The same apply to all test descriptions.

2021-03-11 17:33 UTC, feliperodri commented on regression/contracts/function-calls-02-1/test-enf.desc
> +This bug is fixed in PR #5538.
You don't need to add this here.

2021-03-11 17:33 UTC, feliperodri commented on regression/contracts/function-calls-02/test-enf.desc
> +This bug is fixed in PR #5538.
No need to add the PR here, the same goes for all other test descriptions.

2021-03-11 17:33 UTC, feliperodri commented on regression/contracts/function-calls-03-1/test-enf.desc
> +This test requires the "--unwind 20 --unwinding-assertions" flag for the cbmc call in "chain.sh", which is currently not handled.
Didn't you find a way to update `chan.sh` to handle parameters for CBMC call as well?

2021-03-11 19:03 UTC, feliperodri approved these changes
LGTM.

2021-03-17 23:26 UTC, NlightNFotis approved these changes
LGTM.

Is there any plan to revisit the `KNOWNBUG` issues in the future and repair them?

2021-03-18 14:54 UTC, ArenBabikian commented
> LGTM.
> 
> Is there any plan to revisit the `KNOWNBUG` issues in the future and repair them?

Yes! once #5538 is merged, I will assess the `KNOWNBUG`s.

2021-03-18 18:26 UTC, merged