Fix Cywin make build
diffblue/cbmc pull request #6048
Opened 2021-04-22 17:53 UTC by TGWDB

This fixes various details to ensure that make under Cywin can build
cbmc.

This is just some small fixes that appear to stop `cbmc` from being built using `make` and Cygwin.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2021-04-22 20:00 UTC, tautschnig requested changes
I'd prefer some more clarity in the commit message, and the failing Visual Studio builds suggest that these "small changes" aren't that small at all (the changes to `run.cpp` seem quite wrong, actually).

2021-04-22 20:00 UTC, tautschnig commented on src/util/run.cpp
> +#ifndef _WIN32
This change doesn't look like "just a small change" at all?

2021-04-23 08:23 UTC, TGWDB commented
> I'd prefer some more clarity in the commit message, and the failing Visual Studio builds suggest that these "small changes" aren't that small at all (the changes to `run.cpp` seem quite wrong, actually).

I'll comment directly here, then update the commit message(s) at the end if this makes it through review.

The Windows builds are all currently failing due to some CI problem, not related to this PR (that said, I created this PR to get the results from CI, so there is a chance there could be a problem).

There are three changes here:

1. Remove the `static` linking in the Cygwin build since this causes the build to fail (this was also suggested in the `Makefile` for Cygwin anyway).
2. Update and link the missing dependencies and fix the use of `SYMBOL_INFO` that appears to have been wrong for some time and not detected/tested.
3. Change the `ifdef` statements related to Cygwin (`_WIN32`) in `run.cpp`. Note that this appears to be a large change, but the root of the change is that Cygwin build does not call the `shell_quote` function. This causes the build to fail since the `-Werror` flag makes this an error. Rather than create a dummy call to this function, I chose to simply change the `ifdef` code to not include the function. This also meant deleting code inside the function that was inside an `ifdef` for building in Cygwin.

I hope this clarifies and that CI can be fixed and a proper CI test done.

2021-04-23 11:36 UTC, tautschnig commented
> > I'd prefer some more clarity in the commit message, and the failing Visual Studio builds suggest that these "small changes" aren't that small at all (the changes to `run.cpp` seem quite wrong, actually).
> 
> I'll comment directly here, then update the commit message(s) at the end if this makes it through review.
> 

Thank you!

> The Windows builds are all currently failing due to some CI problem, not related to this PR (that said, I created this PR to get the results from CI, so there is a chance there could be a problem).
> 

My apologies for not digging deeper and wrongly attributing these failures to your changes!

> There are three changes here:
> 
>     1. Remove the `static` linking in the Cygwin build since this causes the build to fail (this was also suggested in the `Makefile` for Cygwin anyway).
> 

Yes, this one seemed less surprising,

>     2. Update and link the missing dependencies and fix the use of `SYMBOL_INFO` that appears to have been wrong for some time and not detected/tested.
> 

and that change looked good.

>     3. Change the `ifdef` statements related to Cygwin (`_WIN32`) in `run.cpp`. Note that this appears to be a large change, but the root of the change is that Cygwin build does not call the `shell_quote` function. This causes the build to fail since the `-Werror` flag makes this an error. Rather than create a dummy call to this function, I chose to simply change the `ifdef` code to not include the function. This also meant deleting code inside the function that was inside an `ifdef` for building in Cygwin.
> 

This one I'm still not very clear about. `_WIN32` is more than Cygwin, this is all Windows builds. I am surprised to hear that `shell_quote` wasn't being invoked at all, it seemed rather important to do the work it is doing (proper escaping). Looking at the code base you are of course right, but it seems we have another problem to solve: `shell_quote` exists twice, once in `util/` and once in `ansi-c`. These are byte-by-byte the same, so one of them ought to be removed. This might fix the problem as the function would then actually be used?

2021-04-23 14:25 UTC, tautschnig commented
@TGWDB See #6054 for the fix of Windows builds in CI.

2021-05-07 11:09 UTC, TGWDB commented
Closing this PR as it mixes different things. The fix needed for general WIN32 build is now #6091.

2021-05-07 11:09 UTC, closed without merging