Fix bool versus bitvec 1 sort mismtach for CVC4
diffblue/cbmc pull request #6205
Opened 2021-06-28 13:55 UTC by TGWDB

This fixes a sort mismatch that can occur in CVC4 where an
array of booleans is translated into an array of (_ bitvec 1)
which is then a mismatch when CVC4 expects and can handle an
Array of Bool.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2021-06-28 13:58 UTC, kroening commented
All relevant solvers support arrays of bool now -- I'll do a PR that removes the `(_ bitvec 1)` encoding.

2021-06-29 09:21 UTC, martin-cs requested changes
This seems like a work-around rather than a fix.  If you can find the code that is generating the sort mismatch then you should be able to fix this properly.

2021-07-05 10:48 UTC, TGWDB commented
@kroening @martin-cs It would be nice to approve and merge this PR to allow cvc4 to not error, regardless of future fixes to resolve the sort stuff generally as in #6206 .

2021-07-06 09:24 UTC, peterschrammel approved these changes
Let's merge this workaround, with a proper fix expected in #6206.

2021-07-06 13:59 UTC, martin-cs reviewed
I don't think this is a good idea as it is a work around.  I am not sure #6206 will fix it either as I think that is needed for MathSAT support but ... @TGWDB if you really want to do it, I won't stand in your way.

2021-07-06 14:00 UTC, martin-cs approved these changes
I don't approve but this will remove my "request changes".

2021-07-06 14:28 UTC, merged

2021-07-06 14:30 UTC, TGWDB commented
@martin-cs Thanks. This is kind of a blocking concern for AWS since it prevents many things that should work with cvc4 from progressing. I agree a proper look at the SMT2 back end and fixing details there is preferable, but this is likely to be slow and/or caught up with other changes. Let's hope a proper solution is done in future.