allow multiple loop invariants
diffblue/cbmc pull request #6214
Opened 2021-07-06 11:07 UTC by kroening

This extends the grammar to allow multiple loop invariants for one loop.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2021-07-06 13:24 UTC, martin-cs approved these changes

2021-07-06 19:25 UTC, SaswatPadhi commented
I think we should also update the side-effect check:

https://github.com/diffblue/cbmc/blob/3e0007f9ed818969185676eb96f8811dc75e8705/src/goto-programs/goto_convert.cpp#L865-L877

2021-07-06 19:28 UTC, SaswatPadhi requested changes
I think we should also update the side-effect check:

https://github.com/diffblue/cbmc/blob/3e0007f9ed818969185676eb96f8811dc75e8705/src/goto-programs/goto_convert.cpp#L865-L877

I see that the PR is now assigned to me / @feliperodri.
Should I make this change and merge the PR, @kroening?

2021-07-07 07:37 UTC, kroening commented
No need to change this code, `has_subexpr` will work as required.

2021-07-07 09:11 UTC, SaswatPadhi approved these changes
Thanks!! Indeed, it looks at the operands and would work as expected.

2021-07-07 16:24 UTC, feliperodri approved these changes
LGTM.

2021-07-07 16:42 UTC, chrisr-diffblue approved these changes

2021-07-07 16:43 UTC, merged