Relational operators support for pointers in new SMT backend
diffblue/cbmc pull request #6905
Opened 2022-06-06 09:04 UTC by NlightNFotis

This PR is adding support for relational operators as applied
to pointers in the new SMT backend.

This is pending unit tests, which are on the way.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-06-06 09:22 UTC, kroening commented on regression/cbmc-incr-smt2/pointers-relational-operators/pointers_assume.c
> +  __CPROVER_assume(x > y);
Please revise these tests -- relations on nondeterministic pointers have no meaning. You need to make those pointers point to the same object.

2022-06-06 17:10 UTC, NlightNFotis commented on regression/cbmc-incr-smt2/pointers-relational-operators/pointers_assume.c
> +  __CPROVER_assume(x > y);
Hi Daniel, do the changes in 36e09551775d53cf09b41e05cfb922df57c300c2 look like an acceptable fix to this?

2022-06-06 17:26 UTC, kroening commented on regression/cbmc-incr-smt2/pointers-relational-operators/pointers_assume.c
> +  __CPROVER_assume(x > y);
Yes, that's fine. It may confuse one or the other reader that you are using `x` both as a source of nondeterminism and as "target" for the pointers.

2022-06-07 07:48 UTC, TGWDB approved these changes

2022-06-08 17:52 UTC, thomasspriggs requested changes

2022-06-08 17:52 UTC, thomasspriggs commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +      "only pointers of the same object type can be subtracted.");
:no_entry_sign: The message in this INVARIANT refers to subtraction, but this is part of the relational operator conversion, not the subtraction.

2022-06-08 17:52 UTC, thomasspriggs commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +    // underlying type.
:no_entry_sign: There are cases where the types of pointer operand for a relational operator are different, but the result is well defined. For example -
```
#include <assert.h>

struct my_structt
{
	int x;
	char y;
};

int main()
{
	struct my_structt s;
	assert(&(s.x) < &(s.y));
}
```
The relevant part of the C(11) standard section 6.5.8 - "If the objects pointed to are members of the same aggregate object, pointers to structure members declared later compare greater than pointers to members declared earlier in the structure"

2022-06-08 17:52 UTC, thomasspriggs commented on regression/cbmc-incr-smt2/pointers-relational-operators/pointers_stack_malloc.desc
> +pointers_stack_malloc.c
:pick: Isn't `stack_malloc` a contradiction, given than malloc allocates heap memory, not stack memory?

2022-06-08 17:52 UTC, thomasspriggs commented on regression/cbmc-incr-smt2/pointers-relational-operators/pointers_stack_malloc.c
> +  int *a = malloc(sizeof(int) * 5);
:information_source: This test is pretty close to running into the unimplemented array functionality. Adding `--no-array-field-sensitivity` to cbmc will cause a failure. Also replacing the last `for` loop using a non-det range for the `i` variable will do the same -
```
#include <stdlib.h>

int main()
{
  int *a = malloc(sizeof(int) * 5);

  for(int i = 0; i < 5; i++)
    *(a + i) = i;

  int i;
  __CPROVER_assume(i >= 0);
  __CPROVER_assume(i < 5);

  {
    __CPROVER_assert(*(a + i) >= i, "*(a + i) >= i: expected successful");
    __CPROVER_assert(*(a + i) <= i, "*(a + i) <= i: expected successful");
    __CPROVER_assert(*(a + i) == i, "*(a + i) <= i: expected successful");
    __CPROVER_assert(*(a + i) != i, "*(a + i) <= i: expected failure");
  }
}
```
No need to action this comment. I just wanted to make note of my findings into why this array using example works despite the unimplemented array functionality.

2022-06-09 15:34 UTC, thomasspriggs approved these changes

2022-06-09 17:36 UTC, merged