Function pointer removal: create fall-back function call
diffblue/cbmc pull request #6987
Opened 2022-07-01 10:47 UTC by tautschnig

The case where a function pointer matches none of the candidate
functions now introduces a call to a new function. No implementation of
this function is provided, leaving the choice to the user in case they
choose to use goto-instrument's generate-function-body.

As doing so requires updates to goto_functions by the caller, two unused
API variants of remove_function_pointers were removed.

Fixes: #6983

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-08-14 19:47 UTC, martin-cs commented
Sorry to be That Person but can you split up the commit a bit?  Maybe remove the unused APIs in a separate commit?  The regression test clean ups might also be able to be separated?

2022-08-25 16:53 UTC, peterschrammel approved these changes

2022-09-01 19:35 UTC, celinval commented
Hi, I was wondering what's the status of this change: @tautschnig?

2022-09-02 13:29 UTC, martin-cs reviewed
I'm a little unsure about the test cases.  Something just feels a little bit off with the status changes.  I'm not going to block this but it'd be really good if you could look at what is going on with them.

2022-09-02 13:29 UTC, martin-cs commented on regression/cbmc/Function_Pointer18/test.desc
> +\[f2.assertion.1\] line [0-9]+ assertion 0: FAILURE
Why is this now a failure?  If I have read the right test case, there is no way `f` can be set to `f2`, so the assert in `f2` cannot be reachable?

2022-09-02 13:29 UTC, martin-cs commented on regression/cbmc/Function_Pointer18/test.desc
> +\[main.assertion.1\] line [0-9]+ assertion x == 1: FAILURE
This also doesn't make sense, why does one of these fail but not the other?

2022-09-02 13:29 UTC, martin-cs commented on regression/cbmc/Function_Pointer20/test.desc
> +^\*\*\*\* WARNING: no body for function indirect::fptr_call
I don't get why there is a warning in this context?  There is only a single thing that `fn_ptr` can point to?

2022-09-02 13:29 UTC, martin-cs commented on regression/cbmc/Function_Pointer_Init_No_Candidate/main.c
> -  //   should succeed
So there is a semantic change for cases where function pointers are invalid / `NULL` / otherwise not properly defined?

2022-09-02 13:29 UTC, martin-cs commented on regression/goto-analyzer/value-set-function-pointers-simple/test.desc
> +^fun_global_show \(\) -> value-set-begin: TOP :value-set-end
Looking at the test case this is slightly concerning as `{f, g}` is a legit and reasonable thing for it to be and it should only be set to `TOP` if something really wrong is occurring.  This looks like we might need to be a bit careful about how this PR interacts with the abstract interpreter.

2022-09-02 13:29 UTC, martin-cs commented on regression/goto-instrument/value-set-fi-fp-removal4/test.desc
> +--
Thanks!

2022-09-02 16:06 UTC, kroening requested changes
As mentioned out of band, I am unhappy with this PR as we are giving meaning to undefined behavior. Undefined behavior needs to stay that.

2022-10-08 10:42 UTC, tautschnig commented
Closing as #7011 provided a solution without (potentially) giving meaning to undefined behaviour.

2022-10-08 10:42 UTC, closed without merging