Add support for is_invalid_pointer in new SMT2 backend
diffblue/cbmc pull request #7035
Opened 2022-07-26 15:11 UTC by esteffin

Add support for `is_invalid_pointer_exprt` in new SMT2 backend allowing support for `__CPROVER_is_invalid_pointer`.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-07-26 16:12 UTC, NlightNFotis requested changes

2022-07-26 16:12 UTC, NlightNFotis commented on src/solvers/smt2_incremental/object_tracking.cpp
> +  invalid_pointer_object.unique_id = 1;
Some documentation on why this has object_id 1 would be good to have.

2022-07-26 16:12 UTC, NlightNFotis commented on src/solvers/smt2_incremental/object_tracking.cpp
> +//static decision_procedure_objectt make_invalid_pointer_object()
Can this be removed please?

2022-07-26 16:12 UTC, NlightNFotis commented on src/solvers/smt2_incremental/object_tracking.h
> +/// \brief Create the invalid pointer constant
Does the type parameter need to be documented?

2022-07-26 16:12 UTC, NlightNFotis commented on regression/cbmc-incr-smt2/pointers/pointer_object3.c
> +  int foo, bar;
Why was a `bar` declaration added here?

2022-07-26 16:12 UTC, NlightNFotis commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +  const string_constantt &string_constant,
This appears to be an error - can this be squashed into the previous commits so it doesn't create noise in the PR review?

2022-07-27 11:01 UTC, esteffin reviewed
Changed where suggested

2022-07-27 11:01 UTC, esteffin commented on regression/cbmc-incr-smt2/pointers/pointer_object3.c
> +  int foo, bar;
Leftover from other uncommited changes.
Removed

2022-07-27 11:01 UTC, esteffin commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +  const string_constantt &string_constant,
Yes, I spot the change and modified.

I will squash

2022-07-27 11:01 UTC, esteffin commented on src/solvers/smt2_incremental/object_tracking.cpp
> +  invalid_pointer_object.unique_id = 1;
Done

2022-07-27 11:01 UTC, esteffin commented on src/solvers/smt2_incremental/object_tracking.cpp
> +//static decision_procedure_objectt make_invalid_pointer_object()
Uops...
Removed

2022-07-27 11:01 UTC, esteffin commented on src/solvers/smt2_incremental/object_tracking.h
> +/// \brief Create the invalid pointer constant
As it was always called with the `void *` type (`pointer_type(void_type())`) I got rid of the parameter.

2022-07-28 09:41 UTC, NlightNFotis approved these changes
Happy for this to go in, modulo the clang format check passing.

2022-07-28 13:44 UTC, merged