Allow `ID_index` expressions in history variables
diffblue/cbmc pull request #7060
Opened 2022-08-05 23:02 UTC by SaswatPadhi

Although `ID_dereference` expressions were previously allowed within history variables, `ID_index` expressions were not. This PR adds support for `ID_index` expressions as well.

In addition, this PR also adds a compilation check for history variable parameters. Previously they were only checked during instrumentation, and bad parameters were silently accepted during compilation.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- n/a ~~The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/~~
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a ~~My commit message includes data points confirming performance improvements (if claimed).~~
- [x] My PR is restricted to a single feature or bugfix.
- n/a ~~White-space or formatting changes outside the feature-related changed lines are in commits of their own.~~

2022-08-15 20:57 UTC, martin-cs approved these changes

2022-08-16 16:27 UTC, feliperodri requested changes
@SaswatPadhi Good catch! Only a few minor questions before approval. Could you also add `CONTRACTS: ` as a prefix in the title of the PR?

2022-08-16 16:27 UTC, feliperodri commented on regression/contracts/history-index/main.c
> +#include <stdlib.h>
Why do you need `stdlib`? Perhaps, just `assert.h`.

2022-08-16 16:27 UTC, feliperodri commented on src/ansi-c/c_typecheck_expr.cpp
> +      throw 0;
Why no coverage?

2022-08-19 17:16 UTC, SaswatPadhi commented on regression/contracts/history-index/main.c
> +#include <stdlib.h>
Thanks; updated.

2022-08-19 17:16 UTC, SaswatPadhi commented on src/ansi-c/c_typecheck_expr.cpp
> +      throw 0;
Thanks; added a test to cover this.

2022-08-19 17:31 UTC, feliperodri approved these changes

2022-08-19 18:19 UTC, kroening approved these changes

2022-08-19 18:35 UTC, merged