Perform remove_returns pass before constant_propagator
diffblue/cbmc pull request #7105
Opened 2022-09-06 14:57 UTC by thomasspriggs

The constant_propagator does not handle returns and gives unexpected
results for examples including returns. Carrying out the remove_returns
pass before contant propagation should resolve this issue.

This relates to https://github.com/diffblue/cbmc/issues/7041

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-09-06 15:34 UTC, martin-cs approved these changes
Yes but really I would suggest using goto-analyzer for constant propagation:  

`goto-analyzer test --simplify test1 --vsd --vsd-value constants`

https://github.com/diffblue/cbmc/issues/7041#issuecomment-1199354287

2022-09-06 16:09 UTC, tautschnig requested changes

2022-09-06 16:09 UTC, tautschnig commented on src/goto-instrument/goto_instrument_parse_options.cpp
> +    remove_returns(goto_model);
Please use `do_remove_returns()` instead.

2022-09-06 18:32 UTC, thomasspriggs commented on src/goto-instrument/goto_instrument_parse_options.cpp
> +    remove_returns(goto_model);
Done.

2022-09-06 20:01 UTC, TGWDB approved these changes

2022-09-07 11:03 UTC, thomasspriggs commented
@tautschnig Can you re-review this please?

2022-09-07 11:06 UTC, peterschrammel approved these changes
Good as a partial workaround. Eventually, the constant propgator should be replaced by functionality from goto-analyzer, as @martin-cs suggests.

2022-09-07 13:17 UTC, tautschnig approved these changes

2022-09-07 13:17 UTC, merged