Support byte extract and update for new SMT backend
diffblue/cbmc pull request #7285
Opened 2022-10-31 16:47 UTC by esteffin

This PR adds support for byte_extract_exprt and byte_update_exprt for the new incremental SMT backend.

- [ ] Each commit message has a non-empty body, explaining why the change was made.
- [ ] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [ ] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-11-03 17:06 UTC, thomasspriggs reviewed
This a partial review. I haven't reviewed the tests yet.

2022-11-03 17:06 UTC, thomasspriggs commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +  if(operands_are_of_type<bitvector_typet>(bitwise_and_expr))
:pick: I know why this change is being made in `convert_expr_to_smt.cpp`. However the rationale is missing from the commit history and it isn't necessarily obvious why the change is needed. I suggest we split the change to this file into a separate commit. Then the change can be described in the commit title and the rationale explained in the commit body.
:hammer: The changes to `convert_expr_to_smt` are missing corresponding unit tests.

2022-11-03 17:06 UTC, thomasspriggs commented on src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +  const exprt expr = lower_byte_operators(in_expr, ns);
:bulb: I suggest we rename `expr` to `lowered` or `lowered_expr`. `expr` is fine as a variable name for an `exprt` in a function using a single expression, but it becomes more confusing as soon as we have 2 of them.

2022-11-03 17:06 UTC, thomasspriggs commented on src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +  expression_handle_identifiers.emplace(in_expr, function.identifier());
:no_entry_sign: Please squash this commit into the previous commit with the other changes to `smt2_incremental_decision_procedure.cpp`. The problem this commit fixes is introduced in the previous commit and I dislike having bugs introduced and fixed in different commits within the same PR.

2022-11-07 17:09 UTC, esteffin commented on src/solvers/smt2_incremental/convert_expr_to_smt.cpp
> +  if(operands_are_of_type<bitvector_typet>(bitwise_and_expr))
- Added unit tests.
- Moved to separate commit.

2022-11-07 17:16 UTC, esteffin commented on src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +  const exprt expr = lower_byte_operators(in_expr, ns);
Changed

2022-11-07 17:16 UTC, esteffin commented on src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +  expression_handle_identifiers.emplace(in_expr, function.identifier());
Squashed

2022-11-08 09:02 UTC, TGWDB approved these changes

2022-11-08 15:51 UTC, thomasspriggs commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +    const auto byte_extract = make_byte_extract(
:exclamation: This commit does not compile when checked out, due to a missing `#include <util/byte_operators.h>` needed for this line in the unit test.

2022-11-08 16:56 UTC, thomasspriggs commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +    const auto byte_extract = make_byte_extract(
I think the problems with this particular test are just down to it being squashed into the wrong commit.

2022-11-08 17:06 UTC, thomasspriggs requested changes
I think we should get the following sorted before merging -

1. Fixing the one unit test which is squashed into the wrong commit.
2. Adding commit message bodies. The commits now (mostly) say what they do, which is great. But some of the pre-requisite fixes are still missing the context as to why they are needed. I am happy to go through adding these with you.

2022-11-08 17:06 UTC, thomasspriggs commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +          smt_bit_vector_constant_termt{18446744073709486335UL, 64}),
:pick: I think this mask would be easier to interpret as a hex literal.

2022-11-08 17:06 UTC, thomasspriggs commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +        smt_bit_vector_constant_termt{2816UL, 64}));
:pick: I think the literal `2816UL` may be easier to read as `11UL << 8`. This would make it clearer that it corresponds to the 11 in the input expression.

2022-11-08 17:06 UTC, thomasspriggs commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +TEST_CASE(
:+1: Looks like a good test to me.

2022-11-08 18:03 UTC, esteffin commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +    const auto byte_extract = make_byte_extract(
Fixed

2022-11-08 18:03 UTC, esteffin commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +          smt_bit_vector_constant_termt{18446744073709486335UL, 64}),
Changed

2022-11-08 18:03 UTC, esteffin commented on unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
> +        smt_bit_vector_constant_termt{2816UL, 64}));
changed

2022-11-08 20:01 UTC, thomasspriggs approved these changes

2022-11-08 20:01 UTC, merged