Extend expr_initializer to support byte-wise initialization
diffblue/cbmc pull request #7392
Opened 2022-11-27 23:14 UTC by peterschrammel

Each byte of the expression is initialized to the given initialization expression, if possible.

This building block will be required for the shadow memory implementation.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- [X] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [ ] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- [ ] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2022-11-28 08:26 UTC, tautschnig commented
Given I don't have enough context just yet the following may be a stupid idea, apologies for that: couldn't you instead use `byte_extract(array_of<char[sizeof(target-type)]>(init_value), 0, target-type)`?

2023-02-12 11:45 UTC, peterschrammel commented
> Given I don't have enough context just yet the following may be a stupid idea, apologies for that: couldn't you instead use byte_extract(array_of<char[sizeof(target-type)]>(init_value), 0, target-type)?

That may not as stupid as it sounds. Let me try. If it works then the entire `expr_initializer` class can be replaced by this single statement.

2023-02-12 15:41 UTC, kroening commented
> > Given I don't have enough context just yet the following may be a stupid idea, apologies for that: couldn't you instead use byte_extract(array_of<char[sizeof(target-type)]>(init_value), 0, target-type)?
> 
> That may not be as stupid as it sounds. Let me try. If it works then the entire `expr_initializer` class can be replaced by this single statement.

Please keep in mind that Goto programs are meant to be consumed by a broad variety of analysis methods. Virtually all but symex will choke on the above.

2023-07-06 11:37 UTC, esteffin commented
> > > Given I don't have enough context just yet the following may be a stupid idea, apologies for that: couldn't you instead use byte_extract(array_of<char[sizeof(target-type)]>(init_value), 0, target-type)?
> > 
> > 
> > That may not be as stupid as it sounds. Let me try. If it works then the entire `expr_initializer` class can be replaced by this single statement.
> 
> Please keep in mind that Goto programs are meant to be consumed by a broad variety of analysis methods. Virtually all but symex will choke on the above.

I agree. We should create a goto that can be consumed by analysis methods other than symex.
An option can be to run `lower_byte_operators` to the output of the `byte_extract(array_of<char[sizeof(target-type)]>(init_value), 0, target-type)` call, but it seems not so clean compared to what is in this PR (just an extension of the already existing `expr_initializert`).

2023-07-06 11:38 UTC, esteffin requested changes
Looks good although it needs unit tests + a few minor comments

2023-07-06 11:38 UTC, esteffin commented on src/util/expr_initializer.cpp
> +      to_bitvector_type(output_type).get_width() / config.ansi_c.char_width;
This should check that `to_bitvector_type(output_type).get_width()` is divisible by `config.ansi_c.char_width` otherwise it may be smaller!!!

2023-07-06 11:38 UTC, esteffin commented on src/util/expr_initializer.cpp
> +/// output type.
Should this be an invariant instead?

2023-07-06 11:38 UTC, esteffin commented on src/util/expr_initializer.cpp
> +      to_bitvector_type(output_type).get_width() / config.ansi_c.char_width;
Why not a more modern?

```suggestion
  if(
    const auto bv_type =
      type_try_dynamic_cast<integer_bitvector_typet>(output_type))
  {
    const size_t size = bv_type->get_width() / config.ansi_c.char_width;
```

2023-07-06 11:48 UTC, peterschrammel commented on src/util/expr_initializer.cpp
> +/// output type.
No, we need to deal with all output types (casting is the fallback behaviour).

2023-07-06 11:48 UTC, peterschrammel commented on src/util/expr_initializer.cpp
> +      to_bitvector_type(output_type).get_width() / config.ansi_c.char_width;
We should probably fall back to a cast if it is smaller (and this behaviour needs to be documented).

2023-07-06 17:29 UTC, esteffin commented
Rebased to the latest `origin/develop`.

2023-07-31 16:56 UTC, esteffin commented
PR rebased, added tests and ready to review.

2023-07-31 16:56 UTC, esteffin commented on src/util/expr_initializer.cpp
> +      to_bitvector_type(output_type).get_width() / config.ansi_c.char_width;
Changed

2023-07-31 16:57 UTC, esteffin commented on src/util/expr_initializer.cpp
> +/// output type.
Left as it was

2023-07-31 16:57 UTC, esteffin commented on src/util/expr_initializer.cpp
> +      to_bitvector_type(output_type).get_width() / config.ansi_c.char_width;
Changed

2023-07-31 20:21 UTC, peterschrammel reviewed
LGTM

2023-08-01 00:00 UTC, esteffin approved these changes

2023-08-01 11:05 UTC, NlightNFotis approved these changes

2023-08-01 16:08 UTC, tautschnig approved these changes

2023-08-01 16:09 UTC, merged