CONTRACTS: `dfcc_is_cprover_symbol` now uses allow lists to match symbols
diffblue/cbmc pull request #7708
Opened 2023-05-11 18:42 UTC by remi-delmas-3000

Assignments to  special `__CPROVER_*` or `*$object` symbols that are essentially ghost state must not be checked under DFCC.  In the same way built-in `__CPROVER_` or `__VERIFIER` or `nondet_`  functions must not be instrumented by DFCC.

Before, these special symbols were detected by matching a prefix or a suffix, which could allow users to bypass DFCC checks by naming their symbols with these prefixes or suffixes.

Instead we propose to maintain finite sets of function symbols and static symbols which are known to be exempt from DFCC instrumentation, and to test membership in that list. 

We add tests that demonstrate that checks are not bypassed even when symbols have the special prefixes.

- [x] Each commit message has a non-empty body, explaining why the change was made.
- [x] Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [x] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- [ ] My commit message includes data points confirming performance improvements (if claimed).
- [x] My PR is restricted to a single feature or bugfix.
- [x] White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2023-05-11 18:43 UTC, remi-delmas-3000 commented
If anyone can suggest a better solution (this one is sound but could be hard to maintain as we add new special symbols).

2023-05-12 13:49 UTC, tautschnig requested changes
See suggestion below in order to avoid a global-scoped static object.

2023-05-12 13:49 UTC, tautschnig commented on src/goto-instrument/contracts/dynamic-frames/dfcc_is_cprover_symbol.cpp
> +static std::unordered_set<irep_idt> static_symbols;
Both of these could safely be moved into their respective `dfcc_is_...` functions: the `init` functions would just have to take a reference to the set as a parameter.

2023-05-12 13:49 UTC, tautschnig commented on src/goto-instrument/contracts/dynamic-frames/dfcc_is_cprover_symbol.cpp
> +    static_symbols.insert(CPROVER_PREFIX "memory_leak");
Here and above: may I suggest to use lexicographic ordering?

2023-05-12 13:49 UTC, tautschnig commented on src/goto-instrument/contracts/dynamic-frames/dfcc_is_cprover_symbol.cpp
> +         has_suffix(str, "$object");
You will now be better off inlining the `id2string` use so that it will only be done when the lookup in `static_symbols` fails.

2023-05-19 23:56 UTC, feliperodri approved these changes

2023-05-19 23:56 UTC, feliperodri commented on src/goto-instrument/contracts/dynamic-frames/dfcc_is_cprover_symbol.h
> +/// Returns `true` iff the symbol is one of the know CPROVER static
```suggestion
/// Returns `true` iff the symbol is one of the known CPROVER static
```

2023-05-22 10:55 UTC, tautschnig approved these changes

2023-05-22 10:55 UTC, merged