Remove `get_value` and `set_value` from `string_constantt`
diffblue/cbmc pull request #7999
Opened 2023-11-07 10:57 UTC by NlightNFotis

Remove `string_constantt::get_value` and `string_constantt::set_value`.

Marked `DEPRECATED` over the `value()` calls (they were already working by dispatching to `value()`, so they were kind of a useless indirection/duplication).

2023-11-07 11:35 UTC, thomasspriggs commented
This should probably be 2 commits. A first commit removing the usage and a second commit removing the functions. That way if any downstream users temporarily want the functions back, then it is easier for them to revert the second commit without reverting the first (in their fork / subtree).

2023-11-07 15:24 UTC, NlightNFotis commented
I thought there was a rule for commits to be atomic and buildable for each one of them, in case there needs to be a bisection or something else happens that lands a developer on the commit and needs to build it.

In that case, if I split this into two commits, the first one is not going to be buildable.

2023-11-07 18:53 UTC, tautschnig requested changes
Quoting our coding guidelines:
"Any deprecated functionality should remain in place for at least six months from the date of deprecation. Before deprecating code, all in-tree uses should be replaced or marked as deprecated."

So let's please have the first commit, and put the second commit in a PR of its own that should remain in Draft state for the next 6 months.

2023-11-09 16:38 UTC, NlightNFotis commented
@tautschnig Done (cleaned up this PR). Will raise the other PR as draft now.

2023-11-09 16:41 UTC, NlightNFotis commented
Okay raised draft PR for the second part at https://github.com/diffblue/cbmc/pull/8003

2023-11-09 18:46 UTC, kroening approved these changes

2023-11-20 10:18 UTC, tautschnig approved these changes

2023-12-15 18:50 UTC, peterschrammel approved these changes

2023-12-15 19:09 UTC, merged