Add IEEE 754 TiesToAway rounding mode
diffblue/cbmc pull request #8515
Opened 2024-11-20 14:00 UTC by kroening

This adds IEEE 754 TiesToAway rounding mode, which rounds away from zero in case of a tie.

- [X] Each commit message has a non-empty body, explaining why the change was made.
- n/a Methods or procedures I have added are documented, following the guidelines provided in CODING_STANDARD.md.
- [ ] The feature or user visible behaviour I have added or modified has been documented in the User Guide in doc/cprover-manual/
- [X] Regression or unit tests are included, or existing tests cover the modified code (in this case I have detailed which ones those are in the commit message).
- n/a My commit message includes data points confirming performance improvements (if claimed).
- [X] My PR is restricted to a single feature or bugfix.
- n/a White-space or formatting changes outside the feature-related changed lines are in commits of their own.

2025-02-04 17:33 UTC, peterschrammel approved these changes

2025-02-07 14:28 UTC, tautschnig requested changes
Looks good except the below piece that I believe to be wrong.

2025-02-07 14:28 UTC, tautschnig commented on src/solvers/smt2/smt2_conv.cpp
> +    out << "roundTowardAway";
Shouldn't this be `RoundNearestTiesToAway`?

2025-02-11 11:29 UTC, kroening commented on src/solvers/smt2/smt2_conv.cpp
> +    out << "roundTowardAway";
Indeed, fixed.

2025-02-11 12:10 UTC, tautschnig approved these changes

2025-02-11 13:17 UTC, merged